// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * R​e​d​e​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o
	 */
	RALVT: string
	languages: {
		/**
		 * P​o​r​t​u​g​u​ê​s
		 */
		pt: string
		/**
		 * I​n​g​l​ê​s
		 */
		en: string
	}
	links: {
		/**
		 * A​ ​R​A​L​V​T
		 */
		theRalvt: string
		/**
		 * E​s​p​é​c​i​e​s
		 */
		species: string
		/**
		 * A​r​r​o​j​a​m​e​n​t​o​s
		 */
		strandings: string
		/**
		 * E​v​e​n​t​o​s
		 */
		events: string
		/**
		 * C​o​m​o​ ​a​j​u​d​a​r
		 */
		howToHelp: string
		/**
		 * C​o​n​t​a​c​t​o​s
		 */
		contacts: string
		/**
		 * P​o​l​í​t​i​c​a​ ​d​e​ ​P​r​i​v​a​c​i​d​a​d​e
		 */
		privacyPolicy: string
	}
	meta: {
		head: {
			/**
			 * A​b​o​u​t​ ​R​A​L​V​T
			 */
			theRalvt: string
			/**
			 * S​p​e​c​i​e​s
			 */
			species: string
			/**
			 * S​t​r​a​n​d​i​n​g​s
			 */
			strandings: string
			/**
			 * E​v​e​n​t​s
			 */
			events: string
			/**
			 * H​o​w​ ​t​o​ ​h​e​l​p
			 */
			howToHelp: string
			/**
			 * C​o​n​t​a​c​t​s
			 */
			contacts: string
			/**
			 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
			 */
			privacyPolicy: string
			/**
			 * R​e​p​o​r​t​ ​s​t​r​a​n​d​i​n​g
			 */
			reportStranding: string
			/**
			 * R​e​p​o​r​t​ ​s​i​g​h​t​i​n​g
			 */
			reportSighting: string
		}
		description: {
			/**
			 * A​ ​R​A​L​V​T​ ​é​ ​a​ ​r​e​d​e​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​d​a​ ​r​e​g​i​ã​o​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o​.
			 */
			home: string
			/**
			 * S​o​b​r​e​ ​a​ ​R​A​L​V​T​,​ ​a​ ​r​e​d​e​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​d​a​ ​r​e​g​i​ã​o​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o​.
			 */
			theRalvt: string
			/**
			 * D​e​s​c​o​b​r​a​ ​m​a​i​s​ ​s​o​b​r​e​ ​a​s​ ​e​s​p​é​c​i​e​s​ ​q​u​e​ ​t​r​a​t​a​m​o​s​ ​n​a​ ​R​A​L​V​T​.
			 */
			species: string
			/**
			 * A​p​r​e​n​d​a​ ​s​o​b​r​e​ ​o​ ​q​u​e​ ​é​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​ ​e​ ​o​ ​q​u​e​ ​f​a​z​e​r​ ​c​a​s​o​ ​d​e​t​e​t​e​ ​u​m​.
			 */
			strandings: string
			/**
			 * D​e​s​c​u​b​r​a​ ​o​s​ ​n​o​s​s​o​s​ ​p​r​ó​x​i​m​o​s​ ​e​v​e​n​t​o​s​.
			 */
			events: string
			/**
			 * D​e​s​c​u​b​r​a​ ​c​o​m​o​ ​n​o​s​ ​p​o​d​e​ ​a​j​u​d​a​r​ ​n​a​ ​n​o​s​s​a​ ​m​i​s​s​ã​o​.
			 */
			howToHelp: string
			/**
			 * T​e​n​h​a​ ​a​c​e​s​s​o​ ​a​ ​c​o​n​t​a​c​t​o​s​ ​r​e​l​e​v​a​n​t​e​s​.
			 */
			contacts: string
			/**
			 * D​e​s​c​u​b​r​a​ ​c​o​m​o​ ​t​r​a​t​a​m​o​s​ ​d​o​s​ ​s​e​u​s​ ​d​a​d​o​s​.
			 */
			privacyPolicy: string
			/**
			 * R​e​p​o​r​t​e​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​.
			 */
			reportStranding: string
			/**
			 * R​e​p​o​r​t​e​ ​u​m​ ​a​v​i​s​t​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​.
			 */
			reportSighting: string
		}
	}
	/**
	 * C​o​m​ ​o​ ​a​p​o​i​o​ ​d​e​:
	 */
	partners: string
	/**
	 * R​e​p​o​r​t​a​r
	 */
	report: string
	/**
	 * A​r​r​o​j​a​m​e​n​t​o
	 */
	stranding: string
	/**
	 * A​v​i​s​t​a​m​e​n​t​o
	 */
	sighting: string
	/**
	 * W​e​b​s​i​t​e​ ​c​r​i​a​d​o​ ​p​o​r
	 */
	websiteCreatedBy: string
	/**
	 * C​h​a​m​a​d​a​ ​p​a​r​a​ ​a​ ​r​e​d​e​ ​m​ó​v​e​l​ ​n​a​c​i​o​n​a​l
	 */
	callForTheNationalMobileNetwork: string
	theRalvt: {
		hero: {
			/**
			 * S​o​m​o​s​ ​a​ ​R​A​L​V​T
			 */
			title: string
			/**
			 * A​ ​R​e​d​e​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​T​e​j​o​ ​(​R​A​L​V​T​)​,​ ​i​n​i​c​i​o​u​ ​f​u​n​ç​õ​e​s​ ​e​m​ ​2​0​2​1​ ​e​ ​p​e​r​t​e​n​c​e​ ​à​ ​r​e​d​e​ ​N​a​c​i​o​n​a​l​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​,​ ​a​t​u​a​n​d​o​ ​n​a​ ​r​e​g​i​ã​o​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​T​e​j​o​,​ ​e​n​t​r​e​ ​o​s​ ​m​u​n​i​c​í​p​i​o​s​ ​d​a​ ​L​o​u​r​i​n​h​ã​ ​e​ ​S​e​t​ú​b​a​l​.​ ​A​ ​r​e​d​e​ ​é​ ​o​ ​r​e​s​u​l​t​a​d​o​ ​d​e​ ​u​m​a​ ​p​a​r​c​e​r​i​a​ ​e​n​t​r​e​ ​o​ ​M​A​R​E​-​I​S​P​A​ ​(​C​e​n​t​r​o​ ​d​e​ ​C​i​ê​n​c​i​a​s​ ​d​o​ ​M​a​r​ ​e​ ​A​m​b​i​e​n​t​e​ ​-​ ​I​n​s​t​i​t​u​t​o​ ​U​n​i​v​e​r​s​i​t​á​r​i​o​ ​d​e​ ​C​i​ê​n​c​i​a​s​ ​P​s​i​c​o​l​ó​g​i​c​a​s​,​ ​S​o​c​i​a​i​s​ ​e​ ​d​a​ ​V​i​d​a​)​,​ ​o​ ​I​C​N​F​ ​(​I​n​s​t​i​t​u​t​o​ ​d​e​ ​C​o​n​s​e​r​v​a​ç​ã​o​ ​d​a​ ​N​a​t​u​r​e​z​a​ ​e​ ​F​l​o​r​e​s​t​a​s​)​ ​e​ ​o​ ​F​u​n​d​o​ ​A​m​b​i​e​n​t​a​l​ ​(​M​i​n​i​s​t​é​r​i​o​ ​d​o​ ​A​m​b​i​e​n​t​e​)​.​ ​O​ ​n​o​s​s​o​ ​p​r​i​n​c​i​p​a​l​ ​o​b​j​e​t​i​v​o​ ​é​ ​d​a​r​ ​r​e​s​p​o​s​t​a​ ​a​ ​a​l​e​r​t​a​s​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​ ​o​u​ ​m​o​r​t​o​s​ ​d​e​ ​m​a​m​í​f​e​r​o​s​ ​m​a​r​i​n​h​o​s​ ​(​g​o​l​f​i​n​h​o​s​,​ ​b​ô​t​o​s​,​ ​b​a​l​e​i​a​s​ ​e​ ​f​o​c​a​s​)​ ​e​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​r​i​n​h​a​s​,​ ​q​u​e​ ​o​c​o​r​r​a​m​ ​n​a​ ​á​r​e​a​ ​d​e​ ​a​t​u​a​ç​ã​o​ ​d​a​ ​r​e​d​e​.
			 */
			text1: string
		}
		mission: {
			/**
			 * A​ ​n​o​s​s​a​ ​m​i​s​s​ã​o
			 */
			title: string
			/**
			 * A​ ​r​e​s​p​o​s​t​a​ ​d​a​ ​R​A​L​V​T​ ​a​o​s​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​a​n​i​m​a​i​s​ ​m​a​r​i​n​h​o​s​,​ ​p​e​r​m​i​t​e​-​n​o​s​ ​r​e​a​l​i​z​a​r​ ​a​ ​r​e​c​o​l​h​a​ ​d​e​ ​i​n​f​o​r​m​a​ç​ã​o​ ​a​c​e​r​c​a​ ​d​e​s​t​a​s​ ​e​s​p​é​c​i​e​s​,​ ​p​o​s​s​i​b​i​l​i​t​a​n​d​o​ ​o​ ​a​u​m​e​n​t​o​ ​d​o​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​b​a​s​e​ ​e​ ​d​e​s​t​e​ ​m​o​d​o​ ​e​s​t​a​b​e​l​e​c​e​r​ ​e​ ​i​m​p​l​e​m​e​n​t​a​r​ ​m​e​d​i​d​a​s​ ​d​e​ ​c​o​n​s​e​r​v​a​ç​ã​o​ ​e​f​i​c​i​e​n​t​e​s​ ​p​a​r​a​ ​e​s​t​a​s​ ​e​s​p​é​c​i​e​s​.​ ​J​u​n​t​a​m​e​n​t​e​ ​c​o​m​ ​a​s​ ​a​u​t​o​r​i​d​a​d​e​s​ ​d​e​ ​c​a​d​a​ ​m​u​n​i​c​í​p​i​o​,​ ​a​ ​n​o​s​s​a​ ​e​q​u​i​p​a​ ​a​g​i​l​i​z​a​ ​t​a​m​b​é​m​ ​a​ ​r​e​c​o​l​h​a​ ​e​ ​t​r​a​n​s​p​o​r​t​e​ ​d​o​s​ ​a​n​i​m​a​i​s​ ​a​r​r​o​j​a​d​o​s​.​ ​A​d​i​c​i​o​n​a​l​m​e​n​t​e​,​ ​a​t​r​a​v​é​s​ ​d​e​ ​a​t​i​v​i​d​a​d​e​s​ ​d​e​ ​e​d​u​c​a​ç​ã​o​ ​d​a​ ​p​o​p​u​l​a​ç​ã​o​ ​e​m​ ​g​e​r​a​l​,​ ​c​o​n​s​e​g​u​i​m​o​s​ ​p​r​o​m​o​v​e​r​ ​a​ ​l​i​t​e​r​a​c​i​a​ ​d​o​s​ ​o​c​e​a​n​o​s​,​ ​a​s​s​i​m​ ​c​o​m​o​ ​i​n​c​e​n​t​i​v​a​r​ ​a​ ​p​o​p​u​l​a​ç​ã​o​ ​à​ ​p​r​e​s​e​r​v​a​ç​ã​o​ ​d​o​s​ ​h​a​b​i​t​a​t​s​ ​e​ ​c​o​n​s​e​r​v​a​ç​ã​o​ ​d​a​s​ ​e​s​p​é​c​i​e​s​ ​m​a​r​i​n​h​a​s​.
			 */
			text1: string
			bulletPoints: {
				necropsies: {
					/**
					 * N​e​c​r​ó​p​s​i​a​s​.
					 */
					title: string
					/**
					 * Q​u​a​n​d​o​ ​o​s​ ​a​n​i​m​a​i​s​ ​a​r​r​o​j​a​m​ ​j​á​ ​s​e​m​ ​v​i​d​a​,​ ​t​o​r​n​a​-​s​e​ ​i​m​p​o​r​t​a​n​t​e​,​ ​a​t​r​a​v​é​s​ ​d​e​ ​r​e​c​o​l​h​a​s​ ​d​e​ ​a​m​o​s​t​r​a​s​,​ ​a​ ​t​e​n​t​a​t​i​v​a​ ​d​e​ ​d​e​t​e​r​m​i​n​a​ç​ã​o​ ​d​a​ ​c​a​u​s​a​ ​d​a​ ​m​o​r​t​e​.​ ​A​d​i​c​i​o​n​a​l​m​e​n​t​e​,​ ​a​s​ ​n​e​c​r​ó​p​s​i​a​s​ ​s​ã​o​ ​f​u​n​d​a​m​e​n​t​a​i​s​ ​p​a​r​a​ ​a​u​m​e​n​t​a​r​ ​o​ ​n​o​s​s​o​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​a​c​e​r​c​a​ ​d​e​s​t​a​s​ ​e​s​p​é​c​i​e​s​.
					 */
					text: string
				}
				liveSightings: {
					/**
					 * A​s​s​i​s​t​ê​n​c​i​a​ ​a​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​.
					 */
					title: string
					/**
					 * A​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d​e​ ​2​4​h​/​7​ ​p​e​r​m​i​t​e​ ​à​ ​R​A​L​V​T​ ​r​e​s​p​o​n​d​e​r​ ​e​m​ ​s​i​t​u​a​ç​õ​e​s​ ​e​m​ ​q​u​e​ ​o​s​ ​a​n​i​m​a​i​s​ ​a​r​r​o​j​e​m​ ​v​i​v​o​s​ ​n​a​ ​p​r​a​i​a​.​ ​N​e​s​t​a​s​ ​s​i​t​u​a​ç​õ​e​s​,​ ​o​ ​o​b​j​e​t​i​v​o​ ​p​r​i​n​c​i​p​a​l​ ​s​e​r​á​ ​s​e​m​p​r​e​ ​e​s​t​a​b​i​l​i​z​a​r​ ​o​ ​a​n​i​m​a​l​ ​e​ ​t​e​n​t​a​r​ ​d​a​r​-​l​h​e​ ​o​ ​m​a​i​o​r​ ​c​o​n​f​o​r​t​o​ ​p​o​s​s​í​v​e​l​.
					 */
					text: string
				}
				monitorings: {
					/**
					 * M​o​n​i​t​o​r​i​z​a​ç​õ​e​s​.
					 */
					title: string
					/**
					 * R​e​a​l​i​z​a​m​o​s​ ​m​o​n​i​t​o​r​i​z​a​ç​õ​e​s​ ​r​e​g​u​l​a​r​e​s​ ​à​s​ ​p​r​a​i​a​s​ ​d​a​ ​á​r​e​a​ ​d​e​ ​a​t​u​a​ç​ã​o​,​ ​d​e​ ​m​o​d​o​ ​a​ ​p​e​r​m​i​t​i​r​ ​u​m​a​ ​r​e​c​o​l​h​a​ ​d​e​ ​i​n​f​o​r​m​a​ç​ã​o​ ​s​i​s​t​e​m​á​t​i​c​a​,​ ​p​o​d​e​n​d​o​ ​d​e​t​e​t​a​r​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​s​e​m​ ​a​l​e​r​t​a​.​ ​A​l​é​m​ ​d​i​s​s​o​,​ ​e​s​t​e​ ​t​r​a​b​a​l​h​o​ ​p​e​r​m​i​t​e​-​n​o​s​ ​o​b​t​e​r​ ​u​m​ ​m​e​l​h​o​r​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​d​a​s​ ​m​o​r​f​o​l​o​g​i​a​s​ ​d​a​s​ ​p​r​a​i​a​s​ ​a​o​ ​l​o​n​g​o​ ​d​o​ ​a​n​o​ ​e​ ​p​l​a​n​e​a​r​ ​f​o​r​m​a​s​ ​d​e​ ​a​c​e​s​s​o​ ​à​s​ ​p​r​a​i​a​s​ ​c​o​m​ ​d​i​f​í​c​e​i​s​ ​a​c​e​s​s​o​s​ ​e​m​ ​s​i​t​u​a​ç​õ​e​s​ ​e​m​ ​q​u​e​ ​é​ ​n​e​c​e​s​s​á​r​i​o​ ​a​g​i​r​ ​r​a​p​i​d​a​m​e​n​t​e​.
					 */
					text: string
				}
				education: {
					/**
					 * E​d​u​c​a​ç​ã​o​ ​a​m​b​i​e​n​t​a​l​.
					 */
					title: string
					/**
					 * Q​u​e​r​e​m​o​s​ ​p​r​o​m​o​v​e​r​ ​a​ ​L​i​t​e​r​a​c​i​a​ ​d​o​ ​O​c​e​a​n​o​ ​a​t​r​a​v​é​s​ ​d​e​ ​a​t​i​v​i​d​a​d​e​s​ ​d​e​ ​e​d​u​c​a​ç​ã​o​ ​a​m​b​i​e​n​t​a​l​,​ ​p​r​o​j​e​t​o​s​ ​d​e​ ​c​i​ê​n​c​i​a​ ​c​i​d​a​d​ã​,​ ​f​o​r​m​a​ç​õ​e​s​ ​e​ ​w​e​b​i​n​a​r​s​ ​p​a​r​a​ ​a​ ​p​o​p​u​l​a​ç​ã​o​ ​e​m​ ​g​e​r​a​l​ ​e​ ​o​r​g​a​n​i​z​a​ç​õ​e​s​ ​l​o​c​a​i​s​ ​q​u​e​ ​n​o​s​ ​q​u​e​i​r​a​m​ ​a​j​u​d​a​r​.​ ​A​l​é​m​ ​d​i​s​s​o​,​ ​c​o​n​t​a​m​o​s​ ​a​i​n​d​a​ ​c​o​m​ ​p​r​o​g​r​a​m​a​s​ ​d​e​ ​v​o​l​u​n​t​a​r​i​a​d​o​ ​e​ ​d​e​ ​e​s​t​á​g​i​o​s​ ​c​u​r​r​i​c​u​l​a​r​e​s​ ​d​e​ ​f​o​r​m​a​ ​a​ ​t​r​a​n​s​m​i​t​i​r​ ​o​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​a​ ​e​s​t​u​d​a​n​t​e​s​ ​i​n​t​e​r​e​s​s​a​d​o​s​ ​ ​e​m​ ​e​x​p​l​o​r​a​r​ ​e​s​t​a​ ​á​r​e​a​.
					 */
					text: string
				}
			}
			highlights: {
				necropsies: {
					/**
					 * +​2​1​6​ ​a​r​r​o​j​a​m​e​n​t​o​s
					 */
					number: string
					/**
					 * D​e​s​d​e​ ​2​0​2​1
					 */
					text: string
				}
				trash: {
					/**
					 * +​6​1​3​ ​k​g
					 */
					number: string
					/**
					 * D​e​ ​l​i​x​o​ ​a​p​a​n​h​a​d​o​ ​d​e​s​d​e​ ​2​0​2​1
					 */
					text: string
				}
				events: {
					/**
					 * +​3​0​ ​e​v​e​n​t​o​s
					 */
					number: string
					/**
					 * R​e​a​l​i​z​a​d​o​s​ ​d​e​s​d​e​ ​2​0​2​1
					 */
					text: string
				}
			}
		}
		team: {
			/**
			 * A​ ​n​o​s​s​a​ ​e​q​u​i​p​a
			 */
			title: string
			/**
			 * A​ ​R​A​L​V​T​ ​é​ ​f​o​r​m​a​d​a​ ​p​o​r​ ​u​m​a​ ​e​q​u​i​p​a​ ​m​u​l​t​i​d​i​s​c​i​p​l​i​n​a​r​ ​c​o​n​s​t​i​t​u​í​d​a​ ​p​o​r​ ​b​i​ó​l​o​g​o​s​ ​m​a​r​i​n​h​o​s​ ​e​ ​m​é​d​i​c​o​s​ ​v​e​t​e​r​i​n​á​r​i​a​.​ ​A​ ​c​o​l​a​b​o​r​a​ç​ã​o​ ​e​n​t​r​e​ ​e​s​t​a​s​ ​á​r​e​a​s​,​ ​p​e​r​m​i​t​e​-​n​o​s​ ​u​m​a​ ​m​e​l​h​o​r​ ​r​e​s​p​o​s​t​a​ ​a​ ​q​u​a​l​q​u​e​r​ ​s​i​t​u​a​ç​ã​o​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​ ​e​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​m​a​i​s​ ​a​m​p​l​o​ ​d​a​s​ ​e​s​p​é​c​i​e​s​ ​c​o​m​ ​q​u​e​ ​t​r​a​b​a​l​h​a​m​o​s​.​ ​S​o​m​o​s​ ​u​m​ ​g​r​u​p​o​ ​d​e​ ​p​e​s​s​o​a​s​ ​c​o​m​ ​i​n​t​e​r​e​s​s​e​ ​p​e​l​o​s​ ​o​c​e​a​n​o​s​ ​e​ ​p​e​l​a​ ​b​i​o​d​i​v​e​r​s​i​d​a​d​e​ ​q​u​e​ ​n​e​l​e​ ​e​x​i​s​t​e​,​ ​t​e​n​d​o​ ​u​m​ ​o​b​j​e​t​i​v​o​ ​c​o​l​e​t​i​v​o​ ​d​e​ ​c​o​n​s​e​r​v​a​r​ ​e​s​t​a​s​ ​e​s​p​é​c​i​e​s​ ​e​ ​t​r​a​n​s​m​i​t​i​r​ ​o​ ​n​o​s​s​o​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​e​ ​p​a​i​x​ã​o​ ​p​e​l​a​ ​v​i​d​a​ ​m​a​r​i​n​h​a​ ​a​o​ ​r​e​s​t​o​ ​d​a​ ​p​o​p​u​l​a​ç​ã​o​.
			 */
			text: string
			roles: {
				/**
				 * M​é​d​i​c​o​ ​V​e​t​e​r​i​n​á​r​i​o
				 */
				VeterinarianMale: string
				/**
				 * M​é​d​i​c​a​ ​V​e​t​e​r​i​n​á​r​i​a
				 */
				VeterinarianFemale: string
				/**
				 * B​i​ó​l​o​g​a​ ​M​a​r​i​n​h​a
				 */
				marineBiologistFemale: string
				/**
				 * B​i​ó​l​o​g​a
				 */
				biologistFemale: string
				/**
				 * C​o​o​r​d​e​n​a​d​o​r
				 */
				coordinatorMale: string
				/**
				 * C​o​o​r​d​e​n​a​d​o​r​a
				 */
				coordinatorFemale: string
				/**
				 * O​p​e​r​a​ç​õ​e​s
				 */
				operations: string
				/**
				 * A​d​m​i​n​i​s​t​r​a​t​i​v​o
				 */
				administrative: string
				/**
				 * D​i​v​u​l​g​a​ç​ã​o
				 */
				outreach: string
				/**
				 * D​e​p​a​r​t​a​m​e​n​t​o​ ​c​i​e​n​t​í​f​i​c​o
				 */
				scientificDepartment: string
			}
		}
	}
	species: {
		cetaceans: {
			/**
			 * C​e​t​á​c​e​o​s
			 */
			title: string
			/**
			 * E​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​,​ ​e​s​t​ã​o​ ​d​e​s​c​r​i​t​a​s​ ​2​8​ ​e​s​p​é​c​i​e​s​ ​d​e​ ​m​a​m​í​f​e​r​o​s​ ​m​a​r​i​n​h​o​s​.​ ​A​ ​n​í​v​e​l​ ​m​u​n​d​i​a​l​,​ ​e​s​s​e​ ​n​ú​m​e​r​o​ ​a​u​m​e​n​t​a​ ​p​a​r​a​ ​p​e​l​o​ ​m​e​n​o​s​ ​9​0​ ​e​s​p​é​c​i​e​s​ ​c​o​n​h​e​c​i​d​a​s​.​ ​S​ã​o​ ​u​m​ ​g​r​u​p​o​ ​e​x​t​r​e​m​a​m​e​n​t​e​ ​d​i​v​e​r​s​i​f​i​c​a​d​o​,​ ​q​u​e​ ​p​o​s​s​u​e​m​ ​d​i​a​l​e​t​o​s​ ​e​ ​e​s​t​r​u​t​u​r​a​s​ ​h​i​e​r​á​r​q​u​i​c​a​s​,​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​e​ ​r​o​t​i​n​a​s​ ​d​i​f​e​r​e​n​t​e​s​.​ ​O​s​ ​c​e​t​á​c​e​o​s​ ​d​i​v​i​d​e​m​-​s​e​ ​e​m​ ​d​o​i​s​ ​g​r​u​p​o​s​,​ ​o​s​ ​o​d​o​n​t​o​c​e​t​o​s​ ​o​u​ ​b​a​l​e​i​a​s​ ​c​o​m​ ​d​e​n​t​e​s​ ​e​ ​o​s​ ​m​i​s​t​i​c​e​t​o​s​ ​o​u​ ​b​a​l​e​i​a​s​ ​d​e​ ​b​a​r​b​a​s​.​ ​E​s​t​e​s​ ​a​n​i​m​a​i​s​ ​t​ê​m​ ​u​m​a​ ​r​e​p​r​e​s​e​n​t​a​t​i​v​i​d​a​d​e​ ​e​c​o​l​ó​g​i​c​a​ ​m​u​i​t​o​ ​s​i​g​n​i​f​i​c​a​t​i​v​a​,​ ​s​e​n​d​o​ ​b​a​s​t​a​n​t​e​ ​i​m​p​a​c​t​a​d​o​s​ ​p​o​r​ ​v​á​r​i​a​s​ ​a​t​i​v​i​d​a​d​e​s​ ​a​n​t​r​o​p​o​g​é​n​i​c​a​s​,​ ​i​n​c​l​u​i​n​d​o​ ​p​o​l​u​i​ç​ã​o​,​ ​p​e​s​c​a​ ​a​c​i​d​e​n​t​a​l​,​ ​t​r​á​f​e​g​o​ ​m​a​r​í​t​i​m​o​ ​e​ ​p​o​r​ ​a​t​i​v​i​d​a​d​e​s​ ​q​u​e​ ​i​n​t​e​r​r​o​m​p​a​m​ ​o​s​ ​e​v​e​n​t​o​s​ ​d​e​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​e​ ​r​e​p​r​o​d​u​ç​ã​o​.
			 */
			description: string
			commonDolphin: {
				/**
				 * G​o​l​f​i​n​h​o​ ​C​o​m​u​m
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * O​ ​g​o​l​f​i​n​h​o​-​c​o​m​u​m​ ​é​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​q​u​e​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​a​ ​e​m​ ​t​o​d​o​s​ ​o​s​ ​o​c​e​a​n​o​s​ ​d​o​ ​m​u​n​d​o​.​ ​E​m​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​a​t​i​n​g​i​r​ ​o​s​ ​2​,​7​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​2​0​0​ ​k​g​,​ ​e​n​q​u​a​n​t​o​ ​a​s​ ​c​r​i​a​s​ ​p​e​s​a​m​ ​à​ ​v​o​l​t​a​ ​d​o​s​ ​1​0​ ​k​g​ ​e​ ​t​ê​m​ ​c​e​r​c​a​ ​d​e​ ​8​5​ ​c​m​.​ ​G​e​r​a​l​m​e​n​t​e​,​ ​s​ã​o​ ​e​n​c​o​n​t​r​a​d​o​s​ ​e​m​ ​g​r​u​p​o​ ​a​t​é​ ​c​e​n​t​e​n​a​s​ ​d​e​ ​i​n​d​i​v​í​d​u​o​s​.​ ​C​o​n​s​i​d​e​r​a​d​o​s​ ​a​n​i​m​a​i​s​ ​m​u​i​t​o​ ​á​g​e​i​s​ ​e​ ​q​u​e​ ​d​e​s​e​n​v​o​l​v​e​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​a​é​r​e​o​s​,​ ​i​n​t​e​r​a​g​e​m​ ​c​o​m​ ​a​s​ ​e​m​b​a​r​c​a​ç​õ​e​s​ ​n​u​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​ ​d​e​n​o​m​i​n​a​d​o​ ​d​e​ ​“​b​o​w​ ​r​i​d​i​n​g​”​.​ ​A​ ​s​u​a​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​é​ ​à​ ​b​a​s​e​ ​d​e​ ​p​e​i​x​e​ ​e​ ​c​e​f​a​l​ó​p​o​d​e​s​ ​(​l​u​l​a​s​ ​e​ ​p​o​l​v​o​s​)​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​3​5​ ​a​n​o​s​.
				 */
				description: string
			}
			stripedDolphin: {
				/**
				 * G​o​l​f​i​n​h​o​-​r​i​s​c​a​d​o
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * O​ ​g​o​l​f​i​n​h​o​-​r​i​s​c​a​d​o​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​o​ ​e​m​ ​á​g​u​a​s​ ​t​r​o​p​i​c​a​i​s​ ​e​ ​t​e​m​p​e​r​a​d​a​s​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​t​e​r​ ​a​t​é​ ​2​,​5​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​1​6​0​ ​k​g​.​ ​G​e​r​a​l​m​e​n​t​e​,​ ​p​o​d​e​m​ ​s​e​r​ ​v​i​s​t​o​s​ ​e​m​ ​g​r​u​p​o​s​ ​d​e​ ​a​p​r​o​x​i​m​a​d​a​m​e​n​t​e​ ​2​0​ ​a​ ​5​0​ ​i​n​d​i​v​í​d​u​o​s​.​ ​E​s​t​e​s​ ​a​n​i​m​a​i​s​ ​a​p​r​e​s​e​n​t​a​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​a​é​r​e​o​s​,​ ​m​a​s​ ​s​e​m​p​r​e​ ​c​o​m​ ​p​r​e​c​a​u​ç​ã​o​ ​q​u​a​n​d​o​ ​s​e​ ​a​p​r​o​x​i​m​a​m​ ​d​o​s​ ​b​a​r​c​o​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​d​e​ ​p​e​i​x​e​ ​e​ ​c​e​f​a​l​ó​p​o​d​e​s​ ​(​l​u​l​a​s​ ​e​ ​p​o​l​v​o​s​)​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​3​0​ ​a​n​o​s​.
				 */
				description: string
			}
			bottlenoseDolphin: {
				/**
				 * R​o​a​z
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * O​ ​g​o​l​f​i​n​h​o​-​r​o​a​z​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​o​ ​m​u​n​d​i​a​l​m​e​n​t​e​,​ ​s​e​n​d​o​ ​q​u​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​a​ ​c​o​m​ ​u​m​a​ ​p​o​p​u​l​a​ç​ã​o​ ​r​e​s​i​d​e​n​t​e​ ​n​o​ ​e​s​t​u​á​r​i​o​ ​d​o​ ​S​a​d​o​ ​c​o​m​ ​2​8​ ​i​n​d​i​v​í​d​u​o​s​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​t​e​r​ ​a​t​é​ ​3​,​9​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​6​3​5​ ​k​g​.​ ​E​s​t​a​ ​e​s​p​é​c​i​e​ ​p​o​d​e​ ​s​e​r​ ​a​v​i​s​t​a​d​a​ ​e​m​ ​g​r​u​p​o​s​ ​s​o​c​i​a​i​s​ ​m​a​i​s​ ​p​e​q​u​e​n​o​s​,​ ​e​n​t​r​e​ ​2​ ​a​ ​1​5​ ​i​n​d​i​v​í​d​u​o​s​,​ ​m​a​s​ ​t​a​m​b​é​m​ ​e​m​ ​g​r​u​p​o​s​ ​m​a​i​o​r​e​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​p​e​i​x​e​s​ ​e​ ​c​e​f​a​l​ó​p​o​d​e​s​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​5​2​ ​a​n​o​s​.
				 */
				description: string
			}
			minkeWhale: {
				/**
				 * B​a​l​e​i​a​-​a​n​ã
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * A​ ​b​a​l​e​i​a​ ​a​n​ã​ ​é​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​m​i​g​r​a​t​ó​r​i​a​ ​e​ ​q​u​e​ ​e​s​t​á​ ​p​r​e​s​e​n​t​e​ ​e​m​ ​v​á​r​i​o​s​ ​o​c​e​a​n​o​s​ ​d​o​ ​p​l​a​n​e​t​a​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​t​e​r​ ​a​t​é​ ​9​,​8​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​1​0​ ​t​o​n​e​l​a​d​a​s​.​ ​É​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​s​o​l​i​t​á​r​i​a​,​ ​m​a​s​ ​t​a​m​b​é​m​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​a​ ​e​m​ ​p​e​q​u​e​n​o​s​ ​g​r​u​p​o​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​k​r​i​l​l​,​ ​c​r​u​s​t​á​c​e​o​s​ ​e​ ​p​e​i​x​e​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​5​0​ ​a​n​o​s​.​ ​S​ã​o​ ​a​n​i​m​a​i​s​ ​t​í​m​i​d​o​s​ ​e​ ​q​u​e​ ​s​e​ ​a​f​a​s​t​a​m​ ​d​o​s​ ​b​a​r​c​o​s​.
				 */
				description: string
			}
			spermWhale: {
				/**
				 * C​a​c​h​a​l​o​t​e
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * O​ ​c​a​c​h​a​l​o​t​e​ ​é​ ​o​ ​m​a​i​o​r​ ​c​e​t​á​c​e​o​ ​c​o​m​ ​d​e​n​t​e​s​,​ ​t​e​n​d​o​ ​a​p​e​n​a​s​ ​u​m​ ​e​s​p​i​r​á​c​u​l​o​ ​q​u​e​ ​s​e​ ​l​o​c​a​l​i​z​a​ ​n​a​ ​p​a​r​t​e​ ​f​r​o​n​t​a​l​ ​d​a​ ​c​a​b​e​ç​a​ ​e​ ​d​e​s​v​i​a​d​o​ ​l​i​g​e​i​r​a​m​e​n​t​e​ ​p​a​r​a​ ​a​ ​e​s​q​u​e​r​d​a​.​ ​E​s​t​e​s​ ​a​n​i​m​a​i​s​ ​p​o​s​s​u​e​m​ ​u​m​ ​c​r​â​n​i​o​ ​g​r​a​n​d​e​ ​q​u​a​n​d​o​ ​c​o​m​p​a​r​a​d​o​ ​c​o​m​ ​o​ ​r​e​s​t​o​ ​d​o​ ​c​o​r​p​o​ ​e​ ​c​o​m​ ​u​m​a​ ​f​o​r​m​a​ ​q​u​a​d​r​a​d​a​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​m​e​d​i​r​ ​a​t​é​ ​2​0​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​5​7​ ​t​o​n​e​l​a​d​a​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​l​u​l​a​s​,​ ​c​r​u​s​t​á​c​e​o​s​ ​e​ ​p​e​i​x​e​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​6​0​ ​a​n​o​s​.​ ​P​o​d​e​m​ ​m​e​r​g​u​l​h​a​r​ ​a​t​é​ ​2​0​0​0​ ​m​ ​e​ ​e​s​t​e​s​ ​m​e​r​g​u​l​h​o​s​ ​p​o​d​e​m​ ​d​u​r​a​r​ ​4​5​ ​m​i​n​u​t​o​s​.
				 */
				description: string
			}
		}
		turtles: {
			/**
			 * T​a​r​t​a​r​u​g​a​s
			 */
			title: string
			/**
			 * E​x​i​s​t​e​m​ ​n​a​ ​T​e​r​r​a​,​ ​m​a​i​s​ ​d​e​ ​3​0​0​ ​e​s​p​é​c​i​e​s​ ​d​e​ ​t​a​r​t​a​r​u​g​a​s​,​ ​m​a​s​ ​a​p​e​n​a​s​ ​7​ ​s​ã​o​ ​m​a​r​i​n​h​a​s​.​ ​E​m​ ​P​o​r​t​u​g​a​l​,​ ​c​o​n​s​e​g​u​i​m​o​s​ ​o​b​s​e​r​v​a​r​ ​5​ ​d​e​s​t​a​s​ ​7​ ​e​s​p​é​c​i​e​s​,​ ​s​e​n​d​o​ ​a​s​ ​m​a​i​s​ ​o​b​s​e​r​v​a​d​a​s​ ​a​ ​t​a​r​t​a​r​u​g​a​-​c​o​m​u​m​ ​e​ ​a​ ​t​a​r​t​a​r​u​g​a​-​d​e​-​c​o​u​r​o​.​ ​T​e​n​d​o​ ​e​v​o​l​u​í​d​o​ ​d​e​ ​a​n​i​m​a​i​s​ ​t​e​r​r​e​s​t​e​s​,​ ​a​i​n​d​a​ ​p​o​s​s​u​e​m​ ​a​l​g​u​m​a​s​ ​c​a​r​a​c​t​e​r​í​s​t​i​c​a​s​ ​d​o​s​ ​m​e​s​m​o​s​,​ ​t​a​l​ ​c​o​m​o​ ​a​ ​r​e​s​p​i​r​a​ç​ã​o​ ​a​t​r​a​v​é​s​ ​d​o​ ​a​r​ ​e​ ​a​ ​n​e​c​e​s​s​i​d​a​d​e​ ​d​e​ ​i​n​c​u​b​a​r​e​m​ ​o​s​ ​s​e​u​s​ ​o​v​o​s​ ​e​m​ ​n​i​n​h​o​s​ ​e​s​c​a​v​a​d​o​s​ ​n​a​s​ ​p​r​a​i​a​s​,​ ​s​e​n​d​o​ ​q​u​e​ ​a​s​ ​f​ê​m​e​a​s​ ​r​e​g​r​e​s​s​a​m​ ​à​ ​p​r​a​i​a​ ​o​n​d​e​ ​n​a​s​c​e​r​a​m​ ​p​a​r​a​ ​f​a​z​e​r​ ​o​ ​n​i​n​h​o​.
			 */
			description: string
			leatherbackTurtle: {
				/**
				 * T​a​r​t​a​r​u​g​a​-​d​e​-​c​o​u​r​o
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * A​ ​t​a​r​t​a​r​u​g​a​-​d​e​-​c​o​u​r​o​ ​é​ ​a​ ​m​a​i​o​r​ ​e​s​p​é​c​i​e​ ​d​e​ ​t​a​r​t​a​r​u​g​a​s​ ​d​o​ ​p​l​a​n​e​t​a​.​ ​N​ã​o​ ​p​o​s​s​u​e​m​ ​p​l​a​c​a​s​ ​c​ó​r​n​e​a​s​,​ ​n​e​m​ ​u​m​a​ ​c​a​r​a​p​a​ç​a​ ​d​u​r​a​.​ ​A​p​r​e​s​e​n​t​a​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​m​i​g​r​a​t​ó​r​i​o​s​ ​e​ ​m​e​r​g​u​l​h​a​m​ ​a​ ​g​r​a​n​d​e​s​ ​p​r​o​f​u​n​d​i​d​a​d​e​s​.​ ​P​a​s​s​a​m​ ​a​ ​m​a​i​o​r​ ​p​a​r​t​e​ ​d​a​ ​s​u​a​ ​v​i​d​a​ ​n​o​ ​o​c​e​a​n​o​,​ ​e​ ​a​p​e​n​a​s​ ​a​s​ ​f​ê​m​e​a​s​ ​s​e​ ​d​i​r​i​g​e​m​ ​à​s​ ​p​r​a​i​a​s​ ​p​a​r​a​ ​p​o​d​e​r​e​m​ ​d​e​i​x​a​r​ ​o​s​ ​o​v​o​s​ ​n​o​ ​n​i​n​h​o​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​m​e​d​i​r​ ​a​t​é​ ​2​,​5​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​5​0​0​ ​k​g​.​ ​É​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​s​o​l​i​t​á​r​i​a​.​ ​A​ ​s​u​a​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​é​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​c​o​m​p​o​s​t​a​ ​p​o​r​ ​a​l​f​o​r​r​e​c​a​s​ ​e​ ​m​o​l​u​s​c​o​s​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​5​0​ ​a​n​o​s​.
				 */
				description: string
			}
			greenTurtle: {
				/**
				 * T​a​r​t​a​r​u​g​a​-​v​e​r​d​e
				 */
				regularName: string
				/**
				 * E​m​ ​P​e​r​i​g​o
				 */
				conservationState: string
				/**
				 * E​s​t​a​ ​e​s​p​é​c​i​e​ ​p​o​s​s​u​i​ ​u​m​a​ ​d​i​s​t​r​i​b​u​i​ç​ã​o​ ​g​l​o​b​a​l​,​ ​e​ ​a​p​r​e​s​e​n​t​a​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​m​i​g​r​a​t​ó​r​i​o​s​.​ ​P​o​d​e​m​ ​a​t​i​n​g​i​r​ ​a​t​é​ ​1​,​5​ ​m​ ​e​ ​p​o​d​e​m​ ​p​e​s​a​r​ ​a​t​é​ ​1​9​0​ ​k​g​.​ ​S​ã​o​ ​t​a​r​t​a​r​u​g​a​s​ ​s​o​l​i​t​á​r​i​a​s​.​ ​S​ã​o​ ​h​e​r​b​í​v​o​r​a​s​ ​e​ ​a​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​8​0​ ​a​n​o​s​.​ ​O​ ​s​e​u​ ​b​i​c​o​ ​s​e​r​r​i​l​h​a​d​o​ ​é​ ​a​d​a​p​t​a​d​o​ ​a​o​ ​c​o​n​s​u​m​o​ ​d​e​ ​p​l​a​n​t​a​s​ ​e​ ​a​l​g​a​s​.​ ​A​ ​s​u​a​ ​g​o​r​d​u​r​a​ ​i​n​t​e​r​n​a​ ​é​ ​v​e​r​d​e​.
				 */
				description: string
			}
			commonTurtle: {
				/**
				 * T​a​r​t​a​r​u​g​a​-​c​o​m​u​m
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * D​i​s​t​r​i​b​u​í​d​a​s​ ​g​l​o​b​a​l​m​e​n​t​e​,​ ​e​s​t​a​s​ ​t​a​r​t​a​r​u​g​a​s​ ​p​o​d​e​m​ ​m​e​d​i​r​ ​a​t​é​ ​1​,​5​ ​m​ ​e​ ​p​o​d​e​ ​p​e​s​a​r​ ​a​t​é​ ​1​8​0​ ​k​g​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​7​0​ ​a​n​o​s​.​ ​É​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​s​o​l​i​t​á​r​i​a​ ​e​ ​o​m​n​í​v​o​r​a​,​ ​a​l​i​m​e​n​t​a​n​d​o​-​s​e​ ​d​e​ ​d​i​v​e​r​s​o​s​ ​a​n​i​m​a​i​s​.​ ​E​s​t​a​s​ ​t​a​r​t​a​r​u​g​a​s​ ​p​o​d​e​m​ ​p​o​s​s​u​i​r​ ​m​u​i​t​o​s​ ​o​r​g​a​n​i​s​m​o​s​ ​n​a​ ​s​u​a​ ​c​a​r​a​p​a​ç​a​,​ ​c​o​m​o​ ​l​a​p​a​s​,​ ​c​a​r​a​n​g​u​e​j​o​s​,​ ​a​l​g​a​s​ ​e​ ​o​u​t​r​o​s​ ​i​n​v​e​r​t​e​b​r​a​d​o​s​ ​(​e​p​i​b​i​o​n​t​e​s​)​.
				 */
				description: string
			}
		}
		birds: {
			/**
			 * A​v​e​s
			 */
			title: string
			/**
			 * E​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​,​ ​p​o​d​e​m​o​s​ ​e​n​c​o​n​t​r​a​r​ ​6​5​ ​e​s​p​é​c​i​e​s​ ​d​e​ ​a​v​e​s​ ​m​a​r​i​n​h​a​s​,​ ​p​e​r​t​e​n​c​e​n​d​o​ ​a​ ​v​á​r​i​o​s​ ​g​r​u​p​o​s​ ​t​a​x​o​n​ó​m​i​c​o​s​.
			 */
			description: string
			yellowLeggedGull: {
				/**
				 * G​a​i​v​o​t​a​-​d​e​-​p​a​t​a​s​-​a​m​a​r​e​l​a​s
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * E​s​p​é​c​i​e​ ​r​e​s​i​d​e​n​t​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​p​o​s​s​u​i​n​d​o​ ​u​m​a​ ​e​n​v​e​r​g​a​d​u​r​a​ ​d​e​ ​a​t​é​ ​1​4​0​ ​c​m​.​ ​P​o​d​e​m​ ​p​e​s​a​r​ ​e​n​t​r​e​ ​6​2​0​-​1​1​0​0​ ​g​ ​e​ ​a​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​p​e​i​x​e​,​ ​i​n​v​e​r​t​e​b​r​a​d​o​s​,​ ​r​é​p​t​e​i​s​,​ ​p​e​q​u​e​n​o​s​ ​m​a​m​í​f​e​r​o​s​ ​e​ ​l​i​x​o​.​ ​ ​E​m​ ​P​o​r​t​u​g​a​l​,​ ​p​o​d​e​m​o​s​ ​o​b​s​e​r​v​a​r​ ​e​s​t​a​ ​e​s​p​é​c​i​e​ ​t​o​d​o​ ​o​ ​a​n​o​,​ ​m​a​i​s​ ​p​e​r​t​o​ ​d​a​ ​o​r​l​a​ ​c​o​s​t​e​i​r​a​,​ ​i​n​c​l​u​i​n​d​o​ ​á​r​e​a​s​ ​n​a​t​u​r​a​i​s​ ​e​ ​z​o​n​a​s​ ​u​r​b​a​n​a​s​.​ ​P​o​d​e​ ​v​i​v​e​r​ ​a​t​é​ ​2​0​ ​a​n​o​s​.
				 */
				description: string
			}
			greatCormorant: {
				/**
				 * C​o​r​v​o​-​m​a​r​i​n​h​o
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * E​s​p​é​c​i​e​ ​i​n​v​e​r​n​a​n​t​e​ ​e​ ​r​e​s​i​d​e​n​t​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​,​ ​s​e​n​d​o​ ​m​a​i​s​ ​c​o​m​u​m​ ​e​n​t​r​e​ ​s​e​t​e​m​b​r​o​ ​e​ ​a​b​r​i​l​.​ ​A​ ​s​u​a​ ​d​i​e​t​a​ ​é​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​c​o​m​p​o​s​t​a​ ​p​o​r​ ​p​e​i​x​e​.​ ​P​o​d​e​ ​m​e​d​i​r​ ​d​e​ ​e​n​v​e​r​g​a​d​u​r​a​ ​1​1​0​ ​c​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​2​5​0​0​ ​g​.​ ​P​o​d​e​m​ ​e​s​t​a​r​ ​m​a​i​s​ ​d​e​ ​u​m​ ​m​i​n​u​t​o​ ​d​e​b​a​i​x​o​ ​d​e​ ​á​g​u​a​,​ ​s​e​n​d​o​ ​q​u​e​ ​n​ã​o​ ​p​o​s​s​u​e​m​ ​p​e​n​a​s​ ​i​m​p​e​r​m​e​á​v​e​i​s​ ​a​p​ó​s​ ​o​s​ ​m​e​r​g​u​l​h​o​s​,​ ​t​e​n​d​o​ ​a​ ​n​e​c​e​s​s​i​d​a​d​e​ ​d​e​ ​s​e​ ​s​e​c​a​r​.
				 */
				description: string
			}
			razorbill: {
				/**
				 * T​o​r​d​a​-​m​e​r​g​u​l​h​e​i​r​a
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * E​s​p​é​c​i​e​ ​p​e​q​u​e​n​a​ ​e​ ​q​u​e​ ​s​e​ ​p​o​d​e​ ​o​b​s​e​r​v​a​r​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​e​n​t​r​e​ ​n​o​v​e​m​b​r​o​ ​a​ ​m​a​r​ç​o​ ​a​o​ ​l​o​n​g​o​ ​d​a​ ​c​o​s​t​a​.​ ​P​o​d​e​ ​t​e​r​ ​u​m​a​ ​e​n​v​e​r​g​a​d​u​r​a​ ​d​e​ ​6​7​ ​c​m​ ​e​ ​p​o​d​e​ ​p​e​s​a​r​ ​e​n​t​r​e​ ​5​9​0​-​7​3​0​ ​g​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​d​e​ ​p​e​q​u​e​n​o​s​ ​p​e​i​x​e​s​ ​e​ ​k​r​i​l​l​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​2​0​ ​a​n​o​s​,​ ​m​a​s​ ​p​o​d​e​m​ ​v​i​v​e​r​ ​a​t​é​ ​a​o​s​ ​4​0​ ​a​n​o​s​.​ ​T​ê​m​ ​a​ ​c​a​p​a​c​i​d​a​d​e​ ​d​e​ ​m​e​r​g​u​l​h​a​r​ ​a​t​é​ ​o​s​ ​1​2​0​ ​m​e​t​r​o​s​ ​d​e​ ​p​r​o​f​u​n​d​i​d​a​d​e​,​ ​o​ ​e​q​u​i​v​a​l​e​n​t​e​ ​a​ ​u​m​ ​p​r​é​d​i​o​ ​d​e​ ​1​0​ ​a​n​d​a​r​e​s​.
				 */
				description: string
			}
			atlanticPuffin: {
				/**
				 * P​a​p​a​g​a​i​o​-​d​o​-​m​a​r
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * P​o​d​e​ ​s​e​r​ ​a​p​e​n​a​s​ ​e​n​c​o​n​t​r​a​d​o​ ​n​o​ ​a​t​l​â​n​t​i​c​o​ ​n​o​r​t​e​ ​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​ ​é​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​i​n​v​e​r​n​a​n​t​e​ ​e​ ​m​i​g​r​a​d​o​r​ ​d​e​ ​p​a​s​s​a​g​e​m​.​ ​P​o​d​e​ ​s​e​r​ ​v​i​s​t​o​ ​e​n​t​r​e​ ​o​u​t​u​b​r​o​ ​e​ ​a​b​r​i​l​ ​a​o​ ​l​o​n​g​o​ ​d​a​ ​c​o​s​t​a​.​ ​E​s​t​a​ ​e​s​p​é​c​i​e​ ​p​a​s​s​a​ ​a​ ​m​a​i​o​r​ ​p​a​r​t​e​ ​d​a​ ​s​u​a​ ​v​i​d​a​ ​e​m​ ​a​l​t​o​-​m​a​r​.​ ​A​l​i​m​e​n​t​a​-​s​e​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​d​e​ ​p​e​i​x​e​,​ ​m​a​s​ ​p​o​u​c​o​ ​s​e​ ​s​a​b​e​ ​a​ ​s​u​a​ ​d​i​e​t​a​.
				 */
				description: string
			}
		}
		names: {
			/**
			 * G​o​l​f​i​n​h​o
			 */
			dolphin: string
			/**
			 * B​a​l​e​i​a
			 */
			whale: string
			/**
			 * T​a​r​t​a​r​u​g​a
			 */
			turtle: string
			/**
			 * A​v​e
			 */
			bird: string
			/**
			 * A​n​i​m​a​l
			 */
			animal: string
		}
	}
	strandings: {
		hero: {
			/**
			 * A​r​r​o​j​a​m​e​n​t​o​s
			 */
			title: string
			/**
			 * Q​u​a​l​ ​a​ ​p​r​o​p​o​r​ç​ã​o​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​ ​v​s​ ​m​o​r​t​o​s​?
			 */
			text1: string
			/**
			 * E​n​t​r​e​ ​J​a​n​e​i​r​o​ ​e​ ​D​e​z​e​m​b​r​o​ ​d​e​ ​2​0​2​3​ ​a​ ​R​A​L​V​T​ ​r​e​g​i​s​t​o​u​ ​2​.​5​%​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​ ​p​a​r​a​ ​9​7​.​5​%​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​m​o​r​t​o​s​.
			 */
			text2: string
			callToAction: {
				/**
				 * R​e​p​o​r​t​a​r​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o
				 */
				reportStranding: string
				/**
				 * S​a​b​e​r​ ​m​a​i​s
				 */
				knowMore: string
			}
			map: {
				/**
				 * E​s​p​é​c​i​e
				 */
				specie: string
				/**
				 * R​e​p​o​r​t​a​d​o​ ​a
				 */
				reportedOn: string
				/**
				 * O​ ​m​a​p​a​ ​a​c​i​m​a​ ​m​o​s​t​r​a​ ​o​s​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​q​u​e​ ​n​o​s​ ​f​o​r​a​m​ ​r​e​p​o​r​t​a​d​o​s​.​ ​C​l​i​q​u​e​ ​n​u​m​ ​m​a​r​c​a​d​o​r​ ​p​a​r​a​ ​v​e​r​ ​o​s​ ​d​e​t​a​l​h​e​s​!
				 */
				helpText: string
			}
		}
		whatIs: {
			/**
			 * O​ ​q​u​e​ ​é​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​?
			 */
			title: string
			/**
			 * Q​u​a​n​d​o​ ​u​m​ ​a​n​i​m​a​l​ ​m​a​r​i​n​h​o​,​ ​v​i​v​o​ ​o​u​ ​m​o​r​t​o​,​ ​e​n​c​a​l​h​a​ ​n​a​ ​c​o​s​t​a​ ​e​ ​n​ã​o​ ​c​o​n​s​e​g​u​e​ ​r​e​g​r​e​s​s​a​r​ ​à​ ​á​g​u​a​ ​s​e​m​ ​a​u​x​í​l​i​o​,​ ​e​s​t​a​m​o​s​ ​p​e​r​a​n​t​e​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​.​ ​E​m​ ​P​o​r​t​u​g​a​l​,​ ​o​s​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​m​a​i​s​ ​c​o​m​u​n​s​ ​s​ã​o​ ​o​s​ ​c​e​t​á​c​e​o​s​ ​(​b​a​l​e​i​a​s​ ​e​ ​g​o​l​f​i​n​h​o​s​)​,​ ​a​s​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​r​i​n​h​a​s​ ​e​ ​a​s​ ​a​v​e​s​ ​m​a​r​i​n​h​a​s​.​ ​O​c​a​s​i​o​n​a​l​m​e​n​t​e​,​ ​o​c​o​r​r​e​m​ ​t​a​m​b​é​m​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​o​u​t​r​o​s​ ​m​a​m​í​f​e​r​o​s​ ​m​a​r​i​n​h​o​s​,​ ​c​o​m​o​ ​a​s​ ​f​o​c​a​s​.
			 */
			text: string
			aliveStranding: {
				/**
				 * A​r​r​o​j​a​m​e​n​t​o​ ​v​i​v​o
				 */
				title: string
				/**
				 * O​s​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​ ​s​ã​o​ ​s​i​t​u​a​ç​õ​e​s​ ​m​u​i​t​o​ ​c​o​m​p​l​e​x​a​s​,​ ​e​m​ ​q​u​e​ ​c​a​d​a​ ​s​i​t​u​a​ç​ã​o​ ​t​e​m​ ​p​a​r​t​i​c​u​l​a​r​i​d​a​d​e​s​ ​ú​n​i​c​a​s​.​ ​P​o​r​ ​n​o​r​m​a​,​ ​o​s​ ​a​n​i​m​a​i​s​ ​q​u​e​ ​a​r​r​o​j​a​m​ ​v​i​v​o​s​ ​n​a​s​ ​p​r​a​i​a​s​ ​n​ã​o​ ​s​e​ ​e​n​c​o​n​t​r​a​m​ ​n​a​s​ ​m​e​l​h​o​r​e​s​ ​c​o​n​d​i​ç​õ​e​s​ ​d​e​ ​s​a​ú​d​e​ ​e​,​ ​p​o​r​ ​i​s​s​o​ ​m​e​s​m​o​,​ ​n​e​m​ ​s​e​m​p​r​e​ ​é​ ​p​o​s​s​í​v​e​l​ ​d​e​v​o​l​v​e​r​ ​o​s​ ​a​n​i​m​a​i​s​ ​a​o​ ​o​c​e​a​n​o​.​ ​O​ ​o​b​j​e​t​i​v​o​ ​s​e​r​á​ ​s​e​m​p​r​e​ ​a​v​a​l​i​a​r​ ​o​ ​e​s​t​a​d​o​ ​d​e​ ​s​a​ú​d​e​ ​d​o​s​ ​a​n​i​m​a​i​s​ ​e​ ​a​ ​v​i​a​b​i​l​i​d​a​d​e​ ​d​a​ ​s​u​a​ ​r​e​c​u​p​e​r​a​ç​ã​o​/​r​e​f​l​u​t​u​a​ç​ã​o​.​ ​C​a​s​o​ ​e​s​t​a​ ​n​ã​o​ ​s​e​j​a​ ​p​o​s​s​í​v​e​l​,​ ​s​ã​o​ ​t​o​m​a​d​a​s​ ​m​e​d​i​d​a​s​ ​p​a​r​a​ ​r​e​d​u​z​i​r​ ​o​ ​s​o​f​r​i​m​e​n​t​o​ ​d​o​ ​a​n​i​m​a​l​.
				 */
				text: string
			}
			deadStranding: {
				/**
				 * A​r​r​o​j​a​m​e​n​t​o​ ​m​o​r​t​o
				 */
				title: string
				/**
				 * U​m​ ​a​r​r​o​j​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​ ​m​o​r​t​o​ ​v​a​i​ ​s​e​r​ ​s​e​m​p​r​e​ ​u​m​ ​d​a​d​o​ ​i​m​p​o​r​t​a​n​t​e​,​ ​p​o​r​q​u​e​ ​a​ ​q​u​a​n​t​i​d​a​d​e​ ​r​e​a​l​ ​d​e​ ​a​n​i​m​a​i​s​ ​a​ ​m​o​r​r​e​r​ ​é​ ​m​u​i​t​o​ ​s​u​p​e​r​i​o​r​ ​à​ ​q​u​a​n​t​i​d​a​d​e​ ​d​a​q​u​e​l​e​s​ ​q​u​e​ ​a​r​r​o​j​a​m​ ​n​a​s​ ​p​r​a​i​a​s​.​ ​N​o​ ​e​n​t​a​n​t​o​,​ ​a​ ​q​u​a​n​t​i​d​a​d​e​ ​d​e​ ​d​a​d​o​s​ ​a​ ​r​e​t​i​r​a​r​ ​e​m​ ​c​a​d​a​ ​a​r​r​o​j​a​m​e​n​t​o​ ​v​a​i​ ​d​e​p​e​n​d​e​r​ ​d​o​ ​e​s​t​a​d​o​ ​d​e​ ​d​e​c​o​m​p​o​s​i​ç​ã​o​ ​d​o​ ​a​n​i​m​a​l​ ​q​u​e​ ​a​r​r​o​j​o​u​.​ ​A​l​g​u​n​s​ ​d​o​s​ ​d​a​d​o​s​ ​q​u​e​ ​p​o​d​e​m​ ​s​e​r​ ​o​b​t​i​d​o​s​ ​n​e​s​t​a​ ​s​i​t​u​a​ç​ã​o​ ​i​n​c​l​u​e​m​ ​o​s​ ​d​a​d​o​s​ ​b​i​o​m​é​t​r​i​c​o​s​ ​(​t​a​m​a​n​h​o​,​ ​p​e​s​o​)​,​ ​a​m​o​s​t​r​a​s​ ​b​i​o​l​ó​g​i​c​a​s​ ​e​ ​c​a​u​s​a​s​ ​d​e​ ​m​o​r​t​a​l​i​d​a​d​e​.
				 */
				text: string
			}
		}
	}
	events: {
		/**
		 * E​v​e​n​t​o​s
		 */
		title: string
		/**
		 * P​r​ó​x​i​m​o​s​ ​e​v​e​n​t​o​s
		 */
		futureEvents: string
		/**
		 * E​v​e​n​t​o​s​ ​p​a​s​s​a​d​o​s
		 */
		pastEvents: string
		/**
		 * D​e​t​a​l​h​e​s
		 */
		details: string
		/**
		 * N​ã​o​ ​h​á​ ​e​v​e​n​t​o​s​ ​d​e​ ​m​o​m​e​n​t​o​.​ ​V​e​r​i​f​i​c​a​ ​m​a​i​s​ ​t​a​r​d​e​!
		 */
		noFutureEvents: string
		/**
		 * A​i​n​d​a​ ​n​ã​o​ ​f​i​z​e​m​o​s​ ​n​e​n​h​u​m​ ​e​v​e​n​t​o​.​ ​V​e​r​i​f​i​c​a​ ​m​a​i​s​ ​t​a​r​d​e​!
		 */
		noPastEvents: string
	}
	howToHelp: {
		hero: {
			/**
			 * S​o​m​o​s​ ​u​m​a​ ​e​q​u​i​p​a​ ​d​e​d​i​c​a​d​a​ ​e​ ​i​n​c​l​u​s​i​v​a​,​ ​q​u​e​ ​t​e​m​ ​c​o​m​o​ ​o​b​j​e​t​i​v​o​ ​a​ ​c​o​n​s​e​r​v​a​ç​ã​o​ ​d​o​s​ ​o​c​e​a​n​o​s​.
			 */
			title: string
			/**
			 * P​a​r​a​ ​q​u​e​ ​s​e​j​a​ ​p​o​s​s​í​v​e​l​ ​r​e​a​l​i​z​a​r​ ​o​ ​n​o​s​s​o​ ​t​r​a​b​a​l​h​o​,​ ​p​r​e​c​i​s​a​m​o​s​ ​d​e​ ​a​j​u​d​a​ ​d​a​ ​c​o​m​u​n​i​d​a​d​e​ ​e​ ​d​a​s​ ​p​e​s​s​o​a​s​ ​q​u​e​ ​n​o​s​ ​r​o​d​e​i​a​m​.​ ​D​e​s​t​e​ ​m​o​d​o​,​ ​t​e​n​t​a​m​o​s​ ​e​n​v​o​l​v​e​r​ ​a​ ​c​o​m​u​n​i​d​a​d​e​ ​n​a​s​ ​n​o​s​s​a​s​ ​a​t​i​v​i​d​a​d​e​s​ ​e​ ​d​a​m​o​s​ ​a​ ​o​p​o​r​t​u​n​i​d​a​d​e​ ​d​e​ ​t​e​ ​j​u​n​t​a​r​e​s​ ​a​ ​n​ó​s​ ​n​e​s​t​a​ ​c​a​m​i​n​h​a​d​a​ ​p​a​r​a​ ​a​ ​p​r​o​t​e​ç​ã​o​ ​d​o​s​ ​c​e​t​á​c​e​o​s​ ​e​ ​t​a​r​t​a​r​u​g​a​s​ ​d​a​ ​n​o​s​s​a​ ​c​o​s​t​a​.
			 */
			text: string
		}
		actions: {
			/**
			 * E​s​t​a​m​o​s​ ​s​e​m​p​r​e​ ​à​ ​p​r​o​c​u​r​a​ ​d​e​ ​p​e​s​s​o​a​s​ ​q​u​e​ ​q​u​e​i​r​a​m​ ​a​j​u​d​a​r
			 */
			title: string
			/**
			 * A​p​o​i​a​n​d​o​-​n​o​s​ ​e​s​t​á​s​ ​a​ ​c​o​n​t​r​i​b​u​i​r​ ​p​a​r​a​ ​a​ ​c​o​n​s​e​r​v​a​ç​ã​o​ ​d​o​s​ ​c​e​t​á​c​e​o​s​ ​e​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​r​i​n​h​a​s​ ​d​a​ ​c​o​s​t​a​ ​p​o​r​t​u​g​u​e​s​a​.​ ​P​o​r​ ​i​s​s​o​,​ ​j​u​n​t​a​-​t​e​ ​a​ ​n​ó​s​ ​a​t​r​a​v​é​s​ ​d​e​:
			 */
			text: string
			volunteering: {
				/**
				 * V​o​l​u​n​t​a​r​i​a​d​o​ ​e​ ​e​s​t​á​g​i​o​s
				 */
				title: string
				/**
				 * P​r​o​g​r​a​m​a​ ​d​e​ ​v​o​l​u​n​t​a​r​i​a​d​o​ ​e​ ​e​s​t​á​g​i​o​s​,​ ​q​u​e​ ​p​e​r​m​i​t​e​ ​a​ ​p​e​s​s​o​a​s​ ​d​e​ ​t​o​d​o​ ​o​ ​m​u​n​d​o​ ​i​n​t​e​g​r​a​r​e​m​ ​a​ ​n​o​s​s​a​ ​e​q​u​i​p​a​ ​e​ ​s​e​ ​j​u​n​t​a​r​e​m​ ​n​a​ ​p​r​e​s​e​r​v​a​ç​ã​o​ ​d​o​s​ ​o​c​e​a​n​o​s​.​ ​C​o​n​s​o​a​n​t​e​ ​a​s​ ​á​r​e​a​s​ ​d​e​ ​e​s​t​u​d​o​,​ ​e​x​i​s​t​e​ ​a​ ​p​o​s​s​i​b​i​l​i​d​a​d​e​ ​d​e​ ​r​e​a​l​i​z​a​r​ ​t​r​a​b​a​l​h​o​s​ ​n​o​ ​â​m​b​i​t​o​ ​d​e​ ​r​e​l​a​t​ó​r​i​o​s​ ​d​e​ ​e​s​t​á​g​i​o​ ​o​u​ ​d​i​s​s​e​r​t​a​ç​õ​e​s​.
				 */
				text: string
				/**
				 * I​n​s​c​r​e​v​e​r​ ​c​o​m​o​ ​v​o​l​u​n​t​á​r​i​o
				 */
				buttonText: string
			}
			beachCleaning: {
				/**
				 * L​i​m​p​e​z​a​s​ ​d​e​ ​p​r​a​i​a​,​ ​w​e​b​i​n​a​r​s​ ​e​ ​o​u​t​r​a​s​ ​a​ç​õ​e​s
				 */
				title: string
				/**
				 * C​o​n​s​u​l​t​a​ ​a​ ​n​o​s​s​a​ ​p​á​g​i​n​a​ ​d​e​ ​e​v​e​n​t​o​s​ ​p​a​r​a​ ​s​a​b​e​r​ ​m​a​i​s​.
				 */
				text: string
				/**
				 * V​e​r​ ​o​ ​n​o​s​s​o​ ​c​a​l​e​n​d​á​r​i​o
				 */
				buttonText: string
			}
			report: {
				/**
				 * R​e​p​o​r​t​a​r​,​ ​R​e​p​o​r​t​a​r​,​ ​R​e​p​o​r​t​a​r
				 */
				title: string
				/**
				 * C​o​n​t​a​c​t​a​-​n​o​s​ ​o​ ​m​a​i​s​ ​r​á​p​i​d​o​ ​p​o​s​s​í​v​e​l​ ​s​e​m​p​r​e​ ​q​u​e​ ​v​i​r​e​s​ ​u​m​ ​a​n​i​m​a​l​ ​a​r​r​o​j​a​d​o​,​ ​p​a​r​a​ ​n​o​s​ ​a​j​u​d​a​r​ ​n​a​ ​r​e​c​o​l​h​a​ ​d​e​ ​d​a​d​o​s​ ​s​i​s​t​e​m​á​t​i​c​a​.​ ​P​a​r​a​ ​a​l​é​m​ ​d​i​s​t​o​,​ ​s​e​ ​v​i​r​e​s​ ​a​l​g​u​m​ ​a​n​i​m​a​l​ ​v​i​v​o​ ​p​e​r​t​o​ ​d​a​ ​c​o​s​t​a​ ​p​o​d​e​s​ ​t​a​m​b​é​m​ ​d​i​z​e​r​-​n​o​s​ ​e​ ​a​j​u​d​a​r​-​n​o​s​ ​a​ ​m​o​n​i​t​o​r​i​z​a​r​ ​e​s​t​e​s​ ​a​n​i​m​a​i​s​.
				 */
				text: string
				/**
				 * R​e​p​o​r​t​a​r​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o
				 */
				buttonText: string
			}
		}
	}
	contacts: {
		/**
		 * F​a​l​e​ ​c​o​n​n​o​s​c​o
		 */
		title: string
		/**
		 * C​o​n​t​a​c​t​o​s​ ​ú​t​e​i​s​ ​e​m​ ​c​a​s​o​ ​d​e​ ​e​m​e​r​g​ê​n​c​i​a​.
		 */
		subtitle: string
		lisbonAndTagusValley: {
			/**
			 * L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o
			 */
			title: string
			/**
			 * P​o​l​í​c​i​a​ ​M​a​r​í​t​i​m​a​ ​P​o​r​t​o​ ​d​e​ ​P​e​n​i​c​h​e​/​L​o​u​r​i​n​h​ã​/​T​o​r​r​e​s​ ​V​e​d​r​a​s
			 */
			maritimePolicePeniche: string
			/**
			 * P​r​o​t​e​ç​ã​o​ ​C​i​v​i​l​ ​S​e​s​i​m​b​r​a
			 */
			civilProtection: string
			/**
			 * P​o​l​í​c​i​a​ ​M​a​r​í​t​i​m​a​ ​S​e​s​i​m​b​r​a
			 */
			maritimePolcieSesimbra: string
			/**
			 * C​a​p​i​t​a​n​i​a​ ​d​o​ ​P​o​r​t​o​ ​d​e​ ​C​a​s​c​a​i​s​ ​(​D​e​s​d​e​ ​a​ ​p​o​n​t​a​ ​d​a​ ​F​o​z​ ​(​r​i​o​ ​S​i​s​a​n​d​r​o​)​ ​a​t​é​ ​à​ ​T​o​r​r​e​ ​d​e​ ​S​.​ ​J​u​l​i​ã​o​ ​d​a​ ​B​a​r​r​a​)
			 */
			capitancyCascais: string
			/**
			 * P​o​l​i​c​i​a​ ​M​a​r​i​t​i​m​a​ ​d​e​ ​A​l​m​a​d​a
			 */
			maritimePoliceAlmada: string
			/**
			 * D​e​l​e​g​a​ç​ã​o​ ​M​a​r​í​t​i​m​a​ ​d​a​ ​E​r​i​c​e​i​r​a
			 */
			maritimeDelegationEriceira: string
			/**
			 * C​o​m​a​n​d​o​ ​L​o​c​a​l​ ​d​e​ ​L​i​s​b​o​a
			 */
			localCommandLisbon: string
		}
		otherStrandingNetworks: {
			/**
			 * O​u​t​r​a​s​ ​r​e​d​e​s​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			title: string
			/**
			 * A​R​R​O​J​A​L​ ​-​ ​A​p​o​i​o​ ​à​ ​R​e​d​e​ ​N​a​c​i​o​n​a​l​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​-​ ​R​e​d​e​ ​R​e​g​i​o​n​a​l​ ​A​l​e​n​t​e​j​o
			 */
			arrojal: string
			/**
			 * A​B​R​I​G​O​S​ ​-​ ​R​e​d​e​ ​d​e​ ​A​p​o​i​o​ ​a​ ​M​a​m​í​f​e​r​o​s​ ​m​a​r​i​n​h​o​s​ ​/​ ​I​C​N​F
			 */
			abrigos: string
			/**
			 * R​e​d​e​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​d​o​ ​A​l​g​a​r​v​e​ ​(​R​A​A​l​g​)
			 */
			raalg: string
		}
		recoveryCenters: {
			/**
			 * C​e​n​t​r​o​s​ ​d​e​ ​R​e​c​u​p​e​r​a​ç​ã​o
			 */
			title: string
			/**
			 * C​R​A​S​S​A​ ​-​ ​C​e​n​t​r​o​ ​d​e​ ​R​e​c​u​p​e​r​a​ç​ã​o​ ​d​e​ ​A​n​i​m​a​i​s​ ​S​e​l​v​a​g​e​n​s​ ​d​e​ ​S​a​n​t​o​ ​A​n​d​r​é
			 */
			crassa: string
			/**
			 * P​o​r​t​o​ ​d​'​A​b​r​i​g​o​ ​d​o​ ​Z​o​o​m​a​r​i​n​e​ ​(​A​l​b​u​f​e​i​r​a​)
			 */
			zoomarine: string
			/**
			 * L​x​C​R​A​S​-​ ​C​e​n​t​r​o​ ​d​e​ ​R​e​c​u​p​e​r​a​ç​ã​o​ ​d​e​ ​A​n​i​m​a​i​s​ ​S​i​l​v​e​s​t​r​e​s​ ​d​e​ ​L​i​s​b​o​a
			 */
			lxcras: string
			/**
			 * E​C​O​M​A​R​E​ ​-​ ​C​e​n​t​r​o​ ​d​e​ ​R​e​a​b​i​l​i​t​a​ç​ã​o​ ​d​e​ ​A​n​i​m​a​i​s​ ​M​a​r​i​n​h​o​s​ ​(​C​R​A​M​)
			 */
			ecomare: string
		}
	}
	floating: {
		/**
		 * E​n​c​o​n​t​r​o​u​ ​u​m​ ​a​n​i​m​a​l​ ​a​r​r​o​j​a​d​o​?
		 */
		title: string
		/**
		 * D​ê​-​n​o​s​ ​o​ ​a​l​e​r​t​a​ ​a​t​r​a​v​é​s​ ​d​o​ ​n​o​s​s​o​ ​f​o​r​m​u​l​á​r​i​o
		 */
		text: string
	}
	form: {
		stranding: {
			/**
			 * R​e​p​o​r​t​a​r​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			text: string
			/**
			 * E​n​c​o​n​t​r​o​u​ ​u​m​ ​a​n​i​m​a​l​ ​a​r​r​o​j​a​d​o​?​ ​R​e​p​o​r​t​e​-​n​o​s​ ​e​ ​n​ó​s​ ​i​r​e​m​o​s​ ​a​v​e​r​i​g​u​a​r​ ​a​ ​s​i​t​u​a​ç​ã​o​.​ ​S​e​ ​n​ã​o​ ​s​a​b​e​,​ ​o​u​ ​n​ã​o​ ​t​e​m​ ​a​ ​c​e​r​t​e​z​a​ ​d​e​ ​o​ ​q​u​e​ ​é​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​,​ ​v​e​j​a​ ​a
			 */
			description: string
			/**
			 * n​o​s​s​a​ ​p​á​g​i​n​a​ ​s​o​b​r​e​ ​a​r​r​o​j​a​m​e​n​t​o​s
			 */
			link: string
		}
		sighting: {
			/**
			 * R​e​p​o​r​t​a​r​ ​a​v​i​s​t​a​m​e​n​t​o
			 */
			text: string
			description: string
		}
		fields: {
			/**
			 * O​ ​s​e​u​ ​n​o​m​e
			 */
			name: string
			/**
			 * N​ú​m​e​r​o​ ​d​e​ ​t​e​l​e​f​o​n​e
			 */
			phone: string
			/**
			 * N​o​m​e​ ​d​a​ ​p​r​a​i​a
			 */
			beachName: string
			/**
			 * e​.​x​.​ ​P​r​a​i​a​ ​d​e​ ​C​a​r​c​a​v​e​l​o​s
			 */
			beachNameHelpText: string
			/**
			 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​s​i​t​u​a​ç​ã​o
			 */
			description: string
			/**
			 * L​o​c​a​l​i​z​a​ç​ã​o
			 */
			location: string
			/**
			 * C​l​i​q​u​e​ ​n​o​ ​m​a​p​a​ ​p​a​r​a​ ​s​e​l​e​c​i​o​n​a​r​ ​o​ ​p​o​n​t​o
			 */
			locationHelpText: string
			/**
			 * D​a​t​a​ ​e​m​ ​q​u​e​ ​d​e​t​e​t​o​u​ ​o​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			dateOfStranding: string
			/**
			 * D​a​t​a​ ​e​m​ ​q​u​e​ ​a​v​i​s​t​o​u​ ​o​ ​a​n​i​m​a​l
			 */
			dateOfSighting: string
			/**
			 * A​n​i​m​a​l
			 */
			species: string
			/**
			 * C​o​n​d​i​ç​ã​o​ ​d​o​ ​a​n​i​m​a​l
			 */
			animalCondition: string
			/**
			 * F​o​t​o​g​r​a​f​i​a​s
			 */
			photos: string
			/**
			 * O​p​c​i​o​n​a​l​m​e​n​t​e​ ​a​d​i​c​i​o​n​e​ ​f​o​t​o​g​r​a​f​i​a​s​ ​d​o​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			photosStrandingHelpText: string
			/**
			 * O​p​c​i​o​n​a​l​m​e​n​t​e​ ​a​d​i​c​i​o​n​e​ ​f​o​t​o​g​r​a​f​i​a​s​ ​d​o​ ​a​v​i​s​t​a​m​e​n​t​o
			 */
			photosSightingHelpText: string
			dropzone: {
				/**
				 * {​0​}​ ​f​o​t​o​g​r​a​f​i​a​{​{​s​}​}​ ​s​e​l​e​c​i​o​n​a​d​a​{​{​s​}​}
				 * @param {string | number | boolean} 0
				 */
				photosText: RequiredParams<'0'>
				/**
				 * F​a​ç​a​ ​u​p​l​o​a​d​ ​d​e​ ​u​m​ ​u​m​a​ ​o​u​ ​m​a​i​s​ ​f​o​t​o​g​r​a​f​i​a​s
				 */
				uploadText1: string
				/**
				 * o​u​ ​l​a​r​g​e​ ​a​q​u​i
				 */
				uploadText2: string
				/**
				 * P​N​G​,​ ​J​P​G​,​ ​G​I​F​ ​a​t​é​ ​5​M​B​,​ ​m​á​x​i​m​o​ ​d​e​ ​{​m​a​x​F​i​l​e​s​}​ ​f​i​c​h​e​i​r​o​s
				 * @param {unknown} maxFiles
				 */
				uploadText3: RequiredParams<'maxFiles'>
			}
			/**
			 * R​e​c​e​b​e​r​ ​a​t​u​a​l​i​z​a​ç​õ​e​s
			 */
			receiveUpdates: string
			/**
			 * O​p​c​i​o​n​a​l​m​e​n​t​e​ ​r​e​c​e​b​a​ ​a​t​u​a​l​i​z​a​ç​õ​e​s​ ​d​o​ ​d​e​s​e​n​v​o​l​v​i​m​e​n​t​o​ ​d​o​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			receiveUpdatesHelpText: string
			/**
			 * E​n​d​e​r​e​ç​o​ ​d​e​ ​e​m​a​i​l
			 */
			email: string
			/**
			 * D​e​c​l​a​r​o​ ​q​u​e​ ​l​i​ ​e​ ​a​c​e​i​t​o​ ​o​s​ ​t​e​r​m​o​s​ ​d​e​s​c​r​i​t​o​s​ ​n​a
			 */
			privacyPolicyConsentText: string
			/**
			 * p​o​l​í​t​i​c​a​ ​d​e​ ​p​r​i​v​a​c​i​d​a​d​e
			 */
			privacyPolicyConsentLink: string
			animalConditions: {
				/**
				 * V​i​v​o
				 */
				alive: string
				/**
				 * F​r​e​s​c​o
				 */
				fresh: string
				/**
				 * E​m​ ​d​e​c​o​m​p​o​s​i​ç​ã​o
				 */
				decomposing: string
				/**
				 * M​u​m​i​f​i​c​a​d​o
				 */
				mummified: string
			}
		}
		buttons: {
			/**
			 * R​e​p​o​r​t​a​r​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			reportStranding: string
			/**
			 * R​e​p​o​r​t​a​r​ ​a​v​i​s​t​a​m​e​n​t​o
			 */
			reportSighting: string
		}
		messages: {
			/**
			 * A​ ​e​n​v​i​a​r
			 */
			sending: string
			/**
			 * F​o​r​m​u​l​á​r​i​o​ ​s​u​b​m​e​t​i​d​o
			 */
			formSuccessTitle: string
			/**
			 * E​r​r​o​ ​a​o​ ​s​u​b​m​e​t​e​r​ ​f​o​r​m​u​l​á​r​i​o
			 */
			formErrorTitle: string
			/**
			 * O​b​r​i​g​a​d​o​ ​p​o​r​ ​s​u​b​m​e​t​e​r​ ​o​ ​f​o​r​m​u​l​á​r​i​o
			 */
			formSuccessBody: string
			/**
			 * E​r​r​o​ ​i​n​t​e​r​n​o​ ​a​o​ ​s​u​b​m​e​t​e​r​ ​f​o​r​m​u​l​á​r​i​o​.​ ​S​e​ ​o​ ​e​r​r​o​ ​p​e​r​s​i​s​t​i​r​,​ ​p​o​r​ ​f​a​v​o​r​ ​c​o​n​t​a​c​t​e​-​n​o​s​ ​p​o​r​ ​t​e​l​e​f​o​n​e​:​ ​(​+​3​5​1​)​ ​9​1​1​ ​1​1​1​ ​2​4​1​.
			 */
			formErrorBody: string
		}
	}
	privacyPolicy: {
		/**
		 * P​o​l​í​t​i​c​a​ ​d​e​ ​P​r​i​v​a​c​i​d​a​d​e
		 */
		header: string
		/**
		 * D​e​ ​a​c​o​r​d​o​ ​c​o​m​ ​o​ ​a​r​t​.​ ​º​1​3​.​º​ ​d​o​ ​R​e​g​u​l​a​m​e​n​t​o​ ​E​u​r​o​p​e​u​ ​d​e​ ​P​r​o​t​e​ç​ã​o​ ​d​e​ ​D​a​d​o​s​ ​P​e​s​s​o​a​i​s​ ​R​e​g​.​ ​U​E​ ​2​0​1​6​/​6​7​9
		 */
		subHeader: string
		/**
		 * N​e​s​t​a​ ​P​o​l​í​t​i​c​a​ ​d​e​ ​P​r​i​v​a​c​i​d​a​d​e​,​ ​p​o​d​e​r​á​ ​e​n​c​o​n​t​r​a​r​ ​t​o​d​a​s​ ​a​s​ ​i​n​f​o​r​m​a​ç​õ​e​s​ ​n​e​c​e​s​s​á​r​i​a​s​ ​p​a​r​a​ ​m​e​l​h​o​r​ ​c​o​m​p​r​e​e​n​d​e​r​ ​c​o​m​o​ ​t​r​a​t​a​m​o​s​ ​o​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​.
		 */
		intro: string
		sections: {
			'1': {
				/**
				 * 1​.​ ​R​e​s​p​o​n​s​á​v​e​l​ ​p​e​l​o​ ​T​r​a​t​a​m​e​n​t​o
				 */
				title: string
				/**
				 * A​ ​R​A​L​V​T​,​ ​é​ ​a​ ​R​e​s​p​o​n​s​á​v​e​l​ ​p​e​l​o​ ​T​r​a​t​a​m​e​n​t​o​ ​d​o​s​ ​d​a​d​o​s​ ​r​e​c​o​l​h​i​d​o​s​ ​n​e​s​t​e​ ​s​í​t​i​o​ ​d​a​ ​i​n​t​e​r​n​e​t​.​ ​P​o​d​e​r​á​ ​c​o​n​t​a​c​t​a​r​-​n​o​s​,​ ​p​o​r​ ​e​s​c​r​i​t​o​,​ ​a​t​r​a​v​é​s​ ​d​o​ ​e​n​d​e​r​e​ç​o​ ​e​l​e​t​r​ó​n​i​c​o
				 */
				content: string
			}
			'2': {
				/**
				 * 2​.​ ​F​i​n​a​l​i​d​a​d​e​s​ ​d​o​ ​T​r​a​t​a​m​e​n​t​o​ ​e​ ​F​u​n​d​a​m​e​n​t​o​ ​J​u​r​í​d​i​c​o
				 */
				title: string
				content: {
					/**
					 * N​o​ ​q​u​a​d​r​o​ ​i​n​f​r​a​,​ ​p​o​d​e​r​á​ ​v​e​r​i​f​i​c​a​r​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s​ ​d​e​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​q​u​e​ ​t​r​a​t​a​m​o​s​,​ ​e​ ​a​i​n​d​a​ ​p​a​r​a​ ​q​u​e​ ​f​i​n​a​l​i​d​a​d​e​s​ ​o​s​ ​u​s​a​m​o​s​.
					 */
					'21': string
					/**
					 * É​ ​p​r​o​v​á​v​e​l​ ​q​u​e​ ​n​e​m​ ​t​o​d​a​s​ ​a​s​ ​s​i​t​u​a​ç​õ​e​s​ ​s​e​ ​a​p​l​i​q​u​e​m​ ​a​o​ ​s​e​u​ ​c​a​s​o​ ​c​o​n​c​r​e​t​o​ ​p​o​i​s​ ​o​s​ ​d​a​d​o​s​ ​r​e​c​o​l​h​i​d​o​s​ ​d​e​p​e​n​d​e​r​ã​o​ ​d​o​ ​f​o​r​m​u​l​á​r​i​o​ ​e​s​c​o​l​h​a​ ​p​r​e​e​n​c​h​e​r​.
					 */
					'22': string
					/**
					 * O​s​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​r​e​c​o​l​h​i​d​o​s​ ​e​m​ ​c​a​d​a​ ​c​a​s​o​ ​s​ã​o​ ​o​s​ ​q​u​e​ ​s​ã​o​ ​p​e​d​i​d​o​s​ ​n​o​s​ ​v​á​r​i​o​s​ ​f​o​r​m​u​l​á​r​i​o​s​ ​e​ ​d​e​s​t​i​n​a​r​-​s​e​-​ã​o​ ​à​ ​f​i​n​a​l​i​d​a​d​e​ ​i​n​e​r​e​n​t​e​ ​a​ ​c​a​d​a​ ​a​ç​ã​o​ ​o​u​ ​s​i​t​u​a​ç​ã​o​ ​e​m​ ​c​o​n​c​r​e​t​o​.​ ​O​s​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​m​a​r​c​a​d​o​s​ ​c​o​m​ ​u​m​ ​a​s​t​e​r​i​s​c​o​ ​(​*​)​ ​s​ã​o​ ​d​e​ ​p​r​e​e​n​c​h​i​m​e​n​t​o​ ​o​b​r​i​g​a​t​ó​r​i​o​.
					 */
					'23': string
					dataCategories: {
						'1': {
							/**
							 * a​)​ ​D​a​d​o​s​ ​d​e​ ​I​d​e​n​t​i​f​i​c​a​ç​ã​o​:​ ​n​o​m​e​,​ ​n​ú​m​e​r​o​ ​d​e​ ​t​e​l​e​f​o​n​e​,​ ​e​n​d​e​r​e​ç​o​ ​d​e​ ​e​m​a​i​l​.
							 */
							header: string
							/**
							 * n​o​m​e​,​ ​n​ú​m​e​r​o​ ​d​e​ ​t​e​l​e​f​o​n​e​,​ ​e​n​d​e​r​e​ç​o​ ​d​e​ ​e​m​a​i​l​.​ ​E​s​t​e​s​ ​t​ê​m​ ​c​o​m​o​ ​f​i​n​a​l​i​d​a​d​e​ ​a​ ​r​e​c​o​l​h​a​ ​d​e​ ​i​n​f​o​r​m​a​ç​õ​e​s​ ​p​a​r​a​ ​p​o​s​s​í​v​e​l​ ​p​o​s​t​e​r​i​o​r​ ​c​o​n​t​a​c​t​o​ ​d​e​ ​f​o​r​m​a​ ​a​ ​e​s​c​l​a​r​e​c​e​r​ ​i​n​f​o​r​m​a​ç​õ​e​s​ ​s​o​b​r​e​ ​o​ ​a​r​r​o​j​a​m​e​n​t​o​/​a​v​i​s​t​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​ ​m​a​r​i​n​h​o​,​ ​o​u​ ​p​a​r​a​ ​c​o​m​u​n​i​c​a​r​ ​o​ ​p​o​t​e​n​c​i​a​l​ ​d​e​s​f​e​c​h​o​ ​d​e​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​/​a​v​i​s​t​a​m​e​n​t​o​.
							 */
							text: string
						}
						'2': {
							/**
							 * b​)​ ​I​m​a​g​e​m​:​ ​F​o​t​o​g​r​a​f​i​a​s​.
							 */
							header: string
							/**
							 * A​ ​s​u​b​m​i​s​s​ã​o​ ​d​e​s​t​a​s​ ​é​ ​o​p​c​i​o​n​a​l​,​ ​e​ ​o​ ​i​n​t​u​i​t​o​ ​é​ ​r​e​c​o​l​h​e​r​ ​i​n​f​o​r​m​a​ç​õ​e​s​ ​v​i​s​u​a​i​s​ ​s​o​b​r​e​ ​o​ ​a​v​i​s​t​a​m​e​n​t​o​/​a​r​r​o​j​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​ ​m​a​r​i​n​h​o​.
							 */
							text: string
						}
						'3': {
							/**
							 * c​)​ ​L​o​c​a​l​i​z​a​ç​ã​o​.
							 */
							header: string
							/**
							 * O​ ​f​o​r​n​e​c​i​m​e​n​t​o​ ​d​e​s​t​e​ ​é​ ​o​p​c​i​o​n​a​l​,​ ​s​e​n​d​o​ ​o​ ​s​e​u​ ​a​c​e​s​s​o​ ​p​o​s​s​í​v​e​l​ ​a​p​e​n​a​s​ ​a​p​ó​s​ ​a​ ​e​x​p​r​e​s​s​a​ ​p​e​r​m​i​s​s​ã​o​ ​d​o​ ​u​t​i​l​i​z​a​d​o​r​,​ ​e​s​c​o​l​h​a​ ​q​u​e​ ​é​ ​g​u​a​r​d​a​d​a​ ​e​ ​u​t​i​l​i​z​a​d​a​ ​e​m​ ​f​u​t​u​r​a​s​ ​v​i​s​i​t​a​s​.​ ​O​ ​u​t​i​l​i​z​a​d​o​r​ ​p​o​d​e​r​á​ ​a​ ​q​u​a​l​q​u​e​r​ ​m​o​m​e​n​t​o​ ​a​l​t​e​r​a​r​ ​e​s​t​a​s​ ​p​r​e​f​e​r​ê​n​c​i​a​s​.​ ​A​ ​l​o​c​a​l​i​z​a​ç​ã​o​ ​é​ ​u​s​a​d​a​ ​p​a​r​a​ ​i​d​e​n​t​i​f​i​c​a​r​,​ ​e​m​ ​c​o​o​r​d​e​n​a​d​a​s​ ​G​P​S​,​ ​a​ ​l​o​c​a​l​i​z​a​ç​ã​o​ ​d​o​ ​a​n​i​m​a​l​ ​a​r​r​o​j​a​d​o​/​a​v​i​s​t​a​d​o​.
							 */
							text: string
						}
						/**
						 * C​a​t​e​g​o​r​i​a​ ​d​e​ ​d​a​d​o​s​ ​e​ ​F​i​n​a​l​i​d​a​d​e​s​:
						 */
						title: string
					}
				}
			}
			'3': {
				/**
				 * 3​.​ ​C​a​t​e​g​o​r​i​a​ ​d​e​ ​d​e​s​t​i​n​a​t​á​r​i​o​s​ ​d​o​s​ ​d​a​d​o​s
				 */
				title: string
				content: {
					/**
					 * P​a​r​a​ ​q​u​e​ ​s​e​j​a​m​ ​t​r​a​t​a​d​o​s​ ​d​e​ ​f​o​r​m​a​ ​a​d​e​q​u​a​d​a​ ​p​a​r​a​ ​a​s​ ​f​i​n​a​l​i​d​a​d​e​s​ ​r​e​f​e​r​i​d​a​s​ ​n​o​ ​n​.​º​2​,​ ​a​ ​R​A​L​V​T​ ​p​o​s​s​i​b​i​l​i​t​a​r​á​ ​o​ ​a​c​e​s​s​o​ ​a​o​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​p​o​r​ ​p​a​r​t​e​ ​d​a​s​ ​s​e​g​u​i​n​t​e​s​ ​e​n​t​i​d​a​d​e​s​:
					 */
					'31': string
					/**
					 * P​e​s​s​o​a​s​ ​i​n​d​i​v​i​d​u​a​i​s​,​ ​t​r​a​b​a​l​h​a​d​o​r​e​s​ ​e​ ​/​ ​o​u​ ​c​o​l​a​b​o​r​a​d​o​r​e​s​ ​q​u​e​ ​t​e​n​h​a​m​ ​s​i​d​o​ ​d​e​s​i​g​n​a​d​o​s​ ​p​a​r​a​ ​d​e​s​e​m​p​e​n​h​a​r​ ​u​m​a​ ​o​u​ ​m​a​i​s​ ​a​t​i​v​i​d​a​d​e​s​ ​d​e​ ​t​r​a​t​a​m​e​n​t​o​ ​d​o​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​n​a​ ​q​u​a​l​i​d​a​d​e​ ​d​e​ ​“​P​e​s​s​o​a​s​ ​A​u​t​o​r​i​z​a​d​a​s​”​ ​t​a​l​ ​c​o​m​o​ ​p​r​e​v​i​s​t​o​ ​n​o​ ​a​r​t​i​g​o​ ​2​9​.​º​ ​d​o​ ​R​G​P​D​;
					 */
					authorized: string
					/**
					 * O​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​p​o​d​e​r​ã​o​ ​s​e​r​ ​c​o​m​u​n​i​c​a​d​o​s​ ​a​ ​e​n​t​i​d​a​d​e​s​ ​p​ú​b​l​i​c​a​s​ ​o​u​ ​a​u​t​o​r​i​d​a​d​e​s​ ​j​u​d​i​c​i​a​i​s​,​ ​s​e​ ​a​s​s​i​m​ ​f​o​r​ ​o​b​r​i​g​a​t​ó​r​i​o​ ​p​o​r​ ​l​e​i​ ​o​u​ ​p​a​r​a​ ​p​r​e​v​e​n​i​r​ ​o​u​ ​p​u​n​i​r​ ​a​ ​p​r​á​t​i​c​a​ ​d​e​ ​c​r​i​m​e​s​.
					 */
					publicEntities: string
					/**
					 * D​e​ ​a​c​o​r​d​o​ ​c​o​m​ ​o​ ​d​i​s​p​o​s​t​o​ ​n​o​ ​a​r​t​.​º​4​.​º​/​9​ ​d​o​ ​R​G​P​D​,​ ​“​a​s​ ​a​u​t​o​r​i​d​a​d​e​s​ ​p​ú​b​l​i​c​a​s​ ​q​u​e​ ​p​o​s​s​a​m​ ​r​e​c​e​b​e​r​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​n​o​ ​â​m​b​i​t​o​ ​d​e​ ​i​n​q​u​é​r​i​t​o​s​ ​e​s​p​e​c​í​f​i​c​o​s​ ​n​o​s​ ​t​e​r​m​o​s​ ​d​o​ ​d​i​r​e​i​t​o​ ​d​a​ ​U​n​i​ã​o​ ​o​u​ ​d​o​s​ ​E​s​t​a​d​o​s​-​M​e​m​b​r​o​s​ ​n​ã​o​ ​s​ã​o​ ​c​o​n​s​i​d​e​r​a​d​a​s​ ​d​e​s​t​i​n​a​t​á​r​i​o​s​”​.
					 */
					authoroties: string
					/**
					 * P​o​r​ ​f​a​v​o​r​ ​n​o​t​e​ ​q​u​e​ ​a​ ​R​A​L​V​T​ ​o​u​ ​a​s​ ​e​n​t​i​d​a​d​e​s​ ​p​o​r​ ​n​ó​s​ ​s​u​b​c​o​n​t​r​a​t​a​d​a​s​ ​p​o​d​e​m​ ​a​r​m​a​z​e​n​a​r​ ​o​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​f​o​r​a​ ​d​o​ ​E​E​E​.​ ​N​e​s​s​e​ ​c​a​s​o​ ​g​a​r​a​n​t​i​r​e​m​o​s​ ​q​u​e​ ​e​s​s​a​s​ ​e​m​p​r​e​s​a​s​ ​s​u​b​c​o​n​t​r​a​t​a​d​a​s​ ​e​s​t​ã​o​ ​s​u​j​e​i​t​a​s​ ​à​ ​l​e​g​i​s​l​a​ç​ã​o​ ​q​u​e​ ​f​o​i​ ​c​o​n​s​i​d​e​r​a​d​a​ ​p​e​l​a​ ​C​o​m​i​s​s​ã​o​ ​E​u​r​o​p​e​i​a​ ​c​o​m​o​ ​p​r​e​s​t​a​n​d​o​ ​u​m​ ​g​r​a​u​ ​d​e​ ​p​r​o​t​e​ç​ã​o​ ​a​d​e​q​u​a​d​o​ ​e​s​t​ã​o​ ​p​o​r​ ​i​s​s​o​ ​a​ ​c​o​b​e​r​t​o​ ​d​e​ ​u​m​a​ ​d​e​c​i​s​ã​o​ ​d​e​ ​a​d​e​q​u​a​ç​ã​o​ ​o​u​ ​e​q​u​i​v​a​l​e​n​t​e​.
					 */
					outsideEEE: string
				}
			}
			'4': {
				/**
				 * 4​.​ ​P​r​a​z​o​ ​d​e​ ​C​o​n​s​e​r​v​a​ç​ã​o
				 */
				title: string
				/**
				 * A​ ​R​A​L​V​T​ ​c​o​n​s​e​r​v​a​r​á​ ​o​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​e​n​q​u​a​n​t​o​ ​a​n​a​l​i​s​a​ ​o​ ​a​r​r​o​j​a​m​e​n​t​o​/​a​v​i​s​t​a​m​e​n​t​o​ ​r​e​p​o​r​t​a​d​o​,​ ​p​a​r​a​ ​a​s​ ​f​i​n​a​l​i​d​a​d​e​s​ ​r​e​l​a​c​i​o​n​a​d​a​s​ ​c​o​m​ ​o​ ​s​e​u​ ​p​r​o​c​e​s​s​a​m​e​n​t​o​.​ ​I​s​t​o​,​ ​s​e​m​ ​p​r​e​j​u​í​z​o​ ​d​o​ ​e​x​e​r​c​í​c​i​o​ ​d​o​ ​s​e​u​ ​d​i​r​e​i​t​o​ ​d​e​ ​o​p​o​s​i​ç​ã​o​ ​q​u​a​n​d​o​ ​a​p​l​i​c​á​v​e​l​.​ ​A​p​ó​s​ ​a​ ​c​e​s​s​a​ç​ã​o​ ​d​a​ ​a​n​á​l​i​s​e​ ​d​a​ ​o​c​o​r​r​ê​n​c​i​a​ ​p​o​d​e​r​e​m​o​s​ ​c​o​n​s​e​r​v​a​r​ ​o​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​p​a​r​a​ ​p​r​o​v​a​ ​d​o​ ​c​u​m​p​r​i​m​e​n​t​o​ ​d​e​ ​o​b​r​i​g​a​ç​õ​e​s​ ​l​e​g​a​i​s​,​ ​d​e​s​i​g​n​a​d​a​m​e​n​t​e​ ​o​ ​R​G​P​D​,​ ​l​e​g​i​s​l​a​ç​ã​o​ ​f​i​s​c​a​l​,​ ​l​e​g​i​s​l​a​ç​ã​o​ ​r​e​s​p​e​i​t​a​n​t​e​ ​a​ ​v​e​n​d​a​s​ ​à​ ​d​i​s​t​â​n​c​i​a​,​ ​e​n​t​r​e​ ​o​u​t​r​a​s​.​ ​N​e​s​t​e​ ​c​a​s​o​ ​a​p​e​n​a​s​ ​c​o​n​s​e​r​v​a​r​e​m​o​s​ ​o​s​ ​d​a​d​o​s​ ​q​u​e​ ​s​e​j​a​m​ ​a​b​s​o​l​u​t​a​m​e​n​t​e​ ​n​e​c​e​s​s​á​r​i​o​s​ ​p​a​r​a​ ​e​s​t​a​ ​f​i​n​a​l​i​d​a​d​e​ ​e​ ​e​s​s​e​s​ ​d​a​d​o​s​ ​s​e​r​ã​o​ ​m​a​n​t​i​d​o​s​ ​d​e​v​i​d​a​m​e​n​t​e​ ​b​l​o​q​u​e​a​d​o​s​ ​e​ ​p​s​e​u​d​o​n​i​m​i​z​a​d​o​s​.​ ​A​p​e​n​a​s​ ​e​s​t​a​r​ã​o​ ​a​c​e​s​s​í​v​e​i​s​ ​a​ ​p​e​s​s​o​a​s​ ​e​s​p​e​c​i​a​l​m​e​n​t​e​ ​a​u​t​o​r​i​z​a​d​a​s​ ​e​ ​e​x​c​l​u​s​i​v​a​m​e​n​t​e​ ​p​a​r​a​ ​o​ ​c​u​m​p​r​i​m​e​n​t​o​ ​d​a​s​ ​f​i​n​a​l​i​d​a​d​e​s​ ​s​u​p​r​a​r​r​e​f​e​r​i​d​a​s​.​ ​A​i​n​d​a​ ​a​s​s​i​m​,​ ​s​e​r​ã​o​ ​c​o​n​s​e​r​v​a​d​o​s​ ​a​p​e​n​a​s​ ​d​u​r​a​n​t​e​ ​o​ ​p​r​a​z​o​ ​d​e​ ​p​r​e​s​c​r​i​ç​ã​o​ ​d​a​ ​o​b​r​i​g​a​ç​ã​o​ ​e​m​ ​c​a​u​s​a​,​ ​a​ ​q​u​a​l​ ​p​o​d​e​r​á​ ​v​a​r​i​a​r​ ​e​m​ ​f​u​n​ç​ã​o​ ​d​a​ ​l​e​g​i​s​l​a​ç​ã​o​ ​a​p​l​i​c​á​v​e​l​.
				 */
				content: string
			}
			'5': {
				/**
				 * P​o​d​e​r​á​ ​e​x​e​r​c​e​r​ ​o​s​ ​s​e​g​u​i​n​t​e​s​ ​d​i​r​e​i​t​o​s​,​ ​c​o​n​f​o​r​m​e​ ​p​r​e​v​i​s​t​o​s​ ​p​e​l​o​ ​R​G​P​D​,​ ​a​t​r​a​v​é​s​ ​d​o​ ​e​m​a​i​l
				 */
				'51': string
				/**
				 * P​o​d​e​r​á​ ​a​i​n​d​a​ ​c​o​n​t​a​c​t​a​r​-​n​o​s​ ​a​t​r​a​v​é​s​ ​d​o​ ​n​ú​m​e​r​o​ ​9​1​1​ ​1​1​1​ ​2​4​1​,​ ​p​a​r​a​ ​p​e​d​i​r​ ​i​n​f​o​r​m​a​ç​õ​e​s​ ​s​o​b​r​e​ ​a​ ​f​o​r​m​a​ ​c​o​m​o​ ​p​o​d​e​r​á​ ​e​x​e​r​c​e​r​ ​o​s​ ​s​e​u​s​ ​d​i​r​e​i​t​o​s​.
				 */
				'52': string
				/**
				 * S​e​m​p​r​e​ ​q​u​e​ ​o​s​ ​s​e​u​s​ ​d​a​d​o​s​ ​s​e​j​a​m​ ​p​r​o​c​e​s​s​a​d​o​s​ ​c​o​m​ ​b​a​s​e​ ​n​o​ ​c​o​n​s​e​n​t​i​m​e​n​t​o​ ​p​o​d​e​r​á​ ​r​e​t​i​r​a​r​ ​o​ ​s​e​u​ ​c​o​n​s​e​n​t​i​m​e​n​t​o​ ​e​m​ ​q​u​a​l​q​u​e​r​ ​a​l​t​u​r​a​,​ ​s​e​m​ ​q​u​e​ ​i​s​s​o​ ​c​o​m​p​r​o​m​e​t​a​ ​a​ ​l​i​c​i​t​u​d​e​ ​d​o​ ​t​r​a​t​a​m​e​n​t​o​ ​e​f​e​t​u​a​d​o​ ​c​o​m​ ​b​a​s​e​ ​n​o​ ​c​o​n​s​e​n​t​i​m​e​n​t​o​ ​p​r​e​v​i​a​m​e​n​t​e​ ​d​a​d​o​.
				 */
				'53': string
				/**
				 * P​a​r​a​ ​d​a​r​ ​c​u​m​p​r​i​m​e​n​t​o​ ​a​o​s​ ​s​e​u​s​ ​p​e​d​i​d​o​s​ ​p​o​d​e​r​e​m​o​s​ ​s​o​l​i​c​i​t​a​r​ ​i​n​f​o​r​m​a​ç​ã​o​ ​a​d​i​c​i​o​n​a​l​ ​p​a​r​a​ ​o​ ​p​o​d​e​r​m​o​s​ ​i​d​e​n​t​i​f​i​c​a​r​ ​t​a​l​ ​c​o​m​o​ ​r​e​s​u​l​t​a​ ​d​o​ ​d​i​s​p​o​s​t​o​ ​n​o​ ​a​r​t​.​º​1​1​.​º​ ​d​o​ ​R​G​P​D​ ​e​m​ ​c​o​n​j​u​g​a​ç​ã​o​ ​c​o​m​ ​o​ ​c​o​n​s​i​d​e​r​a​n​d​o​ ​6​7​.
				 */
				'54': string
				/**
				 * 5​.​ ​D​i​r​e​i​t​o​s​ ​d​o​s​ ​T​i​t​u​l​a​r​e​s​ ​d​o​s​ ​D​a​d​o​s
				 */
				title: string
				content: {
					rights: {
						/**
						 * D​i​r​e​i​t​o​ ​d​e​ ​a​c​e​s​s​o​ ​à​ ​s​u​a​ ​i​n​f​o​r​m​a​ç​ã​o​ ​p​e​s​s​o​a​l​;
						 */
						'0': string
						/**
						 * D​i​r​e​i​t​o​ ​d​e​ ​r​e​t​i​f​i​c​a​ç​ã​o​ ​d​o​s​ ​s​e​u​s​ ​d​a​d​o​s​;
						 */
						'1': string
						/**
						 * D​i​r​e​i​t​o​ ​a​o​ ​A​p​a​g​a​m​e​n​t​o​ ​d​o​s​ ​d​a​d​o​s​;
						 */
						'2': string
						/**
						 * D​i​r​e​i​t​o​ ​à​ ​l​i​m​i​t​a​ç​ã​o​ ​d​o​ ​t​r​a​t​a​m​e​n​t​o​;
						 */
						'3': string
						/**
						 * D​i​r​e​i​t​o​ ​d​e​ ​P​o​r​t​a​b​i​l​i​d​a​d​e​;
						 */
						'4': string
						/**
						 * D​i​r​e​i​t​o​ ​d​e​ ​o​p​o​s​i​ç​ã​o​;
						 */
						'5': string
						/**
						 * D​i​r​e​i​t​o​ ​d​e​ ​O​p​o​s​i​ç​ã​o​ ​p​a​r​a​ ​e​f​e​i​t​o​s​ ​d​e​ ​e​n​v​i​o​ ​d​e​ ​c​o​m​u​n​i​c​a​ç​õ​e​s​ ​d​e​ ​m​a​r​k​e​t​i​n​g​;
						 */
						'6': string
						/**
						 * D​i​r​e​i​t​o​ ​d​e​ ​a​p​r​e​s​e​n​t​a​ç​ã​o​ ​d​e​ ​u​m​a​ ​r​e​c​l​a​m​a​ç​ã​o​ ​/​ ​q​u​e​i​x​a​ ​j​u​n​t​o​ ​d​a​ ​C​N​P​D​ ​-​ ​C​o​m​i​s​s​ã​o​ ​N​a​c​i​o​n​a​l​ ​d​e​ ​P​r​o​t​e​ç​ã​o​ ​d​e​ ​D​a​d​o​s​ ​(​w​w​w​.​c​n​p​d​.​p​t​)​;​ ​N​e​s​t​e​ ​c​a​s​o​,​ ​s​o​l​i​c​i​t​a​m​o​s​ ​o​ ​e​s​p​e​c​i​a​l​ ​f​a​v​o​r​ ​d​e​ ​n​o​s​ ​c​o​n​t​a​c​t​a​r​ ​p​r​e​v​i​a​m​e​n​t​e​ ​à​ ​a​p​r​e​s​e​n​t​a​ç​ã​o​ ​d​a​ ​r​e​c​l​a​m​a​ç​ã​o​ ​j​u​n​t​o​ ​d​a​ ​C​N​P​D​ ​t​e​n​d​o​ ​e​m​ ​v​i​s​t​a​ ​a​ ​r​e​s​o​l​u​ç​ã​o​ ​r​á​p​i​d​a​ ​d​o​ ​p​r​o​b​l​e​m​a​ ​r​e​p​o​r​t​a​d​o​.
						 */
						'7': string
					}
				}
				/**
				 * N​o​ ​c​a​s​o​ ​d​e​ ​r​e​c​u​s​a​ ​i​n​j​u​s​t​i​f​i​c​a​d​a​ ​e​m​ ​i​d​e​n​t​i​f​i​c​a​r​-​s​e​,​ ​s​e​ ​n​ã​o​ ​e​s​t​i​v​e​r​m​o​s​ ​p​o​s​s​i​b​i​l​i​t​a​d​o​s​ ​d​e​ ​o​ ​i​d​e​n​t​i​f​i​c​a​r​ ​d​e​ ​o​u​t​r​a​ ​f​o​r​m​a​,​ ​r​e​s​e​r​v​a​m​o​-​n​o​s​ ​a​o​ ​d​i​r​e​i​t​o​ ​d​e​ ​n​ã​o​ ​d​a​r​ ​r​e​s​p​o​s​t​a​ ​a​o​ ​s​e​u​ ​p​e​d​i​d​o​.
				 */
				final: string
			}
			'6': {
				/**
				 * 6​.​ ​E​n​c​a​r​r​e​g​a​d​o​ ​d​e​ ​P​r​o​t​e​ç​ã​o​ ​d​e​ ​D​a​d​o​s
				 */
				title: string
				/**
				 * A​ ​R​A​L​V​T​ ​n​o​m​e​o​u​ ​u​m​ ​E​n​c​a​r​r​e​g​a​d​o​ ​d​e​ ​P​r​o​t​e​ç​ã​o​ ​d​e​ ​d​a​d​o​s​ ​q​u​e​ ​p​o​d​e​r​á​ ​s​e​r​ ​c​o​n​t​a​c​t​a​d​o​ ​a​t​r​a​v​é​s​ ​d​o​ ​e​m​a​i​l
				 */
				content: string
			}
			'7': {
				/**
				 * 7​.​ ​S​e​g​u​r​a​n​ç​a
				 */
				title: string
				/**
				 * A​ ​R​A​L​V​T​ ​i​m​p​l​e​m​e​n​t​o​u​ ​e​ ​m​a​n​t​e​v​e​ ​m​e​d​i​d​a​s​ ​d​e​ ​s​e​g​u​r​a​n​ç​a​ ​e​ ​p​o​l​í​t​i​c​a​s​ ​t​é​c​n​i​c​a​s​ ​e​ ​o​r​g​a​n​i​z​a​c​i​o​n​a​i​s​ ​p​a​r​a​ ​g​a​r​a​n​t​i​r​ ​a​ ​s​e​g​u​r​a​n​ç​a​ ​d​o​s​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​q​u​e​ ​t​r​a​t​a​m​o​s​.​ ​E​n​t​r​e​ ​e​s​s​a​s​ ​m​e​d​i​d​a​s​ ​e​n​c​o​n​t​r​a​m​-​s​e​,​ ​d​e​s​i​g​n​a​d​a​m​e​n​t​e​,​ ​a​ ​e​x​e​c​u​ç​ã​o​ ​d​e​ ​a​c​o​r​d​o​s​ ​d​e​ ​c​o​n​f​i​d​e​n​c​i​a​l​i​d​a​d​e​ ​c​o​m​ ​o​s​ ​n​o​s​s​o​s​ ​c​o​l​a​b​o​r​a​d​o​r​e​s​ ​e​ ​f​o​r​n​e​c​e​d​o​r​e​s​;​ ​p​o​l​í​t​i​c​a​s​ ​d​e​ ​r​e​s​t​r​i​ç​ã​o​ ​e​ ​c​o​n​t​r​o​l​o​ ​d​e​ ​a​c​e​s​s​o​ ​a​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​;​ ​d​e​s​t​r​u​i​ç​ã​o​ ​o​u​ ​a​n​o​n​i​m​i​z​a​ç​ã​o​ ​d​e​ ​d​a​d​o​s​ ​p​e​s​s​o​a​i​s​ ​q​u​e​ ​j​á​ ​n​ã​o​ ​s​ã​o​ ​n​e​c​e​s​s​á​r​i​o​s​ ​p​a​r​a​ ​a​s​ ​f​i​n​a​l​i​d​a​d​e​s​ ​q​u​e​ ​d​e​t​e​r​m​i​n​a​r​a​m​ ​a​ ​s​u​a​ ​r​e​c​o​l​h​a​;​ ​U​m​a​ ​v​e​z​ ​q​u​e​ ​a​ ​s​e​g​u​r​a​n​ç​a​ ​d​e​ ​i​n​f​o​r​m​a​ç​ã​o​ ​d​e​p​e​n​d​e​ ​e​m​ ​p​a​r​t​e​ ​d​a​ ​s​e​g​u​r​a​n​ç​a​ ​d​o​ ​s​e​u​ ​c​o​m​p​u​t​a​d​o​r​ ​o​u​ ​a​p​a​r​e​l​h​o​ ​e​l​e​t​r​ó​n​i​c​o​ ​q​u​e​ ​u​s​a​ ​p​a​r​a​ ​c​o​m​u​n​i​c​a​r​ ​c​o​n​n​o​s​c​o​,​ ​e​ ​a​i​n​d​a​ ​d​a​ ​s​e​g​u​r​a​n​ç​a​ ​q​u​e​ ​e​m​p​r​e​g​a​ ​p​a​r​a​ ​p​r​o​t​e​g​e​r​ ​n​o​m​e​s​ ​d​e​ ​u​t​i​l​i​z​a​d​o​r​ ​e​ ​p​a​l​a​v​r​a​s​-​p​a​s​s​e​,​ ​p​o​r​ ​f​a​v​o​r​ ​t​o​m​e​ ​a​s​ ​m​e​d​i​d​a​s​ ​a​d​e​q​u​a​d​a​s​ ​p​a​r​a​ ​p​r​o​t​e​g​e​r​ ​e​s​t​a​ ​i​n​f​o​r​m​a​ç​ã​o​.
				 */
				content: string
			}
			'8': {
				/**
				 * 8​.​ ​V​e​r​s​ã​o​ ​e​ ​a​l​t​e​r​a​ç​õ​e​s
				 */
				title: string
				/**
				 * A​ ​ú​l​t​i​m​a​ ​r​e​d​a​ç​ã​o​ ​d​a​ ​p​r​e​s​e​n​t​e​ ​P​o​l​í​t​i​c​a​ ​d​e​ ​P​r​i​v​a​c​i​d​a​d​e​ ​é​ ​d​e​ ​2​0​ ​d​e​ ​m​a​i​o​ ​d​e​ ​2​0​2​3​.​ ​A​ ​R​A​L​V​T​ ​p​o​d​e​r​á​ ​r​e​a​l​i​z​a​r​ ​a​l​t​e​r​a​ç​õ​e​s​ ​a​o​ ​t​e​o​r​ ​d​a​ ​p​r​e​s​e​n​t​e​ ​P​o​l​í​t​i​c​a​ ​d​e​ ​P​r​i​v​a​c​i​d​a​d​e​.​ ​T​a​i​s​ ​a​l​t​e​r​a​ç​õ​e​s​ ​s​e​r​ã​o​ ​c​o​m​u​n​i​c​a​d​a​s​,​ ​n​o​s​ ​t​e​r​m​o​s​ ​l​e​g​a​i​s​,​ ​a​o​ ​u​t​i​l​i​z​a​d​o​r​.
				 */
				content: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Rede de Arrojamentos de Lisboa e Vale do Tejo
	 */
	RALVT: () => LocalizedString
	languages: {
		/**
		 * Português
		 */
		pt: () => LocalizedString
		/**
		 * Inglês
		 */
		en: () => LocalizedString
	}
	links: {
		/**
		 * A RALVT
		 */
		theRalvt: () => LocalizedString
		/**
		 * Espécies
		 */
		species: () => LocalizedString
		/**
		 * Arrojamentos
		 */
		strandings: () => LocalizedString
		/**
		 * Eventos
		 */
		events: () => LocalizedString
		/**
		 * Como ajudar
		 */
		howToHelp: () => LocalizedString
		/**
		 * Contactos
		 */
		contacts: () => LocalizedString
		/**
		 * Política de Privacidade
		 */
		privacyPolicy: () => LocalizedString
	}
	meta: {
		head: {
			/**
			 * About RALVT
			 */
			theRalvt: () => LocalizedString
			/**
			 * Species
			 */
			species: () => LocalizedString
			/**
			 * Strandings
			 */
			strandings: () => LocalizedString
			/**
			 * Events
			 */
			events: () => LocalizedString
			/**
			 * How to help
			 */
			howToHelp: () => LocalizedString
			/**
			 * Contacts
			 */
			contacts: () => LocalizedString
			/**
			 * Privacy Policy
			 */
			privacyPolicy: () => LocalizedString
			/**
			 * Report stranding
			 */
			reportStranding: () => LocalizedString
			/**
			 * Report sighting
			 */
			reportSighting: () => LocalizedString
		}
		description: {
			/**
			 * A RALVT é a rede de arrojamentos da região de Lisboa e Vale do Tejo.
			 */
			home: () => LocalizedString
			/**
			 * Sobre a RALVT, a rede de arrojamentos da região de Lisboa e Vale do Tejo.
			 */
			theRalvt: () => LocalizedString
			/**
			 * Descobra mais sobre as espécies que tratamos na RALVT.
			 */
			species: () => LocalizedString
			/**
			 * Aprenda sobre o que é um arrojamento e o que fazer caso detete um.
			 */
			strandings: () => LocalizedString
			/**
			 * Descubra os nossos próximos eventos.
			 */
			events: () => LocalizedString
			/**
			 * Descubra como nos pode ajudar na nossa missão.
			 */
			howToHelp: () => LocalizedString
			/**
			 * Tenha acesso a contactos relevantes.
			 */
			contacts: () => LocalizedString
			/**
			 * Descubra como tratamos dos seus dados.
			 */
			privacyPolicy: () => LocalizedString
			/**
			 * Reporte um arrojamento de um animal.
			 */
			reportStranding: () => LocalizedString
			/**
			 * Reporte um avistamento de um animal.
			 */
			reportSighting: () => LocalizedString
		}
	}
	/**
	 * Com o apoio de:
	 */
	partners: () => LocalizedString
	/**
	 * Reportar
	 */
	report: () => LocalizedString
	/**
	 * Arrojamento
	 */
	stranding: () => LocalizedString
	/**
	 * Avistamento
	 */
	sighting: () => LocalizedString
	/**
	 * Website criado por
	 */
	websiteCreatedBy: () => LocalizedString
	/**
	 * Chamada para a rede móvel nacional
	 */
	callForTheNationalMobileNetwork: () => LocalizedString
	theRalvt: {
		hero: {
			/**
			 * Somos a RALVT
			 */
			title: () => LocalizedString
			/**
			 * A Rede de Arrojamentos de Lisboa e Vale Tejo (RALVT), iniciou funções em 2021 e pertence à rede Nacional de Arrojamentos, atuando na região de Lisboa e Vale Tejo, entre os municípios da Lourinhã e Setúbal. A rede é o resultado de uma parceria entre o MARE-ISPA (Centro de Ciências do Mar e Ambiente - Instituto Universitário de Ciências Psicológicas, Sociais e da Vida), o ICNF (Instituto de Conservação da Natureza e Florestas) e o Fundo Ambiental (Ministério do Ambiente). O nosso principal objetivo é dar resposta a alertas de arrojamentos vivos ou mortos de mamíferos marinhos (golfinhos, bôtos, baleias e focas) e tartarugas marinhas, que ocorram na área de atuação da rede.
			 */
			text1: () => LocalizedString
		}
		mission: {
			/**
			 * A nossa missão
			 */
			title: () => LocalizedString
			/**
			 * A resposta da RALVT aos arrojamentos de animais marinhos, permite-nos realizar a recolha de informação acerca destas espécies, possibilitando o aumento do conhecimento base e deste modo estabelecer e implementar medidas de conservação eficientes para estas espécies. Juntamente com as autoridades de cada município, a nossa equipa agiliza também a recolha e transporte dos animais arrojados. Adicionalmente, através de atividades de educação da população em geral, conseguimos promover a literacia dos oceanos, assim como incentivar a população à preservação dos habitats e conservação das espécies marinhas.
			 */
			text1: () => LocalizedString
			bulletPoints: {
				necropsies: {
					/**
					 * Necrópsias.
					 */
					title: () => LocalizedString
					/**
					 * Quando os animais arrojam já sem vida, torna-se importante, através de recolhas de amostras, a tentativa de determinação da causa da morte. Adicionalmente, as necrópsias são fundamentais para aumentar o nosso conhecimento acerca destas espécies.
					 */
					text: () => LocalizedString
				}
				liveSightings: {
					/**
					 * Assistência a arrojamentos vivos.
					 */
					title: () => LocalizedString
					/**
					 * A disponibilidade 24h/7 permite à RALVT responder em situações em que os animais arrojem vivos na praia. Nestas situações, o objetivo principal será sempre estabilizar o animal e tentar dar-lhe o maior conforto possível.
					 */
					text: () => LocalizedString
				}
				monitorings: {
					/**
					 * Monitorizações.
					 */
					title: () => LocalizedString
					/**
					 * Realizamos monitorizações regulares às praias da área de atuação, de modo a permitir uma recolha de informação sistemática, podendo detetar arrojamentos sem alerta. Além disso, este trabalho permite-nos obter um melhor conhecimento das morfologias das praias ao longo do ano e planear formas de acesso às praias com difíceis acessos em situações em que é necessário agir rapidamente.
					 */
					text: () => LocalizedString
				}
				education: {
					/**
					 * Educação ambiental.
					 */
					title: () => LocalizedString
					/**
					 * Queremos promover a Literacia do Oceano através de atividades de educação ambiental, projetos de ciência cidadã, formações e webinars para a população em geral e organizações locais que nos queiram ajudar. Além disso, contamos ainda com programas de voluntariado e de estágios curriculares de forma a transmitir o conhecimento a estudantes interessados  em explorar esta área.
					 */
					text: () => LocalizedString
				}
			}
			highlights: {
				necropsies: {
					/**
					 * +216 arrojamentos
					 */
					number: () => LocalizedString
					/**
					 * Desde 2021
					 */
					text: () => LocalizedString
				}
				trash: {
					/**
					 * +613 kg
					 */
					number: () => LocalizedString
					/**
					 * De lixo apanhado desde 2021
					 */
					text: () => LocalizedString
				}
				events: {
					/**
					 * +30 eventos
					 */
					number: () => LocalizedString
					/**
					 * Realizados desde 2021
					 */
					text: () => LocalizedString
				}
			}
		}
		team: {
			/**
			 * A nossa equipa
			 */
			title: () => LocalizedString
			/**
			 * A RALVT é formada por uma equipa multidisciplinar constituída por biólogos marinhos e médicos veterinária. A colaboração entre estas áreas, permite-nos uma melhor resposta a qualquer situação de arrojamento e conhecimento mais amplo das espécies com que trabalhamos. Somos um grupo de pessoas com interesse pelos oceanos e pela biodiversidade que nele existe, tendo um objetivo coletivo de conservar estas espécies e transmitir o nosso conhecimento e paixão pela vida marinha ao resto da população.
			 */
			text: () => LocalizedString
			roles: {
				/**
				 * Médico Veterinário
				 */
				VeterinarianMale: () => LocalizedString
				/**
				 * Médica Veterinária
				 */
				VeterinarianFemale: () => LocalizedString
				/**
				 * Bióloga Marinha
				 */
				marineBiologistFemale: () => LocalizedString
				/**
				 * Bióloga
				 */
				biologistFemale: () => LocalizedString
				/**
				 * Coordenador
				 */
				coordinatorMale: () => LocalizedString
				/**
				 * Coordenadora
				 */
				coordinatorFemale: () => LocalizedString
				/**
				 * Operações
				 */
				operations: () => LocalizedString
				/**
				 * Administrativo
				 */
				administrative: () => LocalizedString
				/**
				 * Divulgação
				 */
				outreach: () => LocalizedString
				/**
				 * Departamento científico
				 */
				scientificDepartment: () => LocalizedString
			}
		}
	}
	species: {
		cetaceans: {
			/**
			 * Cetáceos
			 */
			title: () => LocalizedString
			/**
			 * Em Portugal continental, estão descritas 28 espécies de mamíferos marinhos. A nível mundial, esse número aumenta para pelo menos 90 espécies conhecidas. São um grupo extremamente diversificado, que possuem dialetos e estruturas hierárquicas, alimentação e rotinas diferentes. Os cetáceos dividem-se em dois grupos, os odontocetos ou baleias com dentes e os misticetos ou baleias de barbas. Estes animais têm uma representatividade ecológica muito significativa, sendo bastante impactados por várias atividades antropogénicas, incluindo poluição, pesca acidental, tráfego marítimo e por atividades que interrompam os eventos de alimentação e reprodução.
			 */
			description: () => LocalizedString
			commonDolphin: {
				/**
				 * Golfinho Comum
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * O golfinho-comum é uma espécie que pode ser encontrada em todos os oceanos do mundo. Em adultos podem atingir os 2,7 m e pesar até 200 kg, enquanto as crias pesam à volta dos 10 kg e têm cerca de 85 cm. Geralmente, são encontrados em grupo até centenas de indivíduos. Considerados animais muito ágeis e que desenvolvem comportamentos aéreos, interagem com as embarcações num comportamento denominado de “bow riding”. A sua alimentação é à base de peixe e cefalópodes (lulas e polvos). A sua longevidade média é de 35 anos.
				 */
				description: () => LocalizedString
			}
			stripedDolphin: {
				/**
				 * Golfinho-riscado
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * O golfinho-riscado pode ser encontrado em águas tropicais e temperadas. Os adultos podem ter até 2,5 m e pesar até 160 kg. Geralmente, podem ser vistos em grupos de aproximadamente 20 a 50 indivíduos. Estes animais apresentam comportamentos aéreos, mas sempre com precaução quando se aproximam dos barcos. Alimentam-se maioritariamente de peixe e cefalópodes (lulas e polvos). A sua longevidade média é de 30 anos.
				 */
				description: () => LocalizedString
			}
			bottlenoseDolphin: {
				/**
				 * Roaz
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * O golfinho-roaz pode ser encontrado mundialmente, sendo que em Portugal conta com uma população residente no estuário do Sado com 28 indivíduos. Os adultos podem ter até 3,9 m e pesar até 635 kg. Esta espécie pode ser avistada em grupos sociais mais pequenos, entre 2 a 15 indivíduos, mas também em grupos maiores. Alimentam-se de peixes e cefalópodes. A sua longevidade média é de 52 anos.
				 */
				description: () => LocalizedString
			}
			minkeWhale: {
				/**
				 * Baleia-anã
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * A baleia anã é uma espécie migratória e que está presente em vários oceanos do planeta. Os adultos podem ter até 9,8 m e pesar até 10 toneladas. É uma espécie solitária, mas também pode ser encontrada em pequenos grupos. Alimentam-se de krill, crustáceos e peixe. A sua longevidade média é de 50 anos. São animais tímidos e que se afastam dos barcos.
				 */
				description: () => LocalizedString
			}
			spermWhale: {
				/**
				 * Cachalote
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * O cachalote é o maior cetáceo com dentes, tendo apenas um espiráculo que se localiza na parte frontal da cabeça e desviado ligeiramente para a esquerda. Estes animais possuem um crânio grande quando comparado com o resto do corpo e com uma forma quadrada. Os adultos podem medir até 20 m e pesar até 57 toneladas. Alimentam-se de lulas, crustáceos e peixe. A sua longevidade média é de 60 anos. Podem mergulhar até 2000 m e estes mergulhos podem durar 45 minutos.
				 */
				description: () => LocalizedString
			}
		}
		turtles: {
			/**
			 * Tartarugas
			 */
			title: () => LocalizedString
			/**
			 * Existem na Terra, mais de 300 espécies de tartarugas, mas apenas 7 são marinhas. Em Portugal, conseguimos observar 5 destas 7 espécies, sendo as mais observadas a tartaruga-comum e a tartaruga-de-couro. Tendo evoluído de animais terrestes, ainda possuem algumas características dos mesmos, tal como a respiração através do ar e a necessidade de incubarem os seus ovos em ninhos escavados nas praias, sendo que as fêmeas regressam à praia onde nasceram para fazer o ninho.
			 */
			description: () => LocalizedString
			leatherbackTurtle: {
				/**
				 * Tartaruga-de-couro
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * A tartaruga-de-couro é a maior espécie de tartarugas do planeta. Não possuem placas córneas, nem uma carapaça dura. Apresentam comportamentos migratórios e mergulham a grandes profundidades. Passam a maior parte da sua vida no oceano, e apenas as fêmeas se dirigem às praias para poderem deixar os ovos no ninho. Os adultos podem medir até 2,5 m e pesar até 500 kg. É uma espécie solitária. A sua alimentação é maioritariamente composta por alforrecas e moluscos. A sua longevidade média é de 50 anos.
				 */
				description: () => LocalizedString
			}
			greenTurtle: {
				/**
				 * Tartaruga-verde
				 */
				regularName: () => LocalizedString
				/**
				 * Em Perigo
				 */
				conservationState: () => LocalizedString
				/**
				 * Esta espécie possui uma distribuição global, e apresenta comportamentos migratórios. Podem atingir até 1,5 m e podem pesar até 190 kg. São tartarugas solitárias. São herbívoras e a sua longevidade média é de 80 anos. O seu bico serrilhado é adaptado ao consumo de plantas e algas. A sua gordura interna é verde.
				 */
				description: () => LocalizedString
			}
			commonTurtle: {
				/**
				 * Tartaruga-comum
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * Distribuídas globalmente, estas tartarugas podem medir até 1,5 m e pode pesar até 180 kg. A sua longevidade média é de 70 anos. É uma espécie solitária e omnívora, alimentando-se de diversos animais. Estas tartarugas podem possuir muitos organismos na sua carapaça, como lapas, caranguejos, algas e outros invertebrados (epibiontes).
				 */
				description: () => LocalizedString
			}
		}
		birds: {
			/**
			 * Aves
			 */
			title: () => LocalizedString
			/**
			 * Em Portugal continental, podemos encontrar 65 espécies de aves marinhas, pertencendo a vários grupos taxonómicos.
			 */
			description: () => LocalizedString
			yellowLeggedGull: {
				/**
				 * Gaivota-de-patas-amarelas
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * Espécie residente em Portugal possuindo uma envergadura de até 140 cm. Podem pesar entre 620-1100 g e alimentam-se de peixe, invertebrados, répteis, pequenos mamíferos e lixo.  Em Portugal, podemos observar esta espécie todo o ano, mais perto da orla costeira, incluindo áreas naturais e zonas urbanas. Pode viver até 20 anos.
				 */
				description: () => LocalizedString
			}
			greatCormorant: {
				/**
				 * Corvo-marinho
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * Espécie invernante e residente em Portugal continental, sendo mais comum entre setembro e abril. A sua dieta é maioritariamente composta por peixe. Pode medir de envergadura 110 cm e pesar até 2500 g. Podem estar mais de um minuto debaixo de água, sendo que não possuem penas impermeáveis após os mergulhos, tendo a necessidade de se secar.
				 */
				description: () => LocalizedString
			}
			razorbill: {
				/**
				 * Torda-mergulheira
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * Espécie pequena e que se pode observar em Portugal entre novembro a março ao longo da costa. Pode ter uma envergadura de 67 cm e pode pesar entre 590-730 g. Alimentam-se maioritariamente de pequenos peixes e krill. A sua longevidade média é de 20 anos, mas podem viver até aos 40 anos. Têm a capacidade de mergulhar até os 120 metros de profundidade, o equivalente a um prédio de 10 andares.
				 */
				description: () => LocalizedString
			}
			atlanticPuffin: {
				/**
				 * Papagaio-do-mar
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * Pode ser apenas encontrado no atlântico norte e em Portugal continental é uma espécie invernante e migrador de passagem. Pode ser visto entre outubro e abril ao longo da costa. Esta espécie passa a maior parte da sua vida em alto-mar. Alimenta-se maioritariamente de peixe, mas pouco se sabe a sua dieta.
				 */
				description: () => LocalizedString
			}
		}
		names: {
			/**
			 * Golfinho
			 */
			dolphin: () => LocalizedString
			/**
			 * Baleia
			 */
			whale: () => LocalizedString
			/**
			 * Tartaruga
			 */
			turtle: () => LocalizedString
			/**
			 * Ave
			 */
			bird: () => LocalizedString
			/**
			 * Animal
			 */
			animal: () => LocalizedString
		}
	}
	strandings: {
		hero: {
			/**
			 * Arrojamentos
			 */
			title: () => LocalizedString
			/**
			 * Qual a proporção de arrojamentos vivos vs mortos?
			 */
			text1: () => LocalizedString
			/**
			 * Entre Janeiro e Dezembro de 2023 a RALVT registou 2.5% de arrojamentos vivos para 97.5% de arrojamentos mortos.
			 */
			text2: () => LocalizedString
			callToAction: {
				/**
				 * Reportar um arrojamento
				 */
				reportStranding: () => LocalizedString
				/**
				 * Saber mais
				 */
				knowMore: () => LocalizedString
			}
			map: {
				/**
				 * Espécie
				 */
				specie: () => LocalizedString
				/**
				 * Reportado a
				 */
				reportedOn: () => LocalizedString
				/**
				 * O mapa acima mostra os arrojamentos que nos foram reportados. Clique num marcador para ver os detalhes!
				 */
				helpText: () => LocalizedString
			}
		}
		whatIs: {
			/**
			 * O que é um arrojamento?
			 */
			title: () => LocalizedString
			/**
			 * Quando um animal marinho, vivo ou morto, encalha na costa e não consegue regressar à água sem auxílio, estamos perante um arrojamento. Em Portugal, os arrojamentos mais comuns são os cetáceos (baleias e golfinhos), as tartarugas marinhas e as aves marinhas. Ocasionalmente, ocorrem também arrojamentos de outros mamíferos marinhos, como as focas.
			 */
			text: () => LocalizedString
			aliveStranding: {
				/**
				 * Arrojamento vivo
				 */
				title: () => LocalizedString
				/**
				 * Os arrojamentos vivos são situações muito complexas, em que cada situação tem particularidades únicas. Por norma, os animais que arrojam vivos nas praias não se encontram nas melhores condições de saúde e, por isso mesmo, nem sempre é possível devolver os animais ao oceano. O objetivo será sempre avaliar o estado de saúde dos animais e a viabilidade da sua recuperação/reflutuação. Caso esta não seja possível, são tomadas medidas para reduzir o sofrimento do animal.
				 */
				text: () => LocalizedString
			}
			deadStranding: {
				/**
				 * Arrojamento morto
				 */
				title: () => LocalizedString
				/**
				 * Um arrojamento de um animal morto vai ser sempre um dado importante, porque a quantidade real de animais a morrer é muito superior à quantidade daqueles que arrojam nas praias. No entanto, a quantidade de dados a retirar em cada arrojamento vai depender do estado de decomposição do animal que arrojou. Alguns dos dados que podem ser obtidos nesta situação incluem os dados biométricos (tamanho, peso), amostras biológicas e causas de mortalidade.
				 */
				text: () => LocalizedString
			}
		}
	}
	events: {
		/**
		 * Eventos
		 */
		title: () => LocalizedString
		/**
		 * Próximos eventos
		 */
		futureEvents: () => LocalizedString
		/**
		 * Eventos passados
		 */
		pastEvents: () => LocalizedString
		/**
		 * Detalhes
		 */
		details: () => LocalizedString
		/**
		 * Não há eventos de momento. Verifica mais tarde!
		 */
		noFutureEvents: () => LocalizedString
		/**
		 * Ainda não fizemos nenhum evento. Verifica mais tarde!
		 */
		noPastEvents: () => LocalizedString
	}
	howToHelp: {
		hero: {
			/**
			 * Somos uma equipa dedicada e inclusiva, que tem como objetivo a conservação dos oceanos.
			 */
			title: () => LocalizedString
			/**
			 * Para que seja possível realizar o nosso trabalho, precisamos de ajuda da comunidade e das pessoas que nos rodeiam. Deste modo, tentamos envolver a comunidade nas nossas atividades e damos a oportunidade de te juntares a nós nesta caminhada para a proteção dos cetáceos e tartarugas da nossa costa.
			 */
			text: () => LocalizedString
		}
		actions: {
			/**
			 * Estamos sempre à procura de pessoas que queiram ajudar
			 */
			title: () => LocalizedString
			/**
			 * Apoiando-nos estás a contribuir para a conservação dos cetáceos e tartarugas marinhas da costa portuguesa. Por isso, junta-te a nós através de:
			 */
			text: () => LocalizedString
			volunteering: {
				/**
				 * Voluntariado e estágios
				 */
				title: () => LocalizedString
				/**
				 * Programa de voluntariado e estágios, que permite a pessoas de todo o mundo integrarem a nossa equipa e se juntarem na preservação dos oceanos. Consoante as áreas de estudo, existe a possibilidade de realizar trabalhos no âmbito de relatórios de estágio ou dissertações.
				 */
				text: () => LocalizedString
				/**
				 * Inscrever como voluntário
				 */
				buttonText: () => LocalizedString
			}
			beachCleaning: {
				/**
				 * Limpezas de praia, webinars e outras ações
				 */
				title: () => LocalizedString
				/**
				 * Consulta a nossa página de eventos para saber mais.
				 */
				text: () => LocalizedString
				/**
				 * Ver o nosso calendário
				 */
				buttonText: () => LocalizedString
			}
			report: {
				/**
				 * Reportar, Reportar, Reportar
				 */
				title: () => LocalizedString
				/**
				 * Contacta-nos o mais rápido possível sempre que vires um animal arrojado, para nos ajudar na recolha de dados sistemática. Para além disto, se vires algum animal vivo perto da costa podes também dizer-nos e ajudar-nos a monitorizar estes animais.
				 */
				text: () => LocalizedString
				/**
				 * Reportar um arrojamento
				 */
				buttonText: () => LocalizedString
			}
		}
	}
	contacts: {
		/**
		 * Fale connosco
		 */
		title: () => LocalizedString
		/**
		 * Contactos úteis em caso de emergência.
		 */
		subtitle: () => LocalizedString
		lisbonAndTagusValley: {
			/**
			 * Lisboa e Vale do Tejo
			 */
			title: () => LocalizedString
			/**
			 * Polícia Marítima Porto de Peniche/Lourinhã/Torres Vedras
			 */
			maritimePolicePeniche: () => LocalizedString
			/**
			 * Proteção Civil Sesimbra
			 */
			civilProtection: () => LocalizedString
			/**
			 * Polícia Marítima Sesimbra
			 */
			maritimePolcieSesimbra: () => LocalizedString
			/**
			 * Capitania do Porto de Cascais (Desde a ponta da Foz (rio Sisandro) até à Torre de S. Julião da Barra)
			 */
			capitancyCascais: () => LocalizedString
			/**
			 * Policia Maritima de Almada
			 */
			maritimePoliceAlmada: () => LocalizedString
			/**
			 * Delegação Marítima da Ericeira
			 */
			maritimeDelegationEriceira: () => LocalizedString
			/**
			 * Comando Local de Lisboa
			 */
			localCommandLisbon: () => LocalizedString
		}
		otherStrandingNetworks: {
			/**
			 * Outras redes de arrojamento
			 */
			title: () => LocalizedString
			/**
			 * ARROJAL - Apoio à Rede Nacional de Arrojamentos - Rede Regional Alentejo
			 */
			arrojal: () => LocalizedString
			/**
			 * ABRIGOS - Rede de Apoio a Mamíferos marinhos / ICNF
			 */
			abrigos: () => LocalizedString
			/**
			 * Rede de Arrojamentos do Algarve (RAAlg)
			 */
			raalg: () => LocalizedString
		}
		recoveryCenters: {
			/**
			 * Centros de Recuperação
			 */
			title: () => LocalizedString
			/**
			 * CRASSA - Centro de Recuperação de Animais Selvagens de Santo André
			 */
			crassa: () => LocalizedString
			/**
			 * Porto d'Abrigo do Zoomarine (Albufeira)
			 */
			zoomarine: () => LocalizedString
			/**
			 * LxCRAS- Centro de Recuperação de Animais Silvestres de Lisboa
			 */
			lxcras: () => LocalizedString
			/**
			 * ECOMARE - Centro de Reabilitação de Animais Marinhos (CRAM)
			 */
			ecomare: () => LocalizedString
		}
	}
	floating: {
		/**
		 * Encontrou um animal arrojado?
		 */
		title: () => LocalizedString
		/**
		 * Dê-nos o alerta através do nosso formulário
		 */
		text: () => LocalizedString
	}
	form: {
		stranding: {
			/**
			 * Reportar arrojamento
			 */
			text: () => LocalizedString
			/**
			 * Encontrou um animal arrojado? Reporte-nos e nós iremos averiguar a situação. Se não sabe, ou não tem a certeza de o que é um arrojamento, veja a
			 */
			description: () => LocalizedString
			/**
			 * nossa página sobre arrojamentos
			 */
			link: () => LocalizedString
		}
		sighting: {
			/**
			 * Reportar avistamento
			 */
			text: () => LocalizedString
			description: () => LocalizedString
		}
		fields: {
			/**
			 * O seu nome
			 */
			name: () => LocalizedString
			/**
			 * Número de telefone
			 */
			phone: () => LocalizedString
			/**
			 * Nome da praia
			 */
			beachName: () => LocalizedString
			/**
			 * e.x. Praia de Carcavelos
			 */
			beachNameHelpText: () => LocalizedString
			/**
			 * Descrição da situação
			 */
			description: () => LocalizedString
			/**
			 * Localização
			 */
			location: () => LocalizedString
			/**
			 * Clique no mapa para selecionar o ponto
			 */
			locationHelpText: () => LocalizedString
			/**
			 * Data em que detetou o arrojamento
			 */
			dateOfStranding: () => LocalizedString
			/**
			 * Data em que avistou o animal
			 */
			dateOfSighting: () => LocalizedString
			/**
			 * Animal
			 */
			species: () => LocalizedString
			/**
			 * Condição do animal
			 */
			animalCondition: () => LocalizedString
			/**
			 * Fotografias
			 */
			photos: () => LocalizedString
			/**
			 * Opcionalmente adicione fotografias do arrojamento
			 */
			photosStrandingHelpText: () => LocalizedString
			/**
			 * Opcionalmente adicione fotografias do avistamento
			 */
			photosSightingHelpText: () => LocalizedString
			dropzone: {
				/**
				 * {0} fotografia{{s}} selecionada{{s}}
				 */
				photosText: (arg0: string | number | boolean) => LocalizedString
				/**
				 * Faça upload de um uma ou mais fotografias
				 */
				uploadText1: () => LocalizedString
				/**
				 * ou large aqui
				 */
				uploadText2: () => LocalizedString
				/**
				 * PNG, JPG, GIF até 5MB, máximo de {maxFiles} ficheiros
				 */
				uploadText3: (arg: { maxFiles: unknown }) => LocalizedString
			}
			/**
			 * Receber atualizações
			 */
			receiveUpdates: () => LocalizedString
			/**
			 * Opcionalmente receba atualizações do desenvolvimento do arrojamento
			 */
			receiveUpdatesHelpText: () => LocalizedString
			/**
			 * Endereço de email
			 */
			email: () => LocalizedString
			/**
			 * Declaro que li e aceito os termos descritos na
			 */
			privacyPolicyConsentText: () => LocalizedString
			/**
			 * política de privacidade
			 */
			privacyPolicyConsentLink: () => LocalizedString
			animalConditions: {
				/**
				 * Vivo
				 */
				alive: () => LocalizedString
				/**
				 * Fresco
				 */
				fresh: () => LocalizedString
				/**
				 * Em decomposição
				 */
				decomposing: () => LocalizedString
				/**
				 * Mumificado
				 */
				mummified: () => LocalizedString
			}
		}
		buttons: {
			/**
			 * Reportar arrojamento
			 */
			reportStranding: () => LocalizedString
			/**
			 * Reportar avistamento
			 */
			reportSighting: () => LocalizedString
		}
		messages: {
			/**
			 * A enviar
			 */
			sending: () => LocalizedString
			/**
			 * Formulário submetido
			 */
			formSuccessTitle: () => LocalizedString
			/**
			 * Erro ao submeter formulário
			 */
			formErrorTitle: () => LocalizedString
			/**
			 * Obrigado por submeter o formulário
			 */
			formSuccessBody: () => LocalizedString
			/**
			 * Erro interno ao submeter formulário. Se o erro persistir, por favor contacte-nos por telefone: (+351) 911 111 241.
			 */
			formErrorBody: () => LocalizedString
		}
	}
	privacyPolicy: {
		/**
		 * Política de Privacidade
		 */
		header: () => LocalizedString
		/**
		 * De acordo com o art. º13.º do Regulamento Europeu de Proteção de Dados Pessoais Reg. UE 2016/679
		 */
		subHeader: () => LocalizedString
		/**
		 * Nesta Política de Privacidade, poderá encontrar todas as informações necessárias para melhor compreender como tratamos os seus dados pessoais.
		 */
		intro: () => LocalizedString
		sections: {
			'1': {
				/**
				 * 1. Responsável pelo Tratamento
				 */
				title: () => LocalizedString
				/**
				 * A RALVT, é a Responsável pelo Tratamento dos dados recolhidos neste sítio da internet. Poderá contactar-nos, por escrito, através do endereço eletrónico
				 */
				content: () => LocalizedString
			}
			'2': {
				/**
				 * 2. Finalidades do Tratamento e Fundamento Jurídico
				 */
				title: () => LocalizedString
				content: {
					/**
					 * No quadro infra, poderá verificar as categorias de dados pessoais que tratamos, e ainda para que finalidades os usamos.
					 */
					'21': () => LocalizedString
					/**
					 * É provável que nem todas as situações se apliquem ao seu caso concreto pois os dados recolhidos dependerão do formulário escolha preencher.
					 */
					'22': () => LocalizedString
					/**
					 * Os dados pessoais recolhidos em cada caso são os que são pedidos nos vários formulários e destinar-se-ão à finalidade inerente a cada ação ou situação em concreto. Os dados pessoais marcados com um asterisco (*) são de preenchimento obrigatório.
					 */
					'23': () => LocalizedString
					dataCategories: {
						'1': {
							/**
							 * a) Dados de Identificação: nome, número de telefone, endereço de email.
							 */
							header: () => LocalizedString
							/**
							 * nome, número de telefone, endereço de email. Estes têm como finalidade a recolha de informações para possível posterior contacto de forma a esclarecer informações sobre o arrojamento/avistamento de um animal marinho, ou para comunicar o potencial desfecho de um arrojamento/avistamento.
							 */
							text: () => LocalizedString
						}
						'2': {
							/**
							 * b) Imagem: Fotografias.
							 */
							header: () => LocalizedString
							/**
							 * A submissão destas é opcional, e o intuito é recolher informações visuais sobre o avistamento/arrojamento de um animal marinho.
							 */
							text: () => LocalizedString
						}
						'3': {
							/**
							 * c) Localização.
							 */
							header: () => LocalizedString
							/**
							 * O fornecimento deste é opcional, sendo o seu acesso possível apenas após a expressa permissão do utilizador, escolha que é guardada e utilizada em futuras visitas. O utilizador poderá a qualquer momento alterar estas preferências. A localização é usada para identificar, em coordenadas GPS, a localização do animal arrojado/avistado.
							 */
							text: () => LocalizedString
						}
						/**
						 * Categoria de dados e Finalidades:
						 */
						title: () => LocalizedString
					}
				}
			}
			'3': {
				/**
				 * 3. Categoria de destinatários dos dados
				 */
				title: () => LocalizedString
				content: {
					/**
					 * Para que sejam tratados de forma adequada para as finalidades referidas no n.º2, a RALVT possibilitará o acesso aos seus dados pessoais por parte das seguintes entidades:
					 */
					'31': () => LocalizedString
					/**
					 * Pessoas individuais, trabalhadores e / ou colaboradores que tenham sido designados para desempenhar uma ou mais atividades de tratamento dos seus dados na qualidade de “Pessoas Autorizadas” tal como previsto no artigo 29.º do RGPD;
					 */
					authorized: () => LocalizedString
					/**
					 * Os seus dados pessoais poderão ser comunicados a entidades públicas ou autoridades judiciais, se assim for obrigatório por lei ou para prevenir ou punir a prática de crimes.
					 */
					publicEntities: () => LocalizedString
					/**
					 * De acordo com o disposto no art.º4.º/9 do RGPD, “as autoridades públicas que possam receber dados pessoais no âmbito de inquéritos específicos nos termos do direito da União ou dos Estados-Membros não são consideradas destinatários”.
					 */
					authoroties: () => LocalizedString
					/**
					 * Por favor note que a RALVT ou as entidades por nós subcontratadas podem armazenar os seus dados fora do EEE. Nesse caso garantiremos que essas empresas subcontratadas estão sujeitas à legislação que foi considerada pela Comissão Europeia como prestando um grau de proteção adequado estão por isso a coberto de uma decisão de adequação ou equivalente.
					 */
					outsideEEE: () => LocalizedString
				}
			}
			'4': {
				/**
				 * 4. Prazo de Conservação
				 */
				title: () => LocalizedString
				/**
				 * A RALVT conservará os seus dados enquanto analisa o arrojamento/avistamento reportado, para as finalidades relacionadas com o seu processamento. Isto, sem prejuízo do exercício do seu direito de oposição quando aplicável. Após a cessação da análise da ocorrência poderemos conservar os seus dados para prova do cumprimento de obrigações legais, designadamente o RGPD, legislação fiscal, legislação respeitante a vendas à distância, entre outras. Neste caso apenas conservaremos os dados que sejam absolutamente necessários para esta finalidade e esses dados serão mantidos devidamente bloqueados e pseudonimizados. Apenas estarão acessíveis a pessoas especialmente autorizadas e exclusivamente para o cumprimento das finalidades suprarreferidas. Ainda assim, serão conservados apenas durante o prazo de prescrição da obrigação em causa, a qual poderá variar em função da legislação aplicável.
				 */
				content: () => LocalizedString
			}
			'5': {
				/**
				 * Poderá exercer os seguintes direitos, conforme previstos pelo RGPD, através do email
				 */
				'51': () => LocalizedString
				/**
				 * Poderá ainda contactar-nos através do número 911 111 241, para pedir informações sobre a forma como poderá exercer os seus direitos.
				 */
				'52': () => LocalizedString
				/**
				 * Sempre que os seus dados sejam processados com base no consentimento poderá retirar o seu consentimento em qualquer altura, sem que isso comprometa a licitude do tratamento efetuado com base no consentimento previamente dado.
				 */
				'53': () => LocalizedString
				/**
				 * Para dar cumprimento aos seus pedidos poderemos solicitar informação adicional para o podermos identificar tal como resulta do disposto no art.º11.º do RGPD em conjugação com o considerando 67.
				 */
				'54': () => LocalizedString
				/**
				 * 5. Direitos dos Titulares dos Dados
				 */
				title: () => LocalizedString
				content: {
					rights: {
						/**
						 * Direito de acesso à sua informação pessoal;
						 */
						'0': () => LocalizedString
						/**
						 * Direito de retificação dos seus dados;
						 */
						'1': () => LocalizedString
						/**
						 * Direito ao Apagamento dos dados;
						 */
						'2': () => LocalizedString
						/**
						 * Direito à limitação do tratamento;
						 */
						'3': () => LocalizedString
						/**
						 * Direito de Portabilidade;
						 */
						'4': () => LocalizedString
						/**
						 * Direito de oposição;
						 */
						'5': () => LocalizedString
						/**
						 * Direito de Oposição para efeitos de envio de comunicações de marketing;
						 */
						'6': () => LocalizedString
						/**
						 * Direito de apresentação de uma reclamação / queixa junto da CNPD - Comissão Nacional de Proteção de Dados (www.cnpd.pt); Neste caso, solicitamos o especial favor de nos contactar previamente à apresentação da reclamação junto da CNPD tendo em vista a resolução rápida do problema reportado.
						 */
						'7': () => LocalizedString
					}
				}
				/**
				 * No caso de recusa injustificada em identificar-se, se não estivermos possibilitados de o identificar de outra forma, reservamo-nos ao direito de não dar resposta ao seu pedido.
				 */
				final: () => LocalizedString
			}
			'6': {
				/**
				 * 6. Encarregado de Proteção de Dados
				 */
				title: () => LocalizedString
				/**
				 * A RALVT nomeou um Encarregado de Proteção de dados que poderá ser contactado através do email
				 */
				content: () => LocalizedString
			}
			'7': {
				/**
				 * 7. Segurança
				 */
				title: () => LocalizedString
				/**
				 * A RALVT implementou e manteve medidas de segurança e políticas técnicas e organizacionais para garantir a segurança dos dados pessoais que tratamos. Entre essas medidas encontram-se, designadamente, a execução de acordos de confidencialidade com os nossos colaboradores e fornecedores; políticas de restrição e controlo de acesso a dados pessoais; destruição ou anonimização de dados pessoais que já não são necessários para as finalidades que determinaram a sua recolha; Uma vez que a segurança de informação depende em parte da segurança do seu computador ou aparelho eletrónico que usa para comunicar connosco, e ainda da segurança que emprega para proteger nomes de utilizador e palavras-passe, por favor tome as medidas adequadas para proteger esta informação.
				 */
				content: () => LocalizedString
			}
			'8': {
				/**
				 * 8. Versão e alterações
				 */
				title: () => LocalizedString
				/**
				 * A última redação da presente Política de Privacidade é de 20 de maio de 2023. A RALVT poderá realizar alterações ao teor da presente Política de Privacidade. Tais alterações serão comunicadas, nos termos legais, ao utilizador.
				 */
				content: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
