// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * R​e​d​e​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o
	 */
	RALVT: string
	languages: {
		/**
		 * P​o​r​t​u​g​u​ê​s
		 */
		pt: string
		/**
		 * I​n​g​l​ê​s
		 */
		en: string
	}
	/**
	 * C​o​m​ ​o​ ​a​p​o​i​o​ ​d​e​:
	 */
	partners: string
}

export type TranslationFunctions = {
	/**
	 * Rede de Arrojamentos de Lisboa e Vale do Tejo
	 */
	RALVT: () => LocalizedString
	languages: {
		/**
		 * Português
		 */
		pt: () => LocalizedString
		/**
		 * Inglês
		 */
		en: () => LocalizedString
	}
	/**
	 * Com o apoio de:
	 */
	partners: () => LocalizedString
}

export type Formatters = {}
