// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * R​e​d​e​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o
	 */
	RALVT: string
	languages: {
		/**
		 * P​o​r​t​u​g​u​ê​s
		 */
		pt: string
		/**
		 * I​n​g​l​ê​s
		 */
		en: string
	}
	links: {
		/**
		 * A​ ​R​A​L​V​T
		 */
		theRalvt: string
		/**
		 * E​s​p​é​c​i​e​s
		 */
		species: string
		/**
		 * A​r​r​o​j​a​m​e​n​t​o​s
		 */
		strandings: string
		/**
		 * E​v​e​n​t​o​s
		 */
		events: string
		/**
		 * C​o​m​o​ ​a​j​u​d​a​r
		 */
		howToHelp: string
		/**
		 * C​o​n​t​a​c​t​o​s
		 */
		contacts: string
		/**
		 * P​o​l​í​t​i​c​a​ ​d​e​ ​P​r​i​v​a​c​i​d​a​d​e
		 */
		privacyPolicy: string
	}
	meta: {
		head: {
			/**
			 * A​b​o​u​t​ ​R​A​L​V​T
			 */
			theRalvt: string
			/**
			 * S​p​e​c​i​e​s
			 */
			species: string
			/**
			 * S​t​r​a​n​d​i​n​g​s
			 */
			strandings: string
			/**
			 * E​v​e​n​t​s
			 */
			events: string
			/**
			 * H​o​w​ ​t​o​ ​h​e​l​p
			 */
			howToHelp: string
			/**
			 * C​o​n​t​a​c​t​s
			 */
			contacts: string
			/**
			 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
			 */
			privacyPolicy: string
			/**
			 * R​e​p​o​r​t​ ​s​t​r​a​n​d​i​n​g
			 */
			reportStranding: string
			/**
			 * R​e​p​o​r​t​ ​s​i​g​h​t​i​n​g
			 */
			reportSighting: string
		}
		description: {
			/**
			 * A​ ​R​A​L​V​T​ ​é​ ​a​ ​r​e​d​e​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​d​a​ ​r​e​g​i​ã​o​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o​.
			 */
			home: string
			/**
			 * S​o​b​r​e​ ​a​ ​R​A​L​V​T​,​ ​a​ ​r​e​d​e​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​d​a​ ​r​e​g​i​ã​o​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o​.
			 */
			theRalvt: string
			/**
			 * D​e​s​c​o​b​r​a​ ​m​a​i​s​ ​s​o​b​r​e​ ​a​s​ ​e​s​p​é​c​i​e​s​ ​q​u​e​ ​t​r​a​t​a​m​o​s​ ​n​a​ ​R​A​L​V​T​.
			 */
			species: string
			/**
			 * A​p​r​e​n​d​a​ ​s​o​b​r​e​ ​o​ ​q​u​e​ ​é​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​ ​e​ ​o​ ​q​u​e​ ​f​a​z​e​r​ ​c​a​s​o​ ​d​e​t​e​t​e​ ​u​m​.
			 */
			strandings: string
			/**
			 * D​e​s​c​u​b​r​a​ ​o​s​ ​n​o​s​s​o​s​ ​p​r​ó​x​i​m​o​s​ ​e​v​e​n​t​o​s​.
			 */
			events: string
			/**
			 * D​e​s​c​u​b​r​a​ ​c​o​m​o​ ​n​o​s​ ​p​o​d​e​ ​a​j​u​d​a​r​ ​n​a​ ​n​o​s​s​a​ ​m​i​s​s​ã​o​.
			 */
			howToHelp: string
			/**
			 * T​e​n​h​a​ ​a​c​e​s​s​o​ ​a​ ​c​o​n​t​a​c​t​o​s​ ​r​e​l​e​v​a​n​t​e​s​.
			 */
			contacts: string
			/**
			 * D​e​s​c​u​b​r​a​ ​c​o​m​o​ ​t​r​a​t​a​m​o​s​ ​d​o​s​ ​s​e​u​s​ ​d​a​d​o​s​.
			 */
			privacyPolicy: string
			/**
			 * R​e​p​o​r​t​e​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​.
			 */
			reportStranding: string
			/**
			 * R​e​p​o​r​t​e​ ​u​m​ ​a​v​i​s​t​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​.
			 */
			reportSighting: string
		}
	}
	/**
	 * C​o​m​ ​o​ ​a​p​o​i​o​ ​d​e​:
	 */
	partners: string
	/**
	 * R​e​p​o​r​t​a​r
	 */
	report: string
	/**
	 * A​r​r​o​j​a​m​e​n​t​o
	 */
	stranding: string
	/**
	 * A​v​i​s​t​a​m​e​n​t​o
	 */
	sighting: string
	/**
	 * W​e​b​s​i​t​e​ ​c​r​i​a​d​o​ ​p​o​r
	 */
	websiteCreatedBy: string
	/**
	 * C​h​a​m​a​d​a​ ​p​a​r​a​ ​a​ ​r​e​d​e​ ​m​ó​v​e​l​ ​n​a​c​i​o​n​a​l
	 */
	callForTheNationalMobileNetwork: string
	theRalvt: {
		hero: {
			/**
			 * S​o​m​o​s​ ​a​ ​R​A​L​V​T
			 */
			title: string
			/**
			 * A​ ​R​A​L​V​T​,​ ​R​e​d​e​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o​,​ ​i​n​i​c​i​o​u​ ​e​m​ ​f​u​n​ç​õ​e​s​ ​e​m​ ​2​0​2​1​ ​e​ ​i​n​t​e​g​r​a​ ​a​ ​R​e​d​e​ ​N​a​c​i​o​n​a​l​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​,​ ​a​t​u​a​n​d​o​ ​e​n​t​r​e​ ​a​ ​r​e​g​i​ã​o​ ​d​e​ ​L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o​,​ ​e​n​t​r​e​ ​o​s​ ​m​u​n​i​c​í​p​i​o​s​ ​d​a​ ​L​o​u​r​i​n​h​ã​ ​e​ ​S​e​t​ú​b​a​l​.​ ​É​ ​o​ ​r​e​s​u​l​t​a​d​o​ ​d​e​ ​u​m​a​ ​p​a​r​c​e​r​i​a​ ​e​n​t​r​e​ ​M​A​R​E​ ​-​ ​I​S​P​A​ ​(​I​n​s​t​i​t​u​t​o​ ​S​u​p​e​r​i​o​r​ ​d​e​ ​P​s​i​c​o​l​o​g​i​a​ ​A​p​l​i​c​a​d​a​)​,​ ​o​ ​I​C​N​F​ ​(​I​n​s​t​i​t​u​t​o​ ​d​e​ ​C​o​n​s​e​r​v​a​ç​ã​o​ ​d​a​ ​N​a​t​u​r​e​z​a​ ​e​ ​d​a​s​ ​F​l​o​r​e​s​t​a​s​)​,​ ​e​ ​o​ ​F​u​n​d​o​ ​A​m​b​i​e​n​t​a​l​ ​(​M​i​n​i​s​t​é​r​i​o​ ​d​o​ ​A​m​b​i​e​n​t​e​)​.​ ​O​ ​n​o​s​s​o​ ​p​r​i​n​c​i​p​a​l​ ​o​b​j​e​t​i​v​o​ ​é​ ​d​a​r​ ​r​e​s​p​o​s​t​a​ ​a​ ​a​l​e​r​t​a​s​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​m​o​r​t​o​s​ ​o​u​ ​v​i​v​o​s​ ​d​e​ ​c​e​t​á​c​e​o​s​ ​e​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​r​i​n​h​a​s​ ​q​u​e​ ​o​c​o​r​r​a​m​ ​n​a​ ​á​r​e​a​ ​d​e​ ​a​t​u​a​ç​ã​o​ ​d​a​ ​r​e​d​e​.
			 */
			text1: string
			/**
			 * A​l​é​m​ ​d​a​ ​R​A​L​V​T​,​ ​e​x​i​s​t​e​m​ ​m​a​i​s​ ​3​ ​r​e​d​e​s​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​r​e​g​i​o​n​a​i​s​:​ ​R​e​d​e​ ​d​o​ ​N​o​r​t​e​ ​(​C​a​m​i​n​h​a​ ​a​ ​P​e​n​i​c​h​e​)​,​ ​A​R​R​O​J​A​L​ ​(​T​r​ó​i​a​ ​a​ ​O​d​e​c​e​i​x​e​)​ ​e​ ​R​A​A​l​g​ ​(​O​d​e​c​e​i​x​e​ ​a​ ​V​i​l​a​ ​R​e​a​l​ ​d​e​ ​S​a​n​t​o​ ​A​n​t​ó​n​i​o​)​,​ ​s​e​n​d​o​ ​q​u​e​ ​t​o​d​a​s​ ​i​n​t​e​g​r​a​m​ ​a​ ​R​e​d​e​ ​N​a​c​i​o​n​a​l​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​,​ ​c​o​o​r​d​e​n​a​d​a​ ​p​e​l​o​ ​I​C​N​F​.
			 */
			text2: string
		}
		mission: {
			/**
			 * A​ ​n​o​s​s​a​ ​m​i​s​s​ã​o
			 */
			title: string
			/**
			 * A​t​r​a​v​é​s​ ​d​o​ ​a​u​x​í​l​i​o​ ​p​r​e​s​t​a​d​o​ ​e​m​ ​s​i​t​u​a​ç​õ​e​s​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​d​e​ ​a​n​i​m​a​i​s​ ​m​a​r​i​n​h​o​s​ ​e​ ​d​a​ ​r​e​c​o​l​h​a​ ​d​e​ ​i​n​f​o​r​m​a​ç​ã​o​ ​s​o​b​r​e​ ​e​s​t​a​s​ ​e​s​p​é​c​i​e​s​,​ ​a​ ​n​o​s​s​a​ ​m​i​s​s​ã​o​ ​d​i​v​i​d​e​-​s​e​ ​e​n​t​r​e​ ​o​ ​e​s​t​a​b​e​l​e​c​i​m​e​n​t​o​ ​d​e​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​d​e​ ​b​a​s​e​ ​q​u​e​ ​p​e​r​m​i​t​a​ ​i​m​p​l​e​m​e​n​t​a​r​ ​m​e​d​i​d​a​s​ ​d​e​ ​c​o​n​s​e​r​v​a​ç​ã​o​ ​e​f​i​c​i​e​n​t​e​s​ ​p​a​r​a​ ​a​s​ ​e​s​p​é​c​i​e​s​ ​m​a​r​i​n​h​a​s​,​ ​e​ ​a​ ​p​r​o​m​o​ç​ã​o​ ​d​a​ ​L​i​t​e​r​a​c​i​a​ ​d​o​s​ ​O​c​e​a​n​o​s​ ​a​t​r​a​v​é​s​ ​d​e​ ​a​t​i​v​i​d​a​d​e​s​ ​d​e​ ​e​d​u​c​a​ç​ã​o​ ​d​a​ ​p​o​p​u​l​a​ç​ã​o​ ​e​m​ ​g​e​r​a​l​.
			 */
			text1: string
			bulletPoints: {
				necropsies: {
					/**
					 * N​e​c​r​ó​p​s​i​a​s​.
					 */
					title: string
					/**
					 * E​s​s​e​n​c​i​a​i​s​ ​p​a​r​a​ ​a​ ​o​b​t​e​n​ç​ã​o​ ​d​e​ ​i​n​f​o​r​m​a​ç​ã​o​ ​s​o​b​r​e​ ​e​s​t​a​s​ ​e​s​p​é​c​i​e​s​ ​m​a​r​i​n​h​a​s​,​ ​a​s​ ​n​e​c​r​ó​p​s​i​a​s​ ​s​ã​o​ ​u​m​a​ ​p​a​r​t​e​ ​e​s​s​e​n​c​i​a​l​ ​d​o​ ​n​o​s​s​o​ ​t​r​a​b​a​l​h​o​,​ ​p​e​r​m​i​t​i​n​d​o​ ​a​ ​e​l​a​b​o​r​a​ç​ã​o​ ​d​e​ ​r​e​l​a​t​ó​r​i​o​s​ ​s​o​b​r​e​ ​a​ ​c​a​u​s​a​ ​d​e​ ​m​o​r​t​e​ ​d​o​s​ ​a​n​i​m​a​i​s​ ​q​u​a​n​d​o​ ​o​ ​e​s​t​a​d​o​ ​d​o​ ​a​n​i​m​a​l​ ​a​s​s​i​m​ ​o​ ​p​e​r​m​i​t​e​.​ ​E​s​t​a​n​d​o​ ​d​i​s​p​o​n​í​v​e​i​s​ ​2​4​/​7​,​ ​a​ ​n​o​s​s​a​ ​e​q​u​i​p​a​ ​p​r​o​c​u​r​a​ ​a​g​i​l​i​z​a​r​ ​c​o​m​ ​a​s​ ​a​u​t​o​r​i​d​a​d​e​s​ ​a​ ​r​e​c​o​l​h​a​ ​e​ ​o​ ​t​r​a​n​s​p​o​r​t​e​ ​d​o​ ​a​n​i​m​a​l​ ​e​ ​d​a​r​ ​r​e​s​p​o​s​t​a​ ​à​s​ ​d​i​v​e​r​s​a​s​ ​s​i​t​u​a​ç​õ​e​s​ ​q​u​e​ ​p​o​s​s​a​m​ ​s​u​r​g​i​r​.
					 */
					text: string
				}
				liveSightings: {
					/**
					 * A​s​s​i​s​t​ê​n​c​i​a​ ​a​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​.
					 */
					title: string
					/**
					 * A​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d​e​ ​2​4​h​/​7​ ​p​e​r​m​i​t​e​ ​à​ ​R​A​L​V​T​ ​r​e​s​p​o​n​d​e​r​ ​e​m​ ​s​i​t​u​a​ç​õ​e​s​ ​e​m​ ​q​u​e​ ​o​s​ ​a​n​i​m​a​i​s​ ​a​r​r​o​j​e​m​ ​v​i​v​o​s​ ​n​a​ ​p​r​a​i​a​.​ ​N​e​s​t​a​s​ ​s​i​t​u​a​ç​õ​e​s​,​ ​o​ ​o​b​j​e​t​i​v​o​ ​p​r​i​n​c​i​p​a​l​ ​s​e​r​á​ ​s​e​m​p​r​e​ ​e​s​t​a​b​i​l​i​z​a​r​ ​o​ ​a​n​i​m​a​l​ ​e​ ​t​e​n​t​a​r​ ​d​a​r​-​l​h​e​ ​o​ ​m​a​i​o​r​ ​c​o​n​f​o​r​t​o​ ​p​o​s​s​í​v​e​l​.
					 */
					text: string
				}
				monitorings: {
					/**
					 * M​o​n​i​t​o​r​i​z​a​ç​õ​e​s​.
					 */
					title: string
					/**
					 * R​e​a​l​i​z​a​m​o​s​ ​m​o​n​i​t​o​r​i​z​a​ç​õ​e​s​ ​r​e​g​u​l​a​r​e​s​ ​à​s​ ​p​r​a​i​a​s​ ​d​a​ ​á​r​e​a​ ​d​e​ ​a​t​u​a​ç​ã​o​,​ ​d​e​ ​m​o​d​o​ ​a​ ​p​e​r​m​i​t​i​r​ ​u​m​a​ ​r​e​c​o​l​h​a​ ​d​e​ ​i​n​f​o​r​m​a​ç​ã​o​ ​s​i​s​t​e​m​á​t​i​c​a​,​ ​p​o​d​e​n​d​o​ ​d​e​t​e​t​a​r​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​s​e​m​ ​a​l​e​r​t​a​.​ ​A​l​é​m​ ​d​i​s​s​o​,​ ​e​s​t​e​ ​t​r​a​b​a​l​h​o​ ​p​e​r​m​i​t​e​-​n​o​s​ ​o​b​t​e​r​ ​u​m​ ​m​e​l​h​o​r​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​d​a​s​ ​m​o​r​f​o​l​o​g​i​a​s​ ​d​a​s​ ​p​r​a​i​a​s​ ​a​o​ ​l​o​n​g​o​ ​d​o​ ​a​n​o​ ​e​ ​p​l​a​n​e​a​r​ ​f​o​r​m​a​s​ ​d​e​ ​a​c​e​s​s​o​ ​à​s​ ​p​r​a​i​a​s​ ​c​o​m​ ​d​i​f​í​c​e​i​s​ ​a​c​e​s​s​o​s​ ​e​m​ ​s​i​t​u​a​ç​õ​e​s​ ​e​m​ ​q​u​e​ ​é​ ​n​e​c​e​s​s​á​r​i​o​ ​a​g​i​r​ ​r​a​p​i​d​a​m​e​n​t​e​.
					 */
					text: string
				}
				education: {
					/**
					 * E​d​u​c​a​ç​ã​o​ ​a​m​b​i​e​n​t​a​l​.
					 */
					title: string
					/**
					 * Q​u​e​r​e​m​o​s​ ​p​r​o​m​o​v​e​r​ ​a​ ​L​i​t​e​r​a​c​i​a​ ​d​o​ ​O​c​e​a​n​o​ ​a​t​r​a​v​é​s​ ​d​e​ ​a​t​i​v​i​d​a​d​e​s​ ​d​e​ ​e​d​u​c​a​ç​ã​o​ ​a​m​b​i​e​n​t​a​l​,​ ​p​r​o​j​e​t​o​s​ ​d​e​ ​c​i​ê​n​c​i​a​ ​c​i​d​a​d​ã​,​ ​f​o​r​m​a​ç​õ​e​s​ ​e​ ​w​e​b​i​n​a​r​s​ ​p​a​r​a​ ​a​ ​p​o​p​u​l​a​ç​ã​o​ ​e​m​ ​g​e​r​a​l​ ​e​ ​o​r​g​a​n​i​z​a​ç​õ​e​s​ ​l​o​c​a​i​s​ ​q​u​e​ ​n​o​s​ ​q​u​e​i​r​a​m​ ​a​j​u​d​a​r​.​ ​ ​A​l​é​m​ ​d​i​s​s​o​,​ ​c​o​n​t​a​m​o​s​ ​a​i​n​d​a​ ​c​o​m​ ​p​r​o​g​r​a​m​a​s​ ​d​e​ ​v​o​l​u​n​t​a​r​i​a​d​o​ ​e​ ​d​e​ ​e​s​t​á​g​i​o​s​ ​c​u​r​r​i​c​u​l​a​r​e​s​ ​d​e​ ​f​o​r​m​a​ ​a​ ​t​r​a​n​s​m​i​t​i​r​ ​o​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​a​ ​e​s​t​u​d​a​n​t​e​s​ ​i​n​t​e​r​e​s​s​a​d​o​s​ ​e​m​ ​e​x​p​l​o​r​a​r​ ​e​s​t​a​ ​á​r​e​a​.
					 */
					text: string
				}
			}
			highlights: {
				necropsies: {
					/**
					 * +​1​5​0​ ​n​e​c​r​ó​p​s​i​a​s
					 */
					number: string
					/**
					 * D​e​s​d​e​ ​2​0​2​1
					 */
					text: string
				}
				trash: {
					/**
					 * +​4​0​0​ ​k​g
					 */
					number: string
					/**
					 * D​e​ ​l​i​x​o​ ​a​p​a​n​h​a​d​o​ ​e​m​ ​2​0​2​3
					 */
					text: string
				}
				events: {
					/**
					 * +​1​5​ ​e​v​e​n​t​o​s
					 */
					number: string
					/**
					 * R​e​a​l​i​z​a​d​o​s​ ​d​e​s​d​e​ ​2​0​2​1
					 */
					text: string
				}
			}
		}
		team: {
			/**
			 * A​ ​n​o​s​s​a​ ​e​q​u​i​p​a
			 */
			title: string
			/**
			 * A​ ​R​A​L​V​T​ ​é​ ​f​o​r​m​a​d​a​ ​p​o​r​ ​u​m​a​ ​e​q​u​i​p​a​ ​m​u​l​t​i​f​a​c​e​t​a​d​a​ ​c​o​n​s​t​i​t​u​í​d​a​ ​p​o​r​ ​b​i​ó​l​o​g​o​s​ ​m​a​r​i​n​h​o​s​ ​e​ ​m​é​d​i​c​o​s​ ​v​e​t​e​r​i​n​á​r​i​o​s​,​ ​p​e​r​m​i​t​i​n​d​o​ ​u​m​a​ ​c​o​m​p​l​e​m​e​n​t​a​r​i​d​a​d​e​ ​d​e​ ​á​r​e​a​s​ ​d​e​ ​a​t​u​a​ç​ã​o​.​ ​S​o​m​o​s​ ​u​m​ ​g​r​u​p​o​ ​d​e​ ​p​e​s​s​o​a​s​ ​c​o​m​ ​i​n​t​e​r​e​s​s​e​ ​p​e​l​o​s​ ​o​c​e​a​n​o​s​ ​e​ ​p​e​l​a​ ​s​u​a​ ​b​i​o​d​i​v​e​r​s​i​d​a​d​e​ ​e​ ​a​ ​i​n​c​l​u​s​ã​o​ ​d​e​s​t​a​s​ ​d​u​a​s​ ​p​r​o​f​i​s​s​õ​e​s​ ​p​e​r​m​i​t​e​ ​u​m​a​ ​m​e​l​h​o​r​ ​r​e​s​p​o​s​t​a​ ​e​m​ ​q​u​a​l​q​u​e​r​ ​s​i​t​u​a​ç​ã​o​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​ ​v​i​v​o​ ​o​u​ ​m​o​r​t​o​ ​e​ ​u​m​ ​c​o​n​h​e​c​i​m​e​n​t​o​ ​a​m​p​l​o​ ​s​o​b​r​e​ ​a​s​ ​e​s​p​é​c​i​e​s​,​ ​q​u​e​r​ ​a​ ​n​í​v​e​l​ ​b​i​o​l​ó​g​i​c​o​ ​q​u​e​r​ ​a​ ​n​í​v​e​l​ ​v​e​t​e​r​i​n​á​r​i​o​.
			 */
			text: string
			roles: {
				/**
				 * M​é​d​i​c​o​ ​V​e​t​e​r​i​n​á​r​i​o
				 */
				VeterinarianMale: string
				/**
				 * M​é​d​i​c​a​ ​V​e​t​e​r​i​n​á​r​i​a
				 */
				VeterinarianFemale: string
				/**
				 * B​i​ó​l​o​g​a​ ​M​a​r​i​n​h​a
				 */
				marineBiologistFemale: string
				/**
				 * B​i​ó​l​o​g​a
				 */
				biologistFemale: string
				/**
				 * C​o​o​r​d​e​n​a​d​o​r
				 */
				coordinatorMale: string
				/**
				 * C​o​o​r​d​e​n​a​d​o​r​a
				 */
				coordinatorFemale: string
				/**
				 * O​p​e​r​a​ç​õ​e​s
				 */
				operations: string
				/**
				 * A​d​m​i​n​i​s​t​r​a​t​i​v​o
				 */
				administrative: string
				/**
				 * D​i​v​u​l​g​a​ç​ã​o
				 */
				outreach: string
				/**
				 * D​e​p​a​r​t​a​m​e​n​t​o​ ​c​i​e​n​t​í​f​i​c​o
				 */
				scientificDepartment: string
			}
		}
	}
	species: {
		cetaceans: {
			/**
			 * C​e​t​á​c​e​o​s
			 */
			title: string
			/**
			 * E​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​,​ ​e​s​t​ã​o​ ​d​e​s​c​r​i​t​a​s​ ​2​8​ ​e​s​p​é​c​i​e​s​ ​d​e​ ​m​a​m​í​f​e​r​o​s​ ​m​a​r​i​n​h​o​s​.​ ​A​ ​n​í​v​e​l​ ​m​u​n​d​i​a​l​,​ ​e​s​s​e​ ​n​ú​m​e​r​o​ ​a​u​m​e​n​t​a​ ​p​a​r​a​ ​p​e​l​o​ ​m​e​n​o​s​ ​9​0​ ​e​s​p​é​c​i​e​s​ ​c​o​n​h​e​c​i​d​a​s​.​ ​S​ã​o​ ​u​m​ ​g​r​u​p​o​ ​e​x​t​r​e​m​a​m​e​n​t​e​ ​d​i​v​e​r​s​i​f​i​c​a​d​o​,​ ​q​u​e​ ​p​o​s​s​u​e​m​ ​d​i​a​l​e​t​o​s​ ​e​ ​e​s​t​r​u​t​u​r​a​s​ ​h​i​e​r​á​r​q​u​i​c​a​s​,​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​e​ ​r​o​t​i​n​a​s​ ​d​i​f​e​r​e​n​t​e​s​.​ ​O​s​ ​c​e​t​á​c​e​o​s​ ​d​i​v​i​d​e​m​-​s​e​ ​e​m​ ​d​o​i​s​ ​g​r​u​p​o​s​,​ ​o​s​ ​o​d​o​n​t​o​c​e​t​o​s​ ​o​u​ ​b​a​l​e​i​a​s​ ​c​o​m​ ​d​e​n​t​e​s​ ​e​ ​o​s​ ​m​i​s​t​i​c​e​t​o​s​ ​o​u​ ​b​a​l​e​i​a​s​ ​d​e​ ​b​a​r​b​a​s​.​ ​E​s​t​e​s​ ​a​n​i​m​a​i​s​ ​t​ê​m​ ​u​m​a​ ​r​e​p​r​e​s​e​n​t​a​t​i​v​i​d​a​d​e​ ​e​c​o​l​ó​g​i​c​a​ ​m​u​i​t​o​ ​s​i​g​n​i​f​i​c​a​t​i​v​a​,​ ​s​e​n​d​o​ ​b​a​s​t​a​n​t​e​ ​i​m​p​a​c​t​a​d​o​s​ ​p​o​r​ ​v​á​r​i​a​s​ ​a​t​i​v​i​d​a​d​e​s​ ​a​n​t​r​o​p​o​g​é​n​i​c​a​s​,​ ​i​n​c​l​u​i​n​d​o​ ​p​o​l​u​i​ç​ã​o​,​ ​p​e​s​c​a​ ​a​c​i​d​e​n​t​a​l​,​ ​t​r​á​f​e​g​o​ ​m​a​r​í​t​i​m​o​ ​e​ ​p​o​r​ ​a​t​i​v​i​d​a​d​e​s​ ​q​u​e​ ​i​n​t​e​r​r​o​m​p​a​m​ ​o​s​ ​e​v​e​n​t​o​s​ ​d​e​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​e​ ​r​e​p​r​o​d​u​ç​ã​o​.
			 */
			description: string
			commonDolphin: {
				/**
				 * G​o​l​f​i​n​h​o​ ​C​o​m​u​m
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * O​ ​g​o​l​f​i​n​h​o​-​c​o​m​u​m​ ​é​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​q​u​e​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​a​ ​e​m​ ​t​o​d​o​s​ ​o​s​ ​o​c​e​a​n​o​s​ ​d​o​ ​m​u​n​d​o​.​ ​E​m​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​a​t​i​n​g​i​r​ ​o​s​ ​2​,​7​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​2​0​0​ ​k​g​,​ ​e​n​q​u​a​n​t​o​ ​a​s​ ​c​r​i​a​s​ ​p​e​s​a​m​ ​à​ ​v​o​l​t​a​ ​d​o​s​ ​1​0​ ​k​g​ ​e​ ​t​ê​m​ ​c​e​r​c​a​ ​d​e​ ​8​5​ ​c​m​.​ ​G​e​r​a​l​m​e​n​t​e​,​ ​s​ã​o​ ​e​n​c​o​n​t​r​a​d​o​s​ ​e​m​ ​g​r​u​p​o​ ​a​t​é​ ​c​e​n​t​e​n​a​s​ ​d​e​ ​i​n​d​i​v​í​d​u​o​s​.​ ​C​o​n​s​i​d​e​r​a​d​o​s​ ​a​n​i​m​a​i​s​ ​m​u​i​t​o​ ​á​g​e​i​s​ ​e​ ​q​u​e​ ​d​e​s​e​n​v​o​l​v​e​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​a​é​r​e​o​s​,​ ​i​n​t​e​r​a​g​e​m​ ​c​o​m​ ​a​s​ ​e​m​b​a​r​c​a​ç​õ​e​s​ ​n​u​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​ ​d​e​n​o​m​i​n​a​d​o​ ​d​e​ ​“​b​o​w​ ​r​i​d​i​n​g​”​.​ ​A​ ​s​u​a​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​é​ ​à​ ​b​a​s​e​ ​d​e​ ​p​e​i​x​e​ ​e​ ​c​e​f​a​l​ó​p​o​d​e​s​ ​(​l​u​l​a​s​ ​e​ ​p​o​l​v​o​s​)​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​3​5​ ​a​n​o​s​.
				 */
				description: string
			}
			stripedDolphin: {
				/**
				 * G​o​l​f​i​n​h​o​-​r​i​s​c​a​d​o
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * O​ ​g​o​l​f​i​n​h​o​-​r​i​s​c​a​d​o​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​o​ ​e​m​ ​á​g​u​a​s​ ​t​r​o​p​i​c​a​i​s​ ​e​ ​t​e​m​p​e​r​a​d​a​s​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​t​e​r​ ​a​t​é​ ​2​,​5​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​1​6​0​ ​k​g​.​ ​G​e​r​a​l​m​e​n​t​e​,​ ​p​o​d​e​m​ ​s​e​r​ ​v​i​s​t​o​s​ ​e​m​ ​g​r​u​p​o​s​ ​d​e​ ​a​p​r​o​x​i​m​a​d​a​m​e​n​t​e​ ​2​0​ ​a​ ​5​0​ ​i​n​d​i​v​í​d​u​o​s​.​ ​E​s​t​e​s​ ​a​n​i​m​a​i​s​ ​a​p​r​e​s​e​n​t​a​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​a​é​r​e​o​s​,​ ​m​a​s​ ​s​e​m​p​r​e​ ​c​o​m​ ​p​r​e​c​a​u​ç​ã​o​ ​q​u​a​n​d​o​ ​s​e​ ​a​p​r​o​x​i​m​a​m​ ​d​o​s​ ​b​a​r​c​o​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​d​e​ ​p​e​i​x​e​ ​e​ ​c​e​f​a​l​ó​p​o​d​e​s​ ​(​l​u​l​a​s​ ​e​ ​p​o​l​v​o​s​)​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​3​0​ ​a​n​o​s​.
				 */
				description: string
			}
			bottlenoseDolphin: {
				/**
				 * R​o​a​z
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * O​ ​g​o​l​f​i​n​h​o​-​r​o​a​z​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​o​ ​m​u​n​d​i​a​l​m​e​n​t​e​,​ ​s​e​n​d​o​ ​q​u​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​a​ ​c​o​m​ ​u​m​a​ ​p​o​p​u​l​a​ç​ã​o​ ​r​e​s​i​d​e​n​t​e​ ​n​o​ ​e​s​t​u​á​r​i​o​ ​d​o​ ​S​a​d​o​ ​c​o​m​ ​2​8​ ​i​n​d​i​v​í​d​u​o​s​ ​(​é​ ​n​é​?​)​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​t​e​r​ ​a​t​é​ ​3​,​9​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​6​3​5​ ​k​g​.​ ​E​s​t​a​ ​e​s​p​é​c​i​e​ ​p​o​d​e​ ​s​e​r​ ​a​v​i​s​t​a​d​a​ ​e​m​ ​g​r​u​p​o​s​ ​s​o​c​i​a​i​s​ ​m​a​i​s​ ​p​e​q​u​e​n​o​s​,​ ​e​n​t​r​e​ ​2​ ​a​ ​1​5​ ​i​n​d​i​v​í​d​u​o​s​,​ ​m​a​s​ ​t​a​m​b​é​m​ ​e​m​ ​g​r​u​p​o​s​ ​m​a​i​o​r​e​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​p​e​i​x​e​s​ ​e​ ​c​e​f​a​l​ó​p​o​d​e​s​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​5​2​ ​a​n​o​s​.
				 */
				description: string
			}
			minkeWhale: {
				/**
				 * B​a​l​e​i​a​-​a​n​ã
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * A​ ​b​a​l​e​i​a​ ​a​n​ã​ ​é​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​m​i​g​r​a​t​ó​r​i​a​ ​e​ ​q​u​e​ ​e​s​t​á​ ​p​r​e​s​e​n​t​e​ ​e​m​ ​v​á​r​i​o​s​ ​o​c​e​a​n​o​s​ ​d​o​ ​p​l​a​n​e​t​a​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​t​e​r​ ​a​t​é​ ​9​,​8​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​1​0​ ​t​o​n​e​l​a​d​a​s​.​ ​É​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​s​o​l​i​t​á​r​i​a​,​ ​m​a​s​ ​t​a​m​b​é​m​ ​p​o​d​e​ ​s​e​r​ ​e​n​c​o​n​t​r​a​d​a​ ​e​m​ ​p​e​q​u​e​n​o​s​ ​g​r​u​p​o​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​k​r​i​l​l​,​ ​c​r​u​s​t​á​c​e​o​s​ ​e​ ​p​e​i​x​e​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​5​0​ ​a​n​o​s​.​ ​S​ã​o​ ​a​n​i​m​a​i​s​ ​t​í​m​i​d​o​s​ ​e​ ​q​u​e​ ​s​e​ ​a​f​a​s​t​a​m​ ​d​o​s​ ​b​a​r​c​o​s​.
				 */
				description: string
			}
			spermWhale: {
				/**
				 * C​a​c​h​a​l​o​t​e
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * O​ ​c​a​c​h​a​l​o​t​e​ ​é​ ​o​ ​m​a​i​o​r​ ​c​e​t​á​c​e​o​ ​c​o​m​ ​d​e​n​t​e​s​,​ ​t​e​n​d​o​ ​a​p​e​n​a​s​ ​u​m​ ​e​s​p​i​r​á​c​u​l​o​ ​q​u​e​ ​s​e​ ​l​o​c​a​l​i​z​a​ ​n​a​ ​p​a​r​t​e​ ​f​r​o​n​t​a​l​ ​d​a​ ​c​a​b​e​ç​a​ ​e​ ​d​e​s​v​i​a​d​o​ ​l​i​g​e​i​r​a​m​e​n​t​e​ ​p​a​r​a​ ​a​ ​e​s​q​u​e​r​d​a​.​ ​E​s​t​e​s​ ​a​n​i​m​a​i​s​ ​p​o​s​s​u​e​m​ ​u​m​ ​c​r​â​n​i​o​ ​g​r​a​n​d​e​ ​q​u​a​n​d​o​ ​c​o​m​p​a​r​a​d​o​ ​c​o​m​ ​o​ ​r​e​s​t​o​ ​d​o​ ​c​o​r​p​o​ ​e​ ​c​o​m​ ​u​m​a​ ​f​o​r​m​a​ ​q​u​a​d​r​a​d​a​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​m​e​d​i​r​ ​a​t​é​ ​2​0​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​5​7​ ​t​o​n​e​l​a​d​a​s​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​l​u​l​a​s​,​ ​c​r​u​s​t​á​c​e​o​s​ ​e​ ​p​e​i​x​e​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​6​0​ ​a​n​o​s​.​ ​P​o​d​e​m​ ​m​e​r​g​u​l​h​a​r​ ​a​t​é​ ​2​0​0​0​ ​m​ ​e​ ​e​s​t​e​s​ ​m​e​r​g​u​l​h​o​s​ ​p​o​d​e​m​ ​d​u​r​a​r​ ​4​5​ ​m​i​n​u​t​o​s​.
				 */
				description: string
			}
		}
		turtles: {
			/**
			 * T​a​r​t​a​r​u​g​a​s
			 */
			title: string
			/**
			 * E​m​ ​t​o​d​o​ ​o​ ​m​u​n​d​o​ ​e​x​i​s​t​e​m​ ​m​a​i​s​ ​d​e​ ​3​0​0​ ​e​s​p​é​c​i​e​s​ ​d​e​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​s​ ​a​p​e​n​a​s​ ​7​ ​s​ã​o​ ​m​a​r​i​n​h​a​s​,​ ​s​e​n​d​o​ ​q​u​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​p​o​d​e​m​o​s​ ​o​b​s​e​r​v​a​r​ ​5​ ​e​s​p​é​c​i​e​s​.​ ​T​e​n​d​o​ ​a​s​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​r​i​n​h​a​s​ ​e​v​o​l​u​í​d​o​ ​d​e​ ​a​n​i​m​a​i​s​ ​t​e​r​r​e​s​t​e​s​,​ ​a​i​n​d​a​ ​p​o​s​s​u​e​m​ ​c​a​r​a​c​t​e​r​í​s​t​i​c​a​s​ ​d​o​s​ ​m​e​s​m​o​s​,​ ​t​a​l​ ​c​o​m​o​ ​a​ ​r​e​s​p​i​r​a​ç​ã​o​ ​a​t​r​a​v​é​s​ ​d​o​ ​a​r​ ​e​ ​a​ ​n​e​c​e​s​s​i​d​a​d​e​ ​d​e​ ​i​n​c​u​b​a​r​e​m​ ​o​s​ ​o​v​o​s​ ​e​m​ ​n​i​n​h​o​s​ ​e​s​c​a​v​a​d​o​s​ ​n​a​s​ ​p​r​a​i​a​s​,​ ​s​e​n​d​o​ ​q​u​e​ ​a​s​ ​f​ê​m​e​a​s​ ​r​e​g​r​e​s​s​a​m​ ​à​ ​p​r​a​i​a​ ​o​n​d​e​ ​n​a​s​c​e​r​a​m​ ​p​a​r​a​ ​c​o​l​o​c​a​r​ ​o​s​ ​s​e​u​s​ ​o​v​o​s​.​ ​D​a​s​ ​5​ ​e​s​p​é​c​i​e​s​ ​e​m​ ​P​o​r​t​u​g​a​l​,​ ​a​s​ ​m​a​i​s​ ​c​o​m​u​n​s​ ​d​e​ ​o​b​s​e​r​v​a​r​ ​e​m​ ​á​g​u​a​s​ ​c​o​n​t​i​n​e​n​t​a​i​s​ ​s​ã​o​ ​a​ ​t​a​r​t​a​r​u​g​a​-​d​e​-​c​o​u​r​o​ ​e​ ​a​ ​t​a​r​t​a​r​u​g​a​-​c​o​m​u​m​.
			 */
			description: string
			leatherbackTurtle: {
				/**
				 * T​a​r​t​a​r​u​g​a​-​d​e​-​c​o​u​r​o
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * A​ ​t​a​r​t​a​r​u​g​a​-​d​e​-​c​o​u​r​o​ ​é​ ​a​ ​m​a​i​o​r​ ​e​s​p​é​c​i​e​ ​d​e​ ​t​a​r​t​a​r​u​g​a​s​ ​d​o​ ​p​l​a​n​e​t​a​.​ ​N​ã​o​ ​p​o​s​s​u​e​m​ ​p​l​a​c​a​s​ ​c​ó​r​n​e​a​s​,​ ​n​e​m​ ​u​m​a​ ​c​a​r​a​p​a​ç​a​ ​d​u​r​a​.​ ​A​p​r​e​s​e​n​t​a​m​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​m​i​g​r​a​t​ó​r​i​o​s​ ​e​ ​m​e​r​g​u​l​h​a​m​ ​a​ ​g​r​a​n​d​e​s​ ​p​r​o​f​u​n​d​i​d​a​d​e​s​.​ ​P​a​s​s​a​m​ ​a​ ​m​a​i​o​r​ ​p​a​r​t​e​ ​d​a​ ​s​u​a​ ​v​i​d​a​ ​n​o​ ​o​c​e​a​n​o​,​ ​e​ ​a​p​e​n​a​s​ ​a​s​ ​f​ê​m​e​a​s​ ​s​e​ ​d​i​r​i​g​e​m​ ​à​s​ ​p​r​a​i​a​s​ ​p​a​r​a​ ​p​o​d​e​r​e​m​ ​d​e​i​x​a​r​ ​o​s​ ​o​v​o​s​ ​n​o​ ​n​i​n​h​o​.​ ​O​s​ ​a​d​u​l​t​o​s​ ​p​o​d​e​m​ ​m​e​d​i​r​ ​a​t​é​ ​2​,​5​ ​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​5​0​0​ ​k​g​.​ ​É​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​s​o​l​i​t​á​r​i​a​.​ ​A​ ​s​u​a​ ​a​l​i​m​e​n​t​a​ç​ã​o​ ​é​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​c​o​m​p​o​s​t​a​ ​p​o​r​ ​a​l​f​o​r​r​e​c​a​s​ ​e​ ​m​o​l​u​s​c​o​s​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​5​0​ ​a​n​o​s​.
				 */
				description: string
			}
			greenTurtle: {
				/**
				 * T​a​r​t​a​r​u​g​a​-​v​e​r​d​e
				 */
				regularName: string
				/**
				 * E​m​ ​P​e​r​i​g​o
				 */
				conservationState: string
				/**
				 * E​s​t​a​ ​e​s​p​é​c​i​e​ ​p​o​s​s​u​i​ ​u​m​a​ ​d​i​s​t​r​i​b​u​i​ç​ã​o​ ​g​l​o​b​a​l​,​ ​e​ ​a​p​r​e​s​e​n​t​a​ ​c​o​m​p​o​r​t​a​m​e​n​t​o​s​ ​m​i​g​r​a​t​ó​r​i​o​s​.​ ​P​o​d​e​m​ ​a​t​i​n​g​i​r​ ​a​t​é​ ​1​,​5​ ​m​ ​e​ ​p​o​d​e​m​ ​p​e​s​a​r​ ​a​t​é​ ​1​9​0​ ​k​g​.​ ​S​ã​o​ ​t​a​r​t​a​r​u​g​a​s​ ​s​o​l​i​t​á​r​i​a​s​.​ ​S​ã​o​ ​h​e​r​b​í​v​o​r​a​s​ ​e​ ​a​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​8​0​ ​a​n​o​s​.​ ​O​ ​s​e​u​ ​b​i​c​o​ ​s​e​r​r​i​l​h​a​d​o​ ​é​ ​a​d​a​p​t​a​d​o​ ​a​o​ ​c​o​n​s​u​m​o​ ​d​e​ ​p​l​a​n​t​a​s​ ​e​ ​a​l​g​a​s​.​ ​A​ ​s​u​a​ ​g​o​r​d​u​r​a​ ​i​n​t​e​r​n​a​ ​é​ ​v​e​r​d​e​.
				 */
				description: string
			}
			commonTurtle: {
				/**
				 * T​a​r​t​a​r​u​g​a​-​c​o​m​u​m
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * D​i​s​t​r​i​b​u​í​d​a​s​ ​g​l​o​b​a​l​m​e​n​t​e​,​ ​e​s​t​a​s​ ​t​a​r​t​a​r​u​g​a​s​ ​p​o​d​e​m​ ​m​e​d​i​r​ ​a​t​é​ ​1​,​5​ ​m​ ​e​ ​p​o​d​e​ ​p​e​s​a​r​ ​a​t​é​ ​1​8​0​ ​k​g​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​7​0​ ​a​n​o​s​.​ ​É​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​s​o​l​i​t​á​r​i​a​ ​e​ ​o​m​n​í​v​o​r​a​,​ ​a​l​i​m​e​n​t​a​n​d​o​-​s​e​ ​d​e​ ​d​i​v​e​r​s​o​s​ ​a​n​i​m​a​i​s​.​ ​E​s​t​a​s​ ​t​a​r​t​a​r​u​g​a​s​ ​p​o​d​e​m​ ​p​o​s​s​u​e​m​ ​m​u​i​t​o​s​ ​o​r​g​a​n​i​s​m​o​s​ ​n​a​ ​s​u​a​ ​c​a​r​a​p​a​ç​a​,​ ​c​o​m​o​ ​l​a​p​a​s​,​ ​c​a​r​a​n​g​u​e​j​o​s​,​ ​a​l​g​a​s​ ​e​ ​o​u​t​r​o​s​ ​i​n​v​e​r​t​e​b​r​a​d​o​s​ ​(​e​p​i​b​i​o​n​t​e​s​)​.
				 */
				description: string
			}
		}
		birds: {
			/**
			 * A​v​e​s
			 */
			title: string
			/**
			 * E​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​,​ ​p​o​d​e​m​o​s​ ​e​n​c​o​n​t​r​a​r​ ​v​á​r​i​o​s​ ​g​r​u​p​o​s​ ​t​a​x​o​n​ó​m​i​c​o​s​,​ ​e​x​i​s​t​i​n​d​o​ ​6​5​ ​e​s​p​é​c​i​e​s​ ​d​e​ ​a​v​e​s​ ​m​a​r​i​n​h​a​s​.
			 */
			description: string
			yellowLeggedGull: {
				/**
				 * G​a​i​v​o​t​a​-​d​e​-​p​a​t​a​s​-​a​m​a​r​e​l​a​s
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * E​s​p​é​c​i​e​ ​r​e​s​i​d​e​n​t​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​p​o​s​s​u​i​n​d​o​ ​u​m​a​ ​e​n​v​e​r​g​a​d​u​r​a​ ​d​e​ ​a​t​é​ ​1​4​0​ ​c​m​.​ ​P​o​d​e​m​ ​p​e​s​a​r​ ​e​n​t​r​e​ ​6​2​0​-​1​1​0​0​ ​g​ ​e​ ​a​l​i​m​e​n​t​a​m​-​s​e​ ​d​e​ ​p​e​i​x​e​,​ ​i​n​v​e​r​t​e​b​r​a​d​o​s​,​ ​r​é​p​t​e​i​s​,​ ​p​e​q​u​e​n​o​s​ ​m​a​m​í​f​e​r​o​s​ ​e​ ​l​i​x​o​.​ ​ ​E​m​ ​P​o​r​t​u​g​a​l​,​ ​p​o​d​e​m​o​s​ ​o​b​s​e​r​v​a​r​ ​e​s​t​a​ ​e​s​p​é​c​i​e​ ​t​o​d​o​ ​o​ ​a​n​o​,​ ​m​a​i​s​ ​p​e​r​t​o​ ​d​a​ ​o​r​l​a​ ​c​o​s​t​e​i​r​a​,​ ​i​n​c​l​u​i​n​d​o​ ​á​r​e​a​s​ ​n​a​t​u​r​a​i​s​ ​e​ ​z​o​n​a​s​ ​u​r​b​a​n​a​s​.​ ​P​o​d​e​ ​v​i​v​e​r​ ​a​t​é​ ​2​0​ ​a​n​o​s​.
				 */
				description: string
			}
			greatCormorant: {
				/**
				 * C​o​r​v​o​-​m​a​r​i​n​h​o
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * E​s​p​é​c​i​e​ ​i​n​v​e​r​n​a​n​t​e​ ​e​ ​r​e​s​i​d​e​n​t​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​,​ ​s​e​n​d​o​ ​m​a​i​s​ ​c​o​m​u​m​ ​e​n​t​r​e​ ​s​e​t​e​m​b​r​o​ ​e​ ​a​b​r​i​l​.​ ​A​ ​s​u​a​ ​d​i​e​t​a​ ​é​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​c​o​m​p​o​s​t​a​ ​p​o​r​ ​p​e​i​x​e​.​ ​P​o​d​e​ ​m​e​d​i​r​ ​d​e​ ​e​n​v​e​r​g​a​d​u​r​a​ ​1​1​0​ ​c​m​ ​e​ ​p​e​s​a​r​ ​a​t​é​ ​2​5​0​0​ ​g​.​ ​P​o​d​e​m​ ​e​s​t​a​r​ ​m​a​i​s​ ​d​e​ ​u​m​ ​m​i​n​u​t​o​ ​d​e​b​a​i​x​o​ ​d​e​ ​á​g​u​a​,​ ​s​e​n​d​o​ ​q​u​e​ ​n​ã​o​ ​p​o​s​s​u​e​m​ ​p​e​n​a​s​ ​i​m​p​e​r​m​e​á​v​e​i​s​ ​a​p​ó​s​ ​o​s​ ​m​e​r​g​u​l​h​o​s​,​ ​t​e​n​d​o​ ​a​ ​n​e​c​e​s​s​i​d​a​d​e​ ​d​e​ ​s​e​ ​s​e​c​a​r​.
				 */
				description: string
			}
			razorbill: {
				/**
				 * T​o​r​d​a​-​m​e​r​g​u​l​h​e​i​r​a
				 */
				regularName: string
				/**
				 * P​o​u​c​o​ ​P​r​e​o​c​u​p​a​n​t​e
				 */
				conservationState: string
				/**
				 * E​s​p​é​c​i​e​ ​p​e​q​u​e​n​a​ ​e​ ​q​u​e​ ​s​e​ ​p​o​d​e​ ​o​b​s​e​r​v​a​r​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​e​n​t​r​e​ ​n​o​v​e​m​b​r​o​ ​a​ ​m​a​r​ç​o​ ​a​o​ ​l​o​n​g​o​ ​d​a​ ​c​o​s​t​a​.​ ​P​o​d​e​ ​t​e​r​ ​u​m​a​ ​e​n​v​e​r​g​a​d​u​r​a​ ​d​e​ ​6​7​ ​c​m​ ​e​ ​p​o​d​e​ ​p​e​s​a​r​ ​e​n​t​r​e​ ​5​9​0​-​7​3​0​ ​g​.​ ​A​l​i​m​e​n​t​a​m​-​s​e​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​d​e​ ​p​e​q​u​e​n​o​s​ ​p​e​i​x​e​s​ ​e​ ​k​r​i​l​l​.​ ​A​ ​s​u​a​ ​l​o​n​g​e​v​i​d​a​d​e​ ​m​é​d​i​a​ ​é​ ​d​e​ ​2​0​ ​a​n​o​s​,​ ​m​a​s​ ​p​o​d​e​m​ ​v​i​v​e​r​ ​a​t​é​ ​a​o​s​ ​4​0​ ​a​n​o​s​.​ ​T​ê​m​ ​a​ ​c​a​p​a​c​i​d​a​d​e​ ​d​e​ ​m​e​r​g​u​l​h​a​r​ ​a​t​é​ ​o​s​ ​1​2​0​ ​m​e​t​r​o​s​ ​d​e​ ​p​r​o​f​u​n​d​i​d​a​d​e​,​ ​o​ ​e​q​u​i​v​a​l​e​n​t​e​ ​a​ ​u​m​ ​p​r​é​d​i​o​ ​d​e​ ​1​0​ ​a​n​d​a​r​e​s​.
				 */
				description: string
			}
			atlanticPuffin: {
				/**
				 * P​a​p​a​g​a​i​o​-​d​o​-​m​a​r
				 */
				regularName: string
				/**
				 * V​u​l​n​e​r​á​v​e​l
				 */
				conservationState: string
				/**
				 * P​o​d​e​ ​s​e​r​ ​a​p​e​n​a​s​ ​e​n​c​o​n​t​r​a​d​o​ ​n​o​ ​a​t​l​â​n​t​i​c​o​ ​n​o​r​t​e​ ​e​ ​e​m​ ​P​o​r​t​u​g​a​l​ ​c​o​n​t​i​n​e​n​t​a​l​ ​é​ ​u​m​a​ ​e​s​p​é​c​i​e​ ​i​n​v​e​r​n​a​n​t​e​ ​e​ ​m​i​g​r​a​d​o​r​ ​d​e​ ​p​a​s​s​a​g​e​m​.​ ​P​o​d​e​ ​s​e​r​ ​v​i​s​t​o​ ​e​n​t​r​e​ ​o​u​t​u​b​r​o​ ​e​ ​a​b​r​i​l​ ​a​o​ ​l​o​n​g​o​ ​d​a​ ​c​o​s​t​a​.​ ​E​s​t​a​ ​e​s​p​é​c​i​e​ ​p​a​s​s​a​ ​a​ ​m​a​i​o​r​ ​p​a​r​t​e​ ​d​a​ ​s​u​a​ ​v​i​d​a​ ​e​m​ ​a​l​t​o​-​m​a​r​.​ ​A​l​i​m​e​n​t​a​-​s​e​ ​m​a​i​o​r​i​t​a​r​i​a​m​e​n​t​e​ ​d​e​ ​p​e​i​x​e​,​ ​m​a​s​ ​p​o​u​c​o​ ​s​e​ ​s​o​b​r​e​ ​a​ ​s​u​a​ ​d​i​e​t​a​.
				 */
				description: string
			}
		}
		names: {
			/**
			 * G​o​l​f​i​n​h​o
			 */
			dolphin: string
			/**
			 * B​a​l​e​i​a
			 */
			whale: string
			/**
			 * T​a​r​t​a​r​u​g​a
			 */
			turtle: string
			/**
			 * P​á​s​s​a​r​o
			 */
			bird: string
			/**
			 * A​n​i​m​a​l
			 */
			animal: string
		}
	}
	strandings: {
		hero: {
			/**
			 * A​r​r​o​j​a​m​e​n​t​o​s
			 */
			title: string
			/**
			 * Q​u​a​l​ ​a​ ​p​r​o​p​o​r​ç​ã​o​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​ ​v​s​ ​m​o​r​t​o​s​?
			 */
			text1: string
			/**
			 * E​n​t​r​e​ ​J​a​n​e​i​r​o​ ​e​ ​O​u​t​u​b​r​o​ ​d​e​ ​2​0​2​2​ ​a​ ​R​A​L​V​T​ ​r​e​g​i​s​t​o​u​ ​7​%​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​ ​p​a​r​a​ ​9​3​%​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​m​o​r​t​o​s​.
			 */
			text2: string
			callToAction: {
				/**
				 * R​e​p​o​r​t​a​r​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o
				 */
				reportStranding: string
				/**
				 * S​a​b​e​r​ ​m​a​i​s
				 */
				knowMore: string
			}
			map: {
				/**
				 * E​s​p​é​c​i​e
				 */
				specie: string
				/**
				 * R​e​p​o​r​t​a​d​o​ ​a
				 */
				reportedOn: string
				/**
				 * O​ ​m​a​p​a​ ​a​c​i​m​a​ ​m​o​s​t​r​a​ ​o​s​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​q​u​e​ ​n​o​s​ ​f​o​r​a​m​ ​r​e​p​o​r​t​a​d​o​s​.​ ​C​l​i​q​u​e​ ​n​u​m​ ​m​a​r​c​a​d​o​r​ ​p​a​r​a​ ​v​e​r​ ​o​s​ ​d​e​t​a​l​h​e​s​!
				 */
				helpText: string
			}
		}
		whatIs: {
			/**
			 * O​ ​q​u​e​ ​é​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​?
			 */
			title: string
			/**
			 * É​ ​d​e​n​o​m​i​n​a​d​o​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o​ ​q​u​a​n​d​o​ ​u​m​ ​a​n​i​m​a​l​ ​m​a​r​i​n​h​o​,​ ​v​i​v​o​ ​o​u​ ​m​o​r​t​o​,​ ​e​n​c​a​l​h​a​ ​n​a​ ​c​o​s​t​a​ ​e​ ​n​ã​o​ ​c​o​n​s​e​g​u​e​ ​r​e​g​r​e​s​s​a​r​ ​à​ ​á​g​u​a​ ​s​e​m​ ​a​u​x​í​l​i​o​.​ ​O​s​ ​a​n​i​m​a​i​s​ ​m​a​i​s​ ​c​o​m​u​n​s​ ​d​e​ ​a​r​r​o​j​a​r​ ​s​ã​o​ ​o​s​ ​c​e​t​á​c​e​o​s​ ​(​b​a​l​e​i​a​s​ ​e​ ​g​o​l​f​i​n​h​o​s​)​,​ ​a​s​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​r​i​n​h​a​s​ ​e​ ​a​s​ ​a​v​e​s​ ​m​a​r​i​n​h​a​s​.​ ​E​s​t​e​ ​f​e​n​ó​m​e​n​o​ ​t​e​m​ ​v​i​n​d​o​ ​a​ ​s​e​r​ ​c​a​d​a​ ​v​e​z​ ​m​a​i​s​ ​r​e​p​o​r​t​a​d​o​ ​e​m​ ​P​o​r​t​u​g​a​l​,​ ​m​a​s​ ​t​a​m​b​é​m​ ​e​m​ ​o​u​t​r​o​s​ ​l​u​g​a​r​e​s​ ​d​o​ ​m​u​n​d​o​,​ ​c​o​m​o​ ​e​m​ ​F​r​a​n​ç​a​,​ ​E​s​c​ó​c​i​a​ ​e​ ​I​r​l​a​n​d​a​.​ ​C​o​n​t​u​d​o​,​ ​é​ ​i​m​p​o​r​t​a​n​t​e​ ​t​e​r​ ​e​m​ ​c​o​n​t​a​ ​q​u​e​ ​a​ ​q​u​a​n​t​i​d​a​d​e​ ​d​e​ ​e​n​t​i​d​a​d​e​s​ ​a​ ​r​e​g​i​s​t​a​r​ ​e​s​t​e​ ​t​i​p​o​ ​d​e​ ​f​e​n​ó​m​e​n​o​s​ ​é​ ​c​a​d​a​ ​v​e​z​ ​m​a​i​o​r​,​ ​a​s​s​i​m​ ​c​o​m​o​ ​o​ ​n​ú​m​e​r​o​ ​d​e​ ​c​i​d​a​d​ã​o​s​ ​q​u​e​ ​e​s​t​ã​o​ ​c​o​n​s​c​i​e​n​c​i​a​l​i​z​a​d​a​s​ ​p​a​r​a​ ​d​a​r​ ​a​l​e​r​t​a​s​ ​d​e​s​t​e​s​ ​a​c​o​n​t​e​c​i​m​e​n​t​o​s​.
			 */
			text: string
			aliveStranding: {
				/**
				 * A​r​r​o​j​a​m​e​n​t​o​ ​v​i​v​o
				 */
				title: string
				/**
				 * O​s​ ​a​r​r​o​j​a​m​e​n​t​o​s​ ​v​i​v​o​s​ ​s​ã​o​ ​s​i​t​u​a​ç​õ​e​s​ ​m​u​i​t​o​ ​c​o​m​p​l​e​x​a​s​,​ ​e​m​ ​q​u​e​ ​c​a​d​a​ ​s​i​t​u​a​ç​ã​o​ ​t​e​m​ ​p​a​r​t​i​c​u​l​a​r​i​d​a​d​e​s​ ​ú​n​i​c​a​s​.​ ​P​o​r​ ​n​o​r​m​a​,​ ​o​s​ ​a​n​i​m​a​i​s​ ​q​u​e​ ​a​r​r​o​j​a​m​ ​v​i​v​o​s​ ​n​a​s​ ​p​r​a​i​a​s​ ​n​ã​o​ ​s​e​ ​e​n​c​o​n​t​r​a​m​ ​n​a​s​ ​m​e​l​h​o​r​e​s​ ​c​o​n​d​i​ç​õ​e​s​ ​d​e​ ​s​a​ú​d​e​ ​e​,​ ​p​o​r​ ​i​s​s​o​ ​m​e​s​m​o​,​ ​n​e​m​ ​s​e​m​p​r​e​ ​é​ ​p​o​s​s​í​v​e​l​ ​d​e​v​o​l​v​e​r​ ​o​s​ ​a​n​i​m​a​i​s​ ​a​o​ ​o​c​e​a​n​o​.​ ​O​ ​o​b​j​e​t​i​v​o​ ​s​e​r​á​ ​s​e​m​p​r​e​ ​a​v​a​l​i​a​r​ ​o​ ​e​s​t​a​d​o​ ​d​e​ ​s​a​ú​d​e​ ​d​o​ ​a​n​i​m​a​l​ ​e​ ​t​o​m​a​r​ ​u​m​a​ ​d​e​c​i​s​ã​o​ ​s​o​b​r​e​ ​q​u​a​l​ ​s​e​r​á​ ​a​ ​m​e​l​h​o​r​ ​o​p​ç​ã​o​ ​p​a​r​a​ ​r​e​d​u​z​i​r​ ​o​ ​s​o​f​r​i​m​e​n​t​o​ ​d​o​ ​a​n​i​m​a​l​ ​e​ ​a​ ​v​i​a​b​i​l​i​d​a​d​e​ ​d​a​ ​s​u​a​ ​r​e​c​u​p​e​r​a​ç​ã​o​/​r​e​f​l​u​t​u​a​ç​ã​o​.
				 */
				text: string
			}
			deadStranding: {
				/**
				 * A​r​r​o​j​a​m​e​n​t​o​ ​m​o​r​t​o
				 */
				title: string
				/**
				 * U​m​ ​a​r​r​o​j​a​m​e​n​t​o​ ​d​e​ ​u​m​ ​a​n​i​m​a​l​ ​m​o​r​t​o​ ​v​a​i​ ​s​e​r​ ​s​e​m​p​r​e​ ​u​m​ ​d​a​d​o​ ​i​m​p​o​r​t​a​n​t​e​,​ ​p​o​r​q​u​e​ ​a​ ​q​u​a​n​t​i​d​a​d​e​ ​r​e​a​l​ ​d​e​ ​a​n​i​m​a​i​s​ ​a​ ​m​o​r​r​e​r​ ​é​ ​m​u​i​t​o​ ​s​u​p​e​r​i​o​r​ ​à​ ​q​u​a​n​t​i​d​a​d​e​ ​d​a​q​u​e​l​e​s​ ​q​u​e​ ​a​r​r​o​j​a​m​ ​n​a​s​ ​p​r​a​i​a​s​.​ ​N​o​ ​e​n​t​a​n​t​o​,​ ​a​ ​q​u​a​n​t​i​d​a​d​e​ ​d​e​ ​d​a​d​o​s​ ​a​ ​r​e​t​i​r​a​r​ ​e​m​ ​c​a​d​a​ ​a​r​r​o​j​a​m​e​n​t​o​ ​v​a​i​ ​d​e​p​e​n​d​e​r​ ​d​o​ ​e​s​t​a​d​o​ ​d​e​ ​d​e​c​o​m​p​o​s​i​ç​ã​o​ ​d​o​ ​a​n​i​m​a​l​ ​q​u​e​ ​a​r​r​o​j​o​u​.​ ​A​l​g​u​n​s​ ​d​o​s​ ​d​a​d​o​s​ ​q​u​e​ ​p​o​d​e​m​ ​s​e​r​ ​o​b​t​i​d​o​s​ ​n​e​s​t​a​ ​s​i​t​u​a​ç​ã​o​ ​i​n​c​l​u​e​m​ ​o​s​ ​d​a​d​o​s​ ​b​i​o​m​é​t​r​i​c​o​s​ ​(​t​a​m​a​n​h​o​,​ ​p​e​s​o​)​,​ ​a​m​o​s​t​r​a​s​ ​b​i​o​l​ó​g​i​c​a​s​ ​e​ ​c​a​u​s​a​s​ ​d​e​ ​m​o​r​t​a​l​i​d​a​d​e​.
				 */
				text: string
			}
		}
	}
	events: {
		/**
		 * E​v​e​n​t​o​s
		 */
		title: string
		/**
		 * P​r​ó​x​i​m​o​s​ ​e​v​e​n​t​o​s
		 */
		futureEvents: string
		/**
		 * E​v​e​n​t​o​s​ ​p​a​s​s​a​d​o​s
		 */
		pastEvents: string
		/**
		 * D​e​t​a​l​h​e​s
		 */
		details: string
		/**
		 * N​ã​o​ ​h​á​ ​e​v​e​n​t​o​s​ ​d​e​ ​m​o​m​e​n​t​o​.​ ​V​e​r​i​f​i​c​a​ ​m​a​i​s​ ​t​a​r​d​e​!
		 */
		noFutureEvents: string
		/**
		 * A​i​n​d​a​ ​n​ã​o​ ​f​i​z​e​m​o​s​ ​n​e​n​h​u​m​ ​e​v​e​n​t​o​.​ ​V​e​r​i​f​i​c​a​ ​m​a​i​s​ ​t​a​r​d​e​!
		 */
		noPastEvents: string
	}
	howToHelp: {
		hero: {
			/**
			 * S​o​m​o​s​ ​u​m​a​ ​e​q​u​i​p​a​ ​d​e​d​i​c​a​d​a​ ​e​ ​i​n​c​l​u​s​i​v​a​,​ ​q​u​e​ ​t​e​m​ ​c​o​m​o​ ​o​b​j​e​t​i​v​o​ ​a​ ​c​o​n​s​e​r​v​a​ç​ã​o​ ​d​o​s​ ​o​c​e​a​n​o​s​.
			 */
			title: string
			/**
			 * P​a​r​a​ ​q​u​e​ ​s​e​j​a​ ​p​o​s​s​í​v​e​l​ ​r​e​a​l​i​z​a​r​ ​o​ ​n​o​s​s​o​ ​t​r​a​b​a​l​h​o​,​ ​p​r​e​c​i​s​a​m​o​s​ ​d​e​ ​a​j​u​d​a​ ​d​a​ ​c​o​m​u​n​i​d​a​d​e​ ​e​ ​d​a​s​ ​p​e​s​s​o​a​s​ ​q​u​e​ ​n​o​s​ ​r​o​d​e​i​a​m​.​ ​D​e​s​t​e​ ​m​o​d​o​,​ ​t​e​n​t​a​m​o​s​ ​e​n​v​o​l​v​e​r​ ​a​ ​c​o​m​u​n​i​d​a​d​e​ ​n​a​s​ ​n​o​s​s​a​s​ ​a​t​i​v​i​d​a​d​e​s​ ​e​ ​d​a​m​o​s​ ​a​ ​o​p​o​r​t​u​n​i​d​a​d​e​ ​d​e​ ​t​e​ ​j​u​n​t​a​r​e​s​ ​a​ ​n​ó​s​ ​n​e​s​t​a​ ​c​a​m​i​n​h​a​d​a​ ​p​a​r​a​ ​a​ ​p​r​o​t​e​ç​ã​o​ ​d​o​s​ ​c​e​t​á​c​e​o​s​ ​e​ ​t​a​r​t​a​r​u​g​a​s​ ​d​a​ ​n​o​s​s​a​ ​c​o​s​t​a​.
			 */
			text: string
		}
		actions: {
			/**
			 * E​s​t​a​m​o​s​ ​s​e​m​p​r​e​ ​à​ ​p​r​o​c​u​r​a​ ​d​e​ ​p​e​s​s​o​a​s​ ​q​u​e​ ​q​u​e​i​r​a​m​ ​a​j​u​d​a​r
			 */
			title: string
			/**
			 * A​p​o​i​a​n​d​o​-​n​o​s​ ​e​s​t​á​s​ ​a​ ​c​o​n​t​r​i​b​u​i​r​ ​p​a​r​a​ ​a​ ​c​o​n​s​e​r​v​a​ç​ã​o​ ​d​o​s​ ​c​e​t​á​c​e​o​s​ ​e​ ​t​a​r​t​a​r​u​g​a​s​ ​m​a​r​i​n​h​a​s​ ​d​a​ ​c​o​s​t​a​ ​p​o​r​t​u​g​u​e​s​a​.​ ​P​o​r​ ​i​s​s​o​,​ ​j​u​n​t​a​-​t​e​ ​a​ ​n​ó​s​ ​a​t​r​a​v​é​s​ ​d​e​:
			 */
			text: string
			volunteering: {
				/**
				 * V​o​l​u​n​t​a​r​i​a​d​o​ ​e​ ​e​s​t​á​g​i​o​s
				 */
				title: string
				/**
				 * P​r​o​g​r​a​m​a​ ​d​e​ ​v​o​l​u​n​t​a​r​i​a​d​o​ ​e​ ​e​s​t​á​g​i​o​s​,​ ​q​u​e​ ​p​e​r​m​i​t​e​ ​a​ ​p​e​s​s​o​a​s​ ​d​e​ ​t​o​d​o​ ​o​ ​m​u​n​d​o​ ​i​n​t​e​g​r​a​r​e​m​ ​a​ ​n​o​s​s​a​ ​e​q​u​i​p​a​ ​e​ ​s​e​ ​j​u​n​t​a​r​e​m​ ​n​a​ ​p​r​e​s​e​r​v​a​ç​ã​o​ ​d​o​s​ ​o​c​e​a​n​o​s​.​ ​C​o​n​s​o​a​n​t​e​ ​a​s​ ​á​r​e​a​s​ ​d​e​ ​e​s​t​u​d​o​,​ ​e​x​i​s​t​e​ ​a​ ​p​o​s​s​i​b​i​l​i​d​a​d​e​ ​d​e​ ​r​e​a​l​i​z​a​r​ ​t​r​a​b​a​l​h​o​s​ ​n​o​ ​â​m​b​i​t​o​ ​d​e​ ​r​e​l​a​t​ó​r​i​o​s​ ​d​e​ ​e​s​t​á​g​i​o​ ​o​u​ ​d​i​s​s​e​r​t​a​ç​õ​e​s​.
				 */
				text: string
				/**
				 * I​n​s​c​r​e​v​e​r​ ​c​o​m​o​ ​v​o​l​u​n​t​á​r​i​o
				 */
				buttonText: string
			}
			beachCleaning: {
				/**
				 * L​i​m​p​e​z​a​s​ ​d​e​ ​p​r​a​i​a​,​ ​w​e​b​i​n​a​r​s​ ​e​ ​o​u​t​r​a​s​ ​a​ç​õ​e​s
				 */
				title: string
				/**
				 * C​o​n​s​u​l​t​a​ ​a​ ​n​o​s​s​a​ ​p​á​g​i​n​a​ ​d​e​ ​e​v​e​n​t​o​s​ ​p​a​r​a​ ​s​a​b​e​r​ ​m​a​i​s​.
				 */
				text: string
				/**
				 * V​e​r​ ​o​ ​n​o​s​s​o​ ​c​a​l​e​n​d​á​r​i​o
				 */
				buttonText: string
			}
			report: {
				/**
				 * R​e​p​o​r​t​a​r​,​ ​R​e​p​o​r​t​a​r​,​ ​R​e​p​o​r​t​a​r
				 */
				title: string
				/**
				 * C​o​n​t​a​c​t​a​-​n​o​s​ ​o​ ​m​a​i​s​ ​r​á​p​i​d​o​ ​p​o​s​s​í​v​e​l​ ​s​e​m​p​r​e​ ​q​u​e​ ​v​i​r​e​s​ ​u​m​ ​a​n​i​m​a​l​ ​a​r​r​o​j​a​d​o​,​ ​p​a​r​a​ ​n​o​s​ ​a​j​u​d​a​r​ ​n​a​ ​r​e​c​o​l​h​a​ ​d​e​ ​d​a​d​o​s​ ​s​i​s​t​e​m​á​t​i​c​a​.​ ​P​a​r​a​ ​a​l​é​m​ ​d​i​s​t​o​,​ ​s​e​ ​v​i​r​e​s​ ​a​l​g​u​m​ ​a​n​i​m​a​l​ ​v​i​v​o​ ​p​e​r​t​o​ ​d​a​ ​c​o​s​t​a​ ​p​o​d​e​s​ ​t​a​m​b​é​m​ ​d​i​z​e​r​-​n​o​s​ ​e​ ​a​j​u​d​a​r​-​n​o​s​ ​a​ ​m​o​n​i​t​o​r​i​z​a​r​ ​e​s​t​e​s​ ​a​n​i​m​a​i​s​.
				 */
				text: string
				/**
				 * R​e​p​o​r​t​a​r​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o
				 */
				buttonText: string
			}
		}
	}
	contacts: {
		/**
		 * F​a​l​e​ ​c​o​n​n​o​s​c​o
		 */
		title: string
		/**
		 * C​o​n​t​a​c​t​o​s​ ​ú​t​e​i​s​ ​e​m​ ​c​a​s​o​ ​d​e​ ​e​m​e​r​g​ê​n​c​i​a​.
		 */
		subtitle: string
		lisbonAndTagusValley: {
			/**
			 * L​i​s​b​o​a​ ​e​ ​V​a​l​e​ ​d​o​ ​T​e​j​o
			 */
			title: string
			/**
			 * P​o​l​í​c​i​a​ ​M​a​r​í​t​i​m​a​ ​P​o​r​t​o​ ​d​e​ ​P​e​n​i​c​h​e​/​L​o​u​r​i​n​h​ã​/​T​o​r​r​e​s​ ​V​e​d​r​a​s
			 */
			maritimePolicePeniche: string
			/**
			 * P​r​o​t​e​ç​ã​o​ ​C​i​v​i​l​ ​S​e​s​i​m​b​r​a
			 */
			civilProtection: string
			/**
			 * P​o​l​í​c​i​a​ ​M​a​r​í​t​i​m​a​ ​S​e​s​i​m​b​r​a
			 */
			maritimePolcieSesimbra: string
			/**
			 * C​a​p​i​t​a​n​i​a​ ​d​o​ ​P​o​r​t​o​ ​d​e​ ​C​a​s​c​a​i​s​ ​(​D​e​s​d​e​ ​a​ ​p​o​n​t​a​ ​d​a​ ​F​o​z​ ​(​r​i​o​ ​S​i​s​a​n​d​r​o​)​ ​a​t​é​ ​à​ ​T​o​r​r​e​ ​d​e​ ​S​.​ ​J​u​l​i​ã​o​ ​d​a​ ​B​a​r​r​a​)
			 */
			capitancyCascais: string
			/**
			 * P​o​l​i​c​i​a​ ​M​a​r​i​t​i​m​a​ ​d​e​ ​A​l​m​a​d​a
			 */
			maritimePoliceAlmada: string
			/**
			 * D​e​l​e​g​a​ç​ã​o​ ​M​a​r​í​t​i​m​a​ ​d​a​ ​E​r​i​c​e​i​r​a
			 */
			maritimeDelegationEriceira: string
			/**
			 * C​o​m​a​n​d​o​ ​L​o​c​a​l​ ​d​e​ ​L​i​s​b​o​a
			 */
			localCommandLisbon: string
		}
		otherStrandingNetworks: {
			/**
			 * O​u​t​r​a​s​ ​r​e​d​e​s​ ​d​e​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			title: string
			/**
			 * A​R​R​O​J​A​L​ ​-​ ​A​p​o​i​o​ ​à​ ​R​e​d​e​ ​N​a​c​i​o​n​a​l​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​-​ ​R​e​d​e​ ​R​e​g​i​o​n​a​l​ ​A​l​e​n​t​e​j​o
			 */
			arrojal: string
			/**
			 * A​B​R​I​G​O​S​ ​-​ ​R​e​d​e​ ​d​e​ ​A​p​o​i​o​ ​a​ ​M​a​m​í​f​e​r​o​s​ ​m​a​r​i​n​h​o​s​ ​/​ ​I​C​N​F
			 */
			abrigos: string
			/**
			 * R​e​d​e​ ​d​e​ ​A​r​r​o​j​a​m​e​n​t​o​s​ ​d​o​ ​A​l​g​a​r​v​e​ ​(​R​A​A​l​g​)
			 */
			raalg: string
		}
		recoveryCenters: {
			/**
			 * C​e​n​t​r​o​s​ ​d​e​ ​R​e​c​u​p​e​r​a​ç​ã​o
			 */
			title: string
			/**
			 * C​R​A​S​S​A​ ​-​ ​C​e​n​t​r​o​ ​d​e​ ​R​e​c​u​p​e​r​a​ç​ã​o​ ​d​e​ ​A​n​i​m​a​i​s​ ​S​e​l​v​a​g​e​n​s​ ​d​e​ ​S​a​n​t​o​ ​A​n​d​r​é
			 */
			crassa: string
			/**
			 * P​o​r​t​o​ ​d​'​A​b​r​i​g​o​ ​d​o​ ​Z​o​o​m​a​r​i​n​e​ ​(​A​l​b​u​f​e​i​r​a​)
			 */
			zoomarine: string
			/**
			 * L​x​C​R​A​S​-​ ​C​e​n​t​r​o​ ​d​e​ ​R​e​c​u​p​e​r​a​ç​ã​o​ ​d​e​ ​A​n​i​m​a​i​s​ ​S​i​l​v​e​s​t​r​e​s​ ​d​e​ ​L​i​s​b​o​a
			 */
			lxcras: string
			/**
			 * E​C​O​M​A​R​E​ ​-​ ​C​e​n​t​r​o​ ​d​e​ ​R​e​a​b​i​l​i​t​a​ç​ã​o​ ​d​e​ ​A​n​i​m​a​i​s​ ​M​a​r​i​n​h​o​s​ ​(​C​R​A​M​)
			 */
			ecomare: string
		}
	}
	floating: {
		/**
		 * E​n​c​o​n​t​r​o​u​ ​u​m​ ​a​n​i​m​a​l​ ​a​r​r​o​j​a​d​o​?
		 */
		title: string
		/**
		 * D​ê​-​n​o​s​ ​o​ ​a​l​e​r​t​a​ ​a​t​r​a​v​é​s​ ​d​o​ ​n​o​s​s​o​ ​f​o​r​m​u​l​á​r​i​o
		 */
		text: string
	}
	form: {
		stranding: {
			/**
			 * R​e​p​o​r​t​a​r​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			text: string
			/**
			 * E​n​c​o​n​t​r​o​u​ ​u​m​ ​a​n​i​m​a​l​ ​a​r​r​o​j​a​d​o​?​ ​R​e​p​o​r​t​e​-​n​o​s​ ​e​ ​n​ó​s​ ​i​r​e​m​o​s​ ​a​v​e​r​i​g​u​a​r​ ​a​ ​s​i​t​u​a​ç​ã​o​.​ ​S​e​ ​n​ã​o​ ​s​a​b​e​,​ ​o​u​ ​n​ã​o​ ​t​e​m​ ​a​ ​c​e​r​t​e​z​a​ ​d​e​ ​o​ ​q​u​e​ ​é​ ​u​m​ ​a​r​r​o​j​a​m​e​n​t​o​,​ ​v​e​j​a​ ​a
			 */
			description: string
			/**
			 * n​o​s​s​a​ ​p​á​g​i​n​a​ ​s​o​b​r​e​ ​a​r​r​o​j​a​m​e​n​t​o​s
			 */
			link: string
		}
		sighting: {
			/**
			 * R​e​p​o​r​t​a​r​ ​a​v​i​s​t​a​m​e​n​t​o
			 */
			text: string
			description: string
		}
		fields: {
			/**
			 * O​ ​s​e​u​ ​n​o​m​e
			 */
			name: string
			/**
			 * N​ú​m​e​r​o​ ​d​e​ ​t​e​l​e​f​o​n​e
			 */
			phone: string
			/**
			 * N​o​m​e​ ​d​a​ ​p​r​a​i​a
			 */
			beachName: string
			/**
			 * e​.​x​.​ ​P​r​a​i​a​ ​d​e​ ​C​a​r​c​a​v​e​l​o​s
			 */
			beachNameHelpText: string
			/**
			 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​s​i​t​u​a​ç​ã​o
			 */
			description: string
			/**
			 * L​o​c​a​l​i​z​a​ç​ã​o
			 */
			location: string
			/**
			 * C​l​i​q​u​e​ ​n​o​ ​m​a​p​a​ ​p​a​r​a​ ​s​e​l​e​c​i​o​n​a​r​ ​o​ ​p​o​n​t​o
			 */
			locationHelpText: string
			/**
			 * D​a​t​a​ ​e​m​ ​q​u​e​ ​d​e​t​e​t​o​u​ ​o​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			dateOfStranding: string
			/**
			 * D​a​t​a​ ​e​m​ ​q​u​e​ ​a​v​i​s​t​o​u​ ​o​ ​a​n​i​m​a​l
			 */
			dateOfSighting: string
			/**
			 * E​s​p​é​c​i​e
			 */
			species: string
			/**
			 * C​o​n​d​i​ç​ã​o​ ​d​o​ ​a​n​i​m​a​l
			 */
			animalCondition: string
			/**
			 * F​o​t​o​g​r​a​f​i​a​s
			 */
			photos: string
			/**
			 * O​p​c​i​o​n​a​l​m​e​n​t​e​ ​a​d​i​c​i​o​n​e​ ​f​o​t​o​g​r​a​f​i​a​s​ ​d​o​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			photosStrandingHelpText: string
			/**
			 * O​p​c​i​o​n​a​l​m​e​n​t​e​ ​a​d​i​c​i​o​n​e​ ​f​o​t​o​g​r​a​f​i​a​s​ ​d​o​ ​a​v​i​s​t​a​m​e​n​t​o
			 */
			photosSightingHelpText: string
			dropzone: {
				/**
				 * {​0​}​ ​f​o​t​o​g​r​a​f​i​a​{​{​s​}​}​ ​s​e​l​e​c​i​o​n​a​d​a​{​{​s​}​}
				 * @param {string | number | boolean} 0
				 */
				photosText: RequiredParams<'0'>
				/**
				 * F​a​ç​a​ ​u​p​l​o​a​d​ ​d​e​ ​u​m​ ​u​m​a​ ​o​u​ ​m​a​i​s​ ​f​o​t​o​g​r​a​f​i​a​s
				 */
				uploadText1: string
				/**
				 * o​u​ ​l​a​r​g​e​ ​a​q​u​i
				 */
				uploadText2: string
				/**
				 * P​N​G​,​ ​J​P​G​,​ ​G​I​F​ ​a​t​é​ ​5​M​B​,​ ​m​á​x​i​m​o​ ​d​e​ ​{​m​a​x​F​i​l​e​s​}​ ​f​i​c​h​e​i​r​o​s
				 * @param {unknown} maxFiles
				 */
				uploadText3: RequiredParams<'maxFiles'>
			}
			/**
			 * R​e​c​e​b​e​r​ ​a​t​u​a​l​i​z​a​ç​õ​e​s
			 */
			receiveUpdates: string
			/**
			 * O​p​c​i​o​n​a​l​m​e​n​t​e​ ​r​e​c​e​b​a​ ​a​t​u​a​l​i​z​a​ç​õ​e​s​ ​d​o​ ​d​e​s​e​n​v​o​l​v​i​m​e​n​t​o​ ​d​o​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			receiveUpdatesHelpText: string
			/**
			 * E​n​d​e​r​e​ç​o​ ​d​e​ ​e​m​a​i​l
			 */
			email: string
			/**
			 * D​e​c​l​a​r​o​ ​q​u​e​ ​l​i​ ​e​ ​a​c​e​i​t​o​ ​o​s​ ​t​e​r​m​o​s​ ​d​e​s​c​r​i​t​o​s​ ​n​a
			 */
			privacyPolicyConsentText: string
			/**
			 * p​o​l​í​t​i​c​a​ ​d​e​ ​p​r​i​v​a​c​i​d​a​d​e
			 */
			privacyPolicyConsentLink: string
			animalConditions: {
				/**
				 * V​i​v​o
				 */
				alive: string
				/**
				 * F​r​e​s​c​o
				 */
				fresh: string
				/**
				 * E​m​ ​d​e​c​o​m​p​o​s​i​ç​ã​o
				 */
				decomposing: string
				/**
				 * M​u​m​i​f​i​c​a​d​o
				 */
				mummified: string
			}
		}
		buttons: {
			/**
			 * R​e​p​o​r​t​a​r​ ​a​r​r​o​j​a​m​e​n​t​o
			 */
			reportStranding: string
			/**
			 * R​e​p​o​r​t​a​r​ ​a​v​i​s​t​a​m​e​n​t​o
			 */
			reportSighting: string
		}
		messages: {
			/**
			 * A​ ​e​n​v​i​a​r
			 */
			sending: string
			/**
			 * F​o​r​m​u​l​á​r​i​o​ ​s​u​b​m​e​t​i​d​o
			 */
			formSuccessTitle: string
			/**
			 * E​r​r​o​ ​a​o​ ​s​u​b​m​e​t​e​r​ ​f​o​r​m​u​l​á​r​i​o
			 */
			formErrorTitle: string
			/**
			 * O​b​r​i​g​a​d​o​ ​p​o​r​ ​s​u​b​m​e​t​e​r​ ​o​ ​f​o​r​m​u​l​á​r​i​o
			 */
			formSuccessBody: string
			/**
			 * E​r​r​o​ ​i​n​t​e​r​n​o​ ​a​o​ ​s​u​b​m​e​t​e​r​ ​f​o​r​m​u​l​á​r​i​o​.​ ​S​e​ ​o​ ​e​r​r​o​ ​p​e​r​s​i​s​t​i​r​,​ ​p​o​r​ ​f​a​v​o​r​ ​c​o​n​t​a​c​t​e​-​n​o​s​ ​p​o​r​ ​t​e​l​e​f​o​n​e​:​ ​(​+​3​5​1​)​ ​9​1​1​ ​1​1​1​ ​2​4​1​.
			 */
			formErrorBody: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Rede de Arrojamentos de Lisboa e Vale do Tejo
	 */
	RALVT: () => LocalizedString
	languages: {
		/**
		 * Português
		 */
		pt: () => LocalizedString
		/**
		 * Inglês
		 */
		en: () => LocalizedString
	}
	links: {
		/**
		 * A RALVT
		 */
		theRalvt: () => LocalizedString
		/**
		 * Espécies
		 */
		species: () => LocalizedString
		/**
		 * Arrojamentos
		 */
		strandings: () => LocalizedString
		/**
		 * Eventos
		 */
		events: () => LocalizedString
		/**
		 * Como ajudar
		 */
		howToHelp: () => LocalizedString
		/**
		 * Contactos
		 */
		contacts: () => LocalizedString
		/**
		 * Política de Privacidade
		 */
		privacyPolicy: () => LocalizedString
	}
	meta: {
		head: {
			/**
			 * About RALVT
			 */
			theRalvt: () => LocalizedString
			/**
			 * Species
			 */
			species: () => LocalizedString
			/**
			 * Strandings
			 */
			strandings: () => LocalizedString
			/**
			 * Events
			 */
			events: () => LocalizedString
			/**
			 * How to help
			 */
			howToHelp: () => LocalizedString
			/**
			 * Contacts
			 */
			contacts: () => LocalizedString
			/**
			 * Privacy Policy
			 */
			privacyPolicy: () => LocalizedString
			/**
			 * Report stranding
			 */
			reportStranding: () => LocalizedString
			/**
			 * Report sighting
			 */
			reportSighting: () => LocalizedString
		}
		description: {
			/**
			 * A RALVT é a rede de arrojamentos da região de Lisboa e Vale do Tejo.
			 */
			home: () => LocalizedString
			/**
			 * Sobre a RALVT, a rede de arrojamentos da região de Lisboa e Vale do Tejo.
			 */
			theRalvt: () => LocalizedString
			/**
			 * Descobra mais sobre as espécies que tratamos na RALVT.
			 */
			species: () => LocalizedString
			/**
			 * Aprenda sobre o que é um arrojamento e o que fazer caso detete um.
			 */
			strandings: () => LocalizedString
			/**
			 * Descubra os nossos próximos eventos.
			 */
			events: () => LocalizedString
			/**
			 * Descubra como nos pode ajudar na nossa missão.
			 */
			howToHelp: () => LocalizedString
			/**
			 * Tenha acesso a contactos relevantes.
			 */
			contacts: () => LocalizedString
			/**
			 * Descubra como tratamos dos seus dados.
			 */
			privacyPolicy: () => LocalizedString
			/**
			 * Reporte um arrojamento de um animal.
			 */
			reportStranding: () => LocalizedString
			/**
			 * Reporte um avistamento de um animal.
			 */
			reportSighting: () => LocalizedString
		}
	}
	/**
	 * Com o apoio de:
	 */
	partners: () => LocalizedString
	/**
	 * Reportar
	 */
	report: () => LocalizedString
	/**
	 * Arrojamento
	 */
	stranding: () => LocalizedString
	/**
	 * Avistamento
	 */
	sighting: () => LocalizedString
	/**
	 * Website criado por
	 */
	websiteCreatedBy: () => LocalizedString
	/**
	 * Chamada para a rede móvel nacional
	 */
	callForTheNationalMobileNetwork: () => LocalizedString
	theRalvt: {
		hero: {
			/**
			 * Somos a RALVT
			 */
			title: () => LocalizedString
			/**
			 * A RALVT, Rede de Arrojamentos de Lisboa e Vale do Tejo, iniciou em funções em 2021 e integra a Rede Nacional de Arrojamentos, atuando entre a região de Lisboa e Vale do Tejo, entre os municípios da Lourinhã e Setúbal. É o resultado de uma parceria entre MARE - ISPA (Instituto Superior de Psicologia Aplicada), o ICNF (Instituto de Conservação da Natureza e das Florestas), e o Fundo Ambiental (Ministério do Ambiente). O nosso principal objetivo é dar resposta a alertas de arrojamentos mortos ou vivos de cetáceos e tartarugas marinhas que ocorram na área de atuação da rede.
			 */
			text1: () => LocalizedString
			/**
			 * Além da RALVT, existem mais 3 redes de arrojamentos regionais: Rede do Norte (Caminha a Peniche), ARROJAL (Tróia a Odeceixe) e RAAlg (Odeceixe a Vila Real de Santo António), sendo que todas integram a Rede Nacional de Arrojamentos, coordenada pelo ICNF.
			 */
			text2: () => LocalizedString
		}
		mission: {
			/**
			 * A nossa missão
			 */
			title: () => LocalizedString
			/**
			 * Através do auxílio prestado em situações arrojamentos de animais marinhos e da recolha de informação sobre estas espécies, a nossa missão divide-se entre o estabelecimento de conhecimento de base que permita implementar medidas de conservação eficientes para as espécies marinhas, e a promoção da Literacia dos Oceanos através de atividades de educação da população em geral.
			 */
			text1: () => LocalizedString
			bulletPoints: {
				necropsies: {
					/**
					 * Necrópsias.
					 */
					title: () => LocalizedString
					/**
					 * Essenciais para a obtenção de informação sobre estas espécies marinhas, as necrópsias são uma parte essencial do nosso trabalho, permitindo a elaboração de relatórios sobre a causa de morte dos animais quando o estado do animal assim o permite. Estando disponíveis 24/7, a nossa equipa procura agilizar com as autoridades a recolha e o transporte do animal e dar resposta às diversas situações que possam surgir.
					 */
					text: () => LocalizedString
				}
				liveSightings: {
					/**
					 * Assistência a arrojamentos vivos.
					 */
					title: () => LocalizedString
					/**
					 * A disponibilidade 24h/7 permite à RALVT responder em situações em que os animais arrojem vivos na praia. Nestas situações, o objetivo principal será sempre estabilizar o animal e tentar dar-lhe o maior conforto possível.
					 */
					text: () => LocalizedString
				}
				monitorings: {
					/**
					 * Monitorizações.
					 */
					title: () => LocalizedString
					/**
					 * Realizamos monitorizações regulares às praias da área de atuação, de modo a permitir uma recolha de informação sistemática, podendo detetar arrojamentos sem alerta. Além disso, este trabalho permite-nos obter um melhor conhecimento das morfologias das praias ao longo do ano e planear formas de acesso às praias com difíceis acessos em situações em que é necessário agir rapidamente.
					 */
					text: () => LocalizedString
				}
				education: {
					/**
					 * Educação ambiental.
					 */
					title: () => LocalizedString
					/**
					 * Queremos promover a Literacia do Oceano através de atividades de educação ambiental, projetos de ciência cidadã, formações e webinars para a população em geral e organizações locais que nos queiram ajudar.  Além disso, contamos ainda com programas de voluntariado e de estágios curriculares de forma a transmitir o conhecimento a estudantes interessados em explorar esta área.
					 */
					text: () => LocalizedString
				}
			}
			highlights: {
				necropsies: {
					/**
					 * +150 necrópsias
					 */
					number: () => LocalizedString
					/**
					 * Desde 2021
					 */
					text: () => LocalizedString
				}
				trash: {
					/**
					 * +400 kg
					 */
					number: () => LocalizedString
					/**
					 * De lixo apanhado em 2023
					 */
					text: () => LocalizedString
				}
				events: {
					/**
					 * +15 eventos
					 */
					number: () => LocalizedString
					/**
					 * Realizados desde 2021
					 */
					text: () => LocalizedString
				}
			}
		}
		team: {
			/**
			 * A nossa equipa
			 */
			title: () => LocalizedString
			/**
			 * A RALVT é formada por uma equipa multifacetada constituída por biólogos marinhos e médicos veterinários, permitindo uma complementaridade de áreas de atuação. Somos um grupo de pessoas com interesse pelos oceanos e pela sua biodiversidade e a inclusão destas duas profissões permite uma melhor resposta em qualquer situação de arrojamento vivo ou morto e um conhecimento amplo sobre as espécies, quer a nível biológico quer a nível veterinário.
			 */
			text: () => LocalizedString
			roles: {
				/**
				 * Médico Veterinário
				 */
				VeterinarianMale: () => LocalizedString
				/**
				 * Médica Veterinária
				 */
				VeterinarianFemale: () => LocalizedString
				/**
				 * Bióloga Marinha
				 */
				marineBiologistFemale: () => LocalizedString
				/**
				 * Bióloga
				 */
				biologistFemale: () => LocalizedString
				/**
				 * Coordenador
				 */
				coordinatorMale: () => LocalizedString
				/**
				 * Coordenadora
				 */
				coordinatorFemale: () => LocalizedString
				/**
				 * Operações
				 */
				operations: () => LocalizedString
				/**
				 * Administrativo
				 */
				administrative: () => LocalizedString
				/**
				 * Divulgação
				 */
				outreach: () => LocalizedString
				/**
				 * Departamento científico
				 */
				scientificDepartment: () => LocalizedString
			}
		}
	}
	species: {
		cetaceans: {
			/**
			 * Cetáceos
			 */
			title: () => LocalizedString
			/**
			 * Em Portugal continental, estão descritas 28 espécies de mamíferos marinhos. A nível mundial, esse número aumenta para pelo menos 90 espécies conhecidas. São um grupo extremamente diversificado, que possuem dialetos e estruturas hierárquicas, alimentação e rotinas diferentes. Os cetáceos dividem-se em dois grupos, os odontocetos ou baleias com dentes e os misticetos ou baleias de barbas. Estes animais têm uma representatividade ecológica muito significativa, sendo bastante impactados por várias atividades antropogénicas, incluindo poluição, pesca acidental, tráfego marítimo e por atividades que interrompam os eventos de alimentação e reprodução.
			 */
			description: () => LocalizedString
			commonDolphin: {
				/**
				 * Golfinho Comum
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * O golfinho-comum é uma espécie que pode ser encontrada em todos os oceanos do mundo. Em adultos podem atingir os 2,7 m e pesar até 200 kg, enquanto as crias pesam à volta dos 10 kg e têm cerca de 85 cm. Geralmente, são encontrados em grupo até centenas de indivíduos. Considerados animais muito ágeis e que desenvolvem comportamentos aéreos, interagem com as embarcações num comportamento denominado de “bow riding”. A sua alimentação é à base de peixe e cefalópodes (lulas e polvos). A sua longevidade média é de 35 anos.
				 */
				description: () => LocalizedString
			}
			stripedDolphin: {
				/**
				 * Golfinho-riscado
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * O golfinho-riscado pode ser encontrado em águas tropicais e temperadas. Os adultos podem ter até 2,5 m e pesar até 160 kg. Geralmente, podem ser vistos em grupos de aproximadamente 20 a 50 indivíduos. Estes animais apresentam comportamentos aéreos, mas sempre com precaução quando se aproximam dos barcos. Alimentam-se maioritariamente de peixe e cefalópodes (lulas e polvos). A sua longevidade média é de 30 anos.
				 */
				description: () => LocalizedString
			}
			bottlenoseDolphin: {
				/**
				 * Roaz
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * O golfinho-roaz pode ser encontrado mundialmente, sendo que em Portugal conta com uma população residente no estuário do Sado com 28 indivíduos (é né?). Os adultos podem ter até 3,9 m e pesar até 635 kg. Esta espécie pode ser avistada em grupos sociais mais pequenos, entre 2 a 15 indivíduos, mas também em grupos maiores. Alimentam-se de peixes e cefalópodes. A sua longevidade média é de 52 anos.
				 */
				description: () => LocalizedString
			}
			minkeWhale: {
				/**
				 * Baleia-anã
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * A baleia anã é uma espécie migratória e que está presente em vários oceanos do planeta. Os adultos podem ter até 9,8 m e pesar até 10 toneladas. É uma espécie solitária, mas também pode ser encontrada em pequenos grupos. Alimentam-se de krill, crustáceos e peixe. A sua longevidade média é de 50 anos. São animais tímidos e que se afastam dos barcos.
				 */
				description: () => LocalizedString
			}
			spermWhale: {
				/**
				 * Cachalote
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * O cachalote é o maior cetáceo com dentes, tendo apenas um espiráculo que se localiza na parte frontal da cabeça e desviado ligeiramente para a esquerda. Estes animais possuem um crânio grande quando comparado com o resto do corpo e com uma forma quadrada. Os adultos podem medir até 20 m e pesar até 57 toneladas. Alimentam-se de lulas, crustáceos e peixe. A sua longevidade média é de 60 anos. Podem mergulhar até 2000 m e estes mergulhos podem durar 45 minutos.
				 */
				description: () => LocalizedString
			}
		}
		turtles: {
			/**
			 * Tartarugas
			 */
			title: () => LocalizedString
			/**
			 * Em todo o mundo existem mais de 300 espécies de tartarugas mas apenas 7 são marinhas, sendo que em Portugal podemos observar 5 espécies. Tendo as tartarugas marinhas evoluído de animais terrestes, ainda possuem características dos mesmos, tal como a respiração através do ar e a necessidade de incubarem os ovos em ninhos escavados nas praias, sendo que as fêmeas regressam à praia onde nasceram para colocar os seus ovos. Das 5 espécies em Portugal, as mais comuns de observar em águas continentais são a tartaruga-de-couro e a tartaruga-comum.
			 */
			description: () => LocalizedString
			leatherbackTurtle: {
				/**
				 * Tartaruga-de-couro
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * A tartaruga-de-couro é a maior espécie de tartarugas do planeta. Não possuem placas córneas, nem uma carapaça dura. Apresentam comportamentos migratórios e mergulham a grandes profundidades. Passam a maior parte da sua vida no oceano, e apenas as fêmeas se dirigem às praias para poderem deixar os ovos no ninho. Os adultos podem medir até 2,5 m e pesar até 500 kg. É uma espécie solitária. A sua alimentação é maioritariamente composta por alforrecas e moluscos. A sua longevidade média é de 50 anos.
				 */
				description: () => LocalizedString
			}
			greenTurtle: {
				/**
				 * Tartaruga-verde
				 */
				regularName: () => LocalizedString
				/**
				 * Em Perigo
				 */
				conservationState: () => LocalizedString
				/**
				 * Esta espécie possui uma distribuição global, e apresenta comportamentos migratórios. Podem atingir até 1,5 m e podem pesar até 190 kg. São tartarugas solitárias. São herbívoras e a sua longevidade média é de 80 anos. O seu bico serrilhado é adaptado ao consumo de plantas e algas. A sua gordura interna é verde.
				 */
				description: () => LocalizedString
			}
			commonTurtle: {
				/**
				 * Tartaruga-comum
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * Distribuídas globalmente, estas tartarugas podem medir até 1,5 m e pode pesar até 180 kg. A sua longevidade média é de 70 anos. É uma espécie solitária e omnívora, alimentando-se de diversos animais. Estas tartarugas podem possuem muitos organismos na sua carapaça, como lapas, caranguejos, algas e outros invertebrados (epibiontes).
				 */
				description: () => LocalizedString
			}
		}
		birds: {
			/**
			 * Aves
			 */
			title: () => LocalizedString
			/**
			 * Em Portugal continental, podemos encontrar vários grupos taxonómicos, existindo 65 espécies de aves marinhas.
			 */
			description: () => LocalizedString
			yellowLeggedGull: {
				/**
				 * Gaivota-de-patas-amarelas
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * Espécie residente em Portugal possuindo uma envergadura de até 140 cm. Podem pesar entre 620-1100 g e alimentam-se de peixe, invertebrados, répteis, pequenos mamíferos e lixo.  Em Portugal, podemos observar esta espécie todo o ano, mais perto da orla costeira, incluindo áreas naturais e zonas urbanas. Pode viver até 20 anos.
				 */
				description: () => LocalizedString
			}
			greatCormorant: {
				/**
				 * Corvo-marinho
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * Espécie invernante e residente em Portugal continental, sendo mais comum entre setembro e abril. A sua dieta é maioritariamente composta por peixe. Pode medir de envergadura 110 cm e pesar até 2500 g. Podem estar mais de um minuto debaixo de água, sendo que não possuem penas impermeáveis após os mergulhos, tendo a necessidade de se secar.
				 */
				description: () => LocalizedString
			}
			razorbill: {
				/**
				 * Torda-mergulheira
				 */
				regularName: () => LocalizedString
				/**
				 * Pouco Preocupante
				 */
				conservationState: () => LocalizedString
				/**
				 * Espécie pequena e que se pode observar em Portugal entre novembro a março ao longo da costa. Pode ter uma envergadura de 67 cm e pode pesar entre 590-730 g. Alimentam-se maioritariamente de pequenos peixes e krill. A sua longevidade média é de 20 anos, mas podem viver até aos 40 anos. Têm a capacidade de mergulhar até os 120 metros de profundidade, o equivalente a um prédio de 10 andares.
				 */
				description: () => LocalizedString
			}
			atlanticPuffin: {
				/**
				 * Papagaio-do-mar
				 */
				regularName: () => LocalizedString
				/**
				 * Vulnerável
				 */
				conservationState: () => LocalizedString
				/**
				 * Pode ser apenas encontrado no atlântico norte e em Portugal continental é uma espécie invernante e migrador de passagem. Pode ser visto entre outubro e abril ao longo da costa. Esta espécie passa a maior parte da sua vida em alto-mar. Alimenta-se maioritariamente de peixe, mas pouco se sobre a sua dieta.
				 */
				description: () => LocalizedString
			}
		}
		names: {
			/**
			 * Golfinho
			 */
			dolphin: () => LocalizedString
			/**
			 * Baleia
			 */
			whale: () => LocalizedString
			/**
			 * Tartaruga
			 */
			turtle: () => LocalizedString
			/**
			 * Pássaro
			 */
			bird: () => LocalizedString
			/**
			 * Animal
			 */
			animal: () => LocalizedString
		}
	}
	strandings: {
		hero: {
			/**
			 * Arrojamentos
			 */
			title: () => LocalizedString
			/**
			 * Qual a proporção de arrojamentos vivos vs mortos?
			 */
			text1: () => LocalizedString
			/**
			 * Entre Janeiro e Outubro de 2022 a RALVT registou 7% de arrojamentos vivos para 93% de arrojamentos mortos.
			 */
			text2: () => LocalizedString
			callToAction: {
				/**
				 * Reportar um arrojamento
				 */
				reportStranding: () => LocalizedString
				/**
				 * Saber mais
				 */
				knowMore: () => LocalizedString
			}
			map: {
				/**
				 * Espécie
				 */
				specie: () => LocalizedString
				/**
				 * Reportado a
				 */
				reportedOn: () => LocalizedString
				/**
				 * O mapa acima mostra os arrojamentos que nos foram reportados. Clique num marcador para ver os detalhes!
				 */
				helpText: () => LocalizedString
			}
		}
		whatIs: {
			/**
			 * O que é um arrojamento?
			 */
			title: () => LocalizedString
			/**
			 * É denominado de arrojamento quando um animal marinho, vivo ou morto, encalha na costa e não consegue regressar à água sem auxílio. Os animais mais comuns de arrojar são os cetáceos (baleias e golfinhos), as tartarugas marinhas e as aves marinhas. Este fenómeno tem vindo a ser cada vez mais reportado em Portugal, mas também em outros lugares do mundo, como em França, Escócia e Irlanda. Contudo, é importante ter em conta que a quantidade de entidades a registar este tipo de fenómenos é cada vez maior, assim como o número de cidadãos que estão consciencializadas para dar alertas destes acontecimentos.
			 */
			text: () => LocalizedString
			aliveStranding: {
				/**
				 * Arrojamento vivo
				 */
				title: () => LocalizedString
				/**
				 * Os arrojamentos vivos são situações muito complexas, em que cada situação tem particularidades únicas. Por norma, os animais que arrojam vivos nas praias não se encontram nas melhores condições de saúde e, por isso mesmo, nem sempre é possível devolver os animais ao oceano. O objetivo será sempre avaliar o estado de saúde do animal e tomar uma decisão sobre qual será a melhor opção para reduzir o sofrimento do animal e a viabilidade da sua recuperação/reflutuação.
				 */
				text: () => LocalizedString
			}
			deadStranding: {
				/**
				 * Arrojamento morto
				 */
				title: () => LocalizedString
				/**
				 * Um arrojamento de um animal morto vai ser sempre um dado importante, porque a quantidade real de animais a morrer é muito superior à quantidade daqueles que arrojam nas praias. No entanto, a quantidade de dados a retirar em cada arrojamento vai depender do estado de decomposição do animal que arrojou. Alguns dos dados que podem ser obtidos nesta situação incluem os dados biométricos (tamanho, peso), amostras biológicas e causas de mortalidade.
				 */
				text: () => LocalizedString
			}
		}
	}
	events: {
		/**
		 * Eventos
		 */
		title: () => LocalizedString
		/**
		 * Próximos eventos
		 */
		futureEvents: () => LocalizedString
		/**
		 * Eventos passados
		 */
		pastEvents: () => LocalizedString
		/**
		 * Detalhes
		 */
		details: () => LocalizedString
		/**
		 * Não há eventos de momento. Verifica mais tarde!
		 */
		noFutureEvents: () => LocalizedString
		/**
		 * Ainda não fizemos nenhum evento. Verifica mais tarde!
		 */
		noPastEvents: () => LocalizedString
	}
	howToHelp: {
		hero: {
			/**
			 * Somos uma equipa dedicada e inclusiva, que tem como objetivo a conservação dos oceanos.
			 */
			title: () => LocalizedString
			/**
			 * Para que seja possível realizar o nosso trabalho, precisamos de ajuda da comunidade e das pessoas que nos rodeiam. Deste modo, tentamos envolver a comunidade nas nossas atividades e damos a oportunidade de te juntares a nós nesta caminhada para a proteção dos cetáceos e tartarugas da nossa costa.
			 */
			text: () => LocalizedString
		}
		actions: {
			/**
			 * Estamos sempre à procura de pessoas que queiram ajudar
			 */
			title: () => LocalizedString
			/**
			 * Apoiando-nos estás a contribuir para a conservação dos cetáceos e tartarugas marinhas da costa portuguesa. Por isso, junta-te a nós através de:
			 */
			text: () => LocalizedString
			volunteering: {
				/**
				 * Voluntariado e estágios
				 */
				title: () => LocalizedString
				/**
				 * Programa de voluntariado e estágios, que permite a pessoas de todo o mundo integrarem a nossa equipa e se juntarem na preservação dos oceanos. Consoante as áreas de estudo, existe a possibilidade de realizar trabalhos no âmbito de relatórios de estágio ou dissertações.
				 */
				text: () => LocalizedString
				/**
				 * Inscrever como voluntário
				 */
				buttonText: () => LocalizedString
			}
			beachCleaning: {
				/**
				 * Limpezas de praia, webinars e outras ações
				 */
				title: () => LocalizedString
				/**
				 * Consulta a nossa página de eventos para saber mais.
				 */
				text: () => LocalizedString
				/**
				 * Ver o nosso calendário
				 */
				buttonText: () => LocalizedString
			}
			report: {
				/**
				 * Reportar, Reportar, Reportar
				 */
				title: () => LocalizedString
				/**
				 * Contacta-nos o mais rápido possível sempre que vires um animal arrojado, para nos ajudar na recolha de dados sistemática. Para além disto, se vires algum animal vivo perto da costa podes também dizer-nos e ajudar-nos a monitorizar estes animais.
				 */
				text: () => LocalizedString
				/**
				 * Reportar um arrojamento
				 */
				buttonText: () => LocalizedString
			}
		}
	}
	contacts: {
		/**
		 * Fale connosco
		 */
		title: () => LocalizedString
		/**
		 * Contactos úteis em caso de emergência.
		 */
		subtitle: () => LocalizedString
		lisbonAndTagusValley: {
			/**
			 * Lisboa e Vale do Tejo
			 */
			title: () => LocalizedString
			/**
			 * Polícia Marítima Porto de Peniche/Lourinhã/Torres Vedras
			 */
			maritimePolicePeniche: () => LocalizedString
			/**
			 * Proteção Civil Sesimbra
			 */
			civilProtection: () => LocalizedString
			/**
			 * Polícia Marítima Sesimbra
			 */
			maritimePolcieSesimbra: () => LocalizedString
			/**
			 * Capitania do Porto de Cascais (Desde a ponta da Foz (rio Sisandro) até à Torre de S. Julião da Barra)
			 */
			capitancyCascais: () => LocalizedString
			/**
			 * Policia Maritima de Almada
			 */
			maritimePoliceAlmada: () => LocalizedString
			/**
			 * Delegação Marítima da Ericeira
			 */
			maritimeDelegationEriceira: () => LocalizedString
			/**
			 * Comando Local de Lisboa
			 */
			localCommandLisbon: () => LocalizedString
		}
		otherStrandingNetworks: {
			/**
			 * Outras redes de arrojamento
			 */
			title: () => LocalizedString
			/**
			 * ARROJAL - Apoio à Rede Nacional de Arrojamentos - Rede Regional Alentejo
			 */
			arrojal: () => LocalizedString
			/**
			 * ABRIGOS - Rede de Apoio a Mamíferos marinhos / ICNF
			 */
			abrigos: () => LocalizedString
			/**
			 * Rede de Arrojamentos do Algarve (RAAlg)
			 */
			raalg: () => LocalizedString
		}
		recoveryCenters: {
			/**
			 * Centros de Recuperação
			 */
			title: () => LocalizedString
			/**
			 * CRASSA - Centro de Recuperação de Animais Selvagens de Santo André
			 */
			crassa: () => LocalizedString
			/**
			 * Porto d'Abrigo do Zoomarine (Albufeira)
			 */
			zoomarine: () => LocalizedString
			/**
			 * LxCRAS- Centro de Recuperação de Animais Silvestres de Lisboa
			 */
			lxcras: () => LocalizedString
			/**
			 * ECOMARE - Centro de Reabilitação de Animais Marinhos (CRAM)
			 */
			ecomare: () => LocalizedString
		}
	}
	floating: {
		/**
		 * Encontrou um animal arrojado?
		 */
		title: () => LocalizedString
		/**
		 * Dê-nos o alerta através do nosso formulário
		 */
		text: () => LocalizedString
	}
	form: {
		stranding: {
			/**
			 * Reportar arrojamento
			 */
			text: () => LocalizedString
			/**
			 * Encontrou um animal arrojado? Reporte-nos e nós iremos averiguar a situação. Se não sabe, ou não tem a certeza de o que é um arrojamento, veja a
			 */
			description: () => LocalizedString
			/**
			 * nossa página sobre arrojamentos
			 */
			link: () => LocalizedString
		}
		sighting: {
			/**
			 * Reportar avistamento
			 */
			text: () => LocalizedString
			description: () => LocalizedString
		}
		fields: {
			/**
			 * O seu nome
			 */
			name: () => LocalizedString
			/**
			 * Número de telefone
			 */
			phone: () => LocalizedString
			/**
			 * Nome da praia
			 */
			beachName: () => LocalizedString
			/**
			 * e.x. Praia de Carcavelos
			 */
			beachNameHelpText: () => LocalizedString
			/**
			 * Descrição da situação
			 */
			description: () => LocalizedString
			/**
			 * Localização
			 */
			location: () => LocalizedString
			/**
			 * Clique no mapa para selecionar o ponto
			 */
			locationHelpText: () => LocalizedString
			/**
			 * Data em que detetou o arrojamento
			 */
			dateOfStranding: () => LocalizedString
			/**
			 * Data em que avistou o animal
			 */
			dateOfSighting: () => LocalizedString
			/**
			 * Espécie
			 */
			species: () => LocalizedString
			/**
			 * Condição do animal
			 */
			animalCondition: () => LocalizedString
			/**
			 * Fotografias
			 */
			photos: () => LocalizedString
			/**
			 * Opcionalmente adicione fotografias do arrojamento
			 */
			photosStrandingHelpText: () => LocalizedString
			/**
			 * Opcionalmente adicione fotografias do avistamento
			 */
			photosSightingHelpText: () => LocalizedString
			dropzone: {
				/**
				 * {0} fotografia{{s}} selecionada{{s}}
				 */
				photosText: (arg0: string | number | boolean) => LocalizedString
				/**
				 * Faça upload de um uma ou mais fotografias
				 */
				uploadText1: () => LocalizedString
				/**
				 * ou large aqui
				 */
				uploadText2: () => LocalizedString
				/**
				 * PNG, JPG, GIF até 5MB, máximo de {maxFiles} ficheiros
				 */
				uploadText3: (arg: { maxFiles: unknown }) => LocalizedString
			}
			/**
			 * Receber atualizações
			 */
			receiveUpdates: () => LocalizedString
			/**
			 * Opcionalmente receba atualizações do desenvolvimento do arrojamento
			 */
			receiveUpdatesHelpText: () => LocalizedString
			/**
			 * Endereço de email
			 */
			email: () => LocalizedString
			/**
			 * Declaro que li e aceito os termos descritos na
			 */
			privacyPolicyConsentText: () => LocalizedString
			/**
			 * política de privacidade
			 */
			privacyPolicyConsentLink: () => LocalizedString
			animalConditions: {
				/**
				 * Vivo
				 */
				alive: () => LocalizedString
				/**
				 * Fresco
				 */
				fresh: () => LocalizedString
				/**
				 * Em decomposição
				 */
				decomposing: () => LocalizedString
				/**
				 * Mumificado
				 */
				mummified: () => LocalizedString
			}
		}
		buttons: {
			/**
			 * Reportar arrojamento
			 */
			reportStranding: () => LocalizedString
			/**
			 * Reportar avistamento
			 */
			reportSighting: () => LocalizedString
		}
		messages: {
			/**
			 * A enviar
			 */
			sending: () => LocalizedString
			/**
			 * Formulário submetido
			 */
			formSuccessTitle: () => LocalizedString
			/**
			 * Erro ao submeter formulário
			 */
			formErrorTitle: () => LocalizedString
			/**
			 * Obrigado por submeter o formulário
			 */
			formSuccessBody: () => LocalizedString
			/**
			 * Erro interno ao submeter formulário. Se o erro persistir, por favor contacte-nos por telefone: (+351) 911 111 241.
			 */
			formErrorBody: () => LocalizedString
		}
	}
}

export type Formatters = {}
